import { SPORTS_N_LEISURE_FILTER_ID } from '../../../enums/filter-ids/sports-n-leisure.enum';

export const SPORTS_N_LEISURE_FILTER_CONFIGURATION = {
  bubble: [
    SPORTS_N_LEISURE_FILTER_ID.CATEGORIES,
    SPORTS_N_LEISURE_FILTER_ID.PRICE,
    SPORTS_N_LEISURE_FILTER_ID.OBJECT_TYPE,
    SPORTS_N_LEISURE_FILTER_ID.CONDITION,
    SPORTS_N_LEISURE_FILTER_ID.LOCATION,
  ],
  drawer: [
    SPORTS_N_LEISURE_FILTER_ID.CATEGORIES,
    SPORTS_N_LEISURE_FILTER_ID.PRICE,
    SPORTS_N_LEISURE_FILTER_ID.OBJECT_TYPE,
    SPORTS_N_LEISURE_FILTER_ID.CONDITION,
    SPORTS_N_LEISURE_FILTER_ID.LOCATION,
    SPORTS_N_LEISURE_FILTER_ID.POSTED_AGO,
  ],
};
