import { COMPUTERS_N_ELECTRONICS_FILTER_ID } from '../../filter-ids/computers-n-electronic.enum';

export const COMPUTERS_N_ELECTRONICS_CONFIGURATION_FILTERS = {
  bubble: [COMPUTERS_N_ELECTRONICS_FILTER_ID.PRICE],
  drawer: [COMPUTERS_N_ELECTRONICS_FILTER_ID.PRICE],
};
