export enum COMPLETED_TRANSACTION_TRACKING_STATUS {
  DISPUTE_REJECTED_BY_WALLAPOP,
  DISPUTE_CLOSED,
  DISPUTE_EXPIRED,
  TRANSACTION_CANCELLED_BY_SELLER,
  TRANSACTION_EXPIRED,
  TRANSACTION_CANCELLED,
  MONEY_TRANSFERRED,
}
