export enum ANALYTICS_EVENT_NAMES {
	ClickItemCard = 'Click Item Card',
	TapRegisterEmailBack = 'Tap Register Email Back',
	TapRegisterEmailRegister = 'Tap Register Email Register',
	SendFirstMessage = 'Send First Message',
	EditItemCar = 'Edit Item Car',
	EditItemCG = 'Edit Item CG',
	EditItemRE = 'Edit Item RE',
	FavoriteItem = 'Favorite Item',
	TapRegisterPresentationClose = 'Tap Register Presentation Close',
	TapRegisterPresentationEmail = 'Tap Register Presentation Email',
	TapRegisterPresentationFacebook = 'Tap Register Presentation Facebook',
	TapRegisterPresentationGoogle = 'Tap Register Presentation Google',
	TapRegisterPresentationLogin = 'Tap Register Presentation Login',
	ListItemCar = 'List Item Car',
	ListItemCG = 'List Item CG',
	ListItemRE = 'List Item RE',
	ViewChatScreen = 'View Chat Screen',
	ViewItemDetailRecommendationSlider = 'View Item Detail Recommendation Slider',
	ViewOthersItemCarDetail = 'View Others Item Car Detail',
	ViewOthersItemCGDetail = 'View Others Item CG Detail',
	ViewOthersItemREDetail = 'View Others Item RE Detail',
	DisplayRegisterPresentationPage = 'Display Register Presentation Page',
	ViewTransactionPayScreen = 'View Transaction Pay Screen',
	ViewTransactionTimelineScreen = 'View Transaction Timeline Screen',}

