import { COMMON_CONFIGURATION_ID } from '../configuration-ids/common-configuration-ids.enum';
import { COMMON_CONSUMER_GOODS_CONFIGURATION_ID } from '../configuration-ids/consumer-goods-configuration-ids.enum';
import { FASHION_CONFIGURATION_ID } from '../configuration-ids/fashion-configuration-ids.enum';

export enum FASHION_FILTER_ID {
  PRICE = COMMON_CONSUMER_GOODS_CONFIGURATION_ID.PRICE,
  CONDITION = COMMON_CONFIGURATION_ID.CONDITION,
  GENDER = FASHION_CONFIGURATION_ID.GENDER,
  CLOTHING_TYPE = FASHION_CONFIGURATION_ID.OBJECT_TYPE,
  BRAND = FASHION_CONFIGURATION_ID.BRAND,
  SIZE = FASHION_CONFIGURATION_ID.SIZE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
}
