import { COMMON_CONSUMER_GOODS_FILTERS, COMMON_FILTERS } from '@public/shared/components/filters/core/enums/filter-ids/common.enum';

export enum MOTORBIKES_FILTERS {
  PRICE = COMMON_CONSUMER_GOODS_FILTERS.PRICE,
  LOCATION = COMMON_FILTERS.LOCATION,
  POSTED_BEFORE = COMMON_FILTERS.LOCATION,
}
