Parameters:
  EnvName:
    Description: EnvName
    Type: String
  Branch:
    Description: Branch
    Type: String
  Commit:
    Description: Commit
    Type: String
  Bucket:
    Description: Bucket
    Type: String

Conditions:
  IsProdEnv: !Equals [ !Ref EnvName, prod ]

Resources:
  adminDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref Bucket
        CustomErrorResponses:
        - ErrorCachingMinTTL: 60
          ErrorCode: 404
          ResponseCode: 404
          ResponsePagePath: '/'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: 'true'
        HttpVersion: http2
        Origins:
        - DomainName: !Join [ ".", [ !Ref Bucket, "s3.amazonaws.com" ] ]
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/ECJ0NOZMYCRH1
        PriceClass: PriceClass_100
        ViewerCertificate:
          !If
          - IsProdEnv
          - IamCertificateId: 'ASCAJHGNNZ3LDFECH7X46'
            SslSupportMethod: 'sni-only'
          - AcmCertificateArn: 'arn:aws:acm:us-east-1:745640521341:certificate/34cb22eb-e316-4600-abcf-11803c69f764'
            SslSupportMethod: 'sni-only'
      Tags:
      - Key: Branch
        Value: !Ref Branch
      - Key: Commit
        Value: !Ref Commit
      - Key: Env
        Value: !Ref EnvName

  adminRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: 'wallapop.com.'
      RecordSets:
      - AliasTarget:
          DNSName: !GetAtt adminDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
        Name: !Ref Bucket
        Type: A
