Parameters:
  EnvName:
    Description: EnvName
    Type: String
  Branch:
    Description: Branch
    Type: String
  Commit:
    Description: Commit
    Type: String
  BucketES:
    Description: BucketES
    Type: String
  BucketEN:
    Description: BucketEN
    Type: String
  HostES:
    Description: HostES
    Type: String
  HostEN:
    Description: HostEN
    Type: String


Conditions:
  IsProdEnv: !Equals [ !Ref EnvName, prod ]

Mappings:
  Certificates:
    Wildcard:
      default: "arn:aws:acm:us-east-1:745640521341:certificate/e7ed6a3d-db7c-4fae-9daf-a9daea4cc02d"

Resources:
  WebEsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref HostES
        CustomErrorResponses:
        - ErrorCachingMinTTL: 60
          ErrorCode: 404
          ResponseCode: 404
          ResponsePagePath: '/'
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !Join [ ".", [ !Ref BucketES, "s3.amazonaws.com" ] ]
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/ECJ0NOZMYCRH1
        PriceClass: PriceClass_100
        ViewerCertificate:
          !If
          - IsProdEnv
          - AcmCertificateArn: 'arn:aws:acm:us-east-1:745640521341:certificate/f7eb823b-c9de-49b3-8ac0-0d3f6cceeaec'
            SslSupportMethod: 'sni-only'
          - AcmCertificateArn: !FindInMap ["Certificates", "Wildcard", "default"]
            SslSupportMethod: 'sni-only'
      Tags:
      - Key: Branch
        Value: !Ref Branch
      - Key: Commit
        Value: !Ref Commit
      - Key: Env
        Value: !Ref EnvName
      - Key: Project
        Value: Frontend

  WebEnDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref HostEN
        CustomErrorResponses:
        - ErrorCachingMinTTL: 60
          ErrorCode: 404
          ResponseCode: 404
          ResponsePagePath: '/'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !Join [ ".", [ !Ref BucketEN, "s3.amazonaws.com" ] ]
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/ECJ0NOZMYCRH1
        PriceClass: PriceClass_100
        ViewerCertificate:
          !If
          - IsProdEnv
          - IamCertificateId: 'ASCAJHGNNZ3LDFECH7X46'
            SslSupportMethod: 'sni-only'
          - AcmCertificateArn: !FindInMap ["Certificates", "Wildcard", "default"]
            SslSupportMethod: 'sni-only'
      Tags:
      - Key: Branch
        Value: !Ref Branch
      - Key: Commit
        Value: !Ref Commit
      - Key: Env
        Value: !Ref EnvName
      - Key: Project
        Value: Frontend

  WebEsRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: 'wallapop.com.'
      RecordSets:
      - AliasTarget:
          DNSName: !GetAtt WebEsDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
        Name: !Ref HostES
        Type: A

  WebEnRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: 'wallapop.com.'
      RecordSets:
      - AliasTarget:
          DNSName: !GetAtt WebEnDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
        Name: !Ref HostEN
        Type: A
