import { SERVICES_FILTER_ID } from '../../../enums/filter-ids/services.enum';

export const SERVICES_FILTER_CONFIGURATION = {
  bubble: [SERVICES_FILTER_ID.CATEGORIES, SERVICES_FILTER_ID.PRICE, SERVICES_FILTER_ID.OBJECT_TYPE, SERVICES_FILTER_ID.LOCATION],
  drawer: [
    SERVICES_FILTER_ID.CATEGORIES,
    SERVICES_FILTER_ID.PRICE,
    SERVICES_FILTER_ID.OBJECT_TYPE,
    SERVICES_FILTER_ID.LOCATION,
    SERVICES_FILTER_ID.POSTED_AGO,
  ],
};
