import { TRANSACTION_PAYMENT_STATUS } from '@api/core/model/delivery/transaction/status';
import { ToDomainMapper } from '@api/core/utils/types';

enum TRANSACTION_PAYMENT_STATUS_API {
  PENDING_PAY_IN = 'pending pay in',
  REQUIRES_3DS = 'requires 3ds',
  PAY_IN_SUCCEEDED = 'pay in succeeded',
  PENDING_3DS = 'pending 3ds',
  PAY_IN_FAILED = 'pay in failed',
  TRANSFER_SUCCEEDED = 'transfer succeeded',
  PAY_OUT_PENDING_BANK_APPROVE = 'pay out pending bank approve',
  TRANSFER_FAILED = 'transfer failed',
  PAY_OUT_PENDING_BANK_ACCOUNT = 'pay out pending bank account',
  PAY_OUT_FAILED = 'pay out failed',
  PAY_OUT_SUCCEEDED = 'pay out succeeded',
  PAY_OUT_REFUNDED = 'pay out refunded',
  PAY_IN_REFUNDED = 'pay in refunded',
}

const transactionPaymentStatusApiRelation: Record<TRANSACTION_PAYMENT_STATUS_API, TRANSACTION_PAYMENT_STATUS> = {
  [TRANSACTION_PAYMENT_STATUS_API.PENDING_PAY_IN]: TRANSACTION_PAYMENT_STATUS.PENDING_PAY_IN,
  [TRANSACTION_PAYMENT_STATUS_API.REQUIRES_3DS]: TRANSACTION_PAYMENT_STATUS.REQUIRES_3DS,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_IN_SUCCEEDED]: TRANSACTION_PAYMENT_STATUS.PAY_IN_SUCCEEDED,
  [TRANSACTION_PAYMENT_STATUS_API.PENDING_3DS]: TRANSACTION_PAYMENT_STATUS.PENDING_3DS,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_IN_FAILED]: TRANSACTION_PAYMENT_STATUS.PAY_IN_FAILED,
  [TRANSACTION_PAYMENT_STATUS_API.TRANSFER_SUCCEEDED]: TRANSACTION_PAYMENT_STATUS.TRANSFER_SUCCEEDED,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_OUT_PENDING_BANK_APPROVE]: TRANSACTION_PAYMENT_STATUS.PAY_OUT_PENDING_BANK_APPROVE,
  [TRANSACTION_PAYMENT_STATUS_API.TRANSFER_FAILED]: TRANSACTION_PAYMENT_STATUS.TRANSFER_FAILED,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_OUT_PENDING_BANK_ACCOUNT]: TRANSACTION_PAYMENT_STATUS.PAY_OUT_PENDING_BANK_ACCOUNT,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_OUT_FAILED]: TRANSACTION_PAYMENT_STATUS.PAY_OUT_FAILED,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_OUT_SUCCEEDED]: TRANSACTION_PAYMENT_STATUS.PAY_OUT_SUCCEEDED,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_OUT_REFUNDED]: TRANSACTION_PAYMENT_STATUS.PAY_OUT_REFUNDED,
  [TRANSACTION_PAYMENT_STATUS_API.PAY_IN_REFUNDED]: TRANSACTION_PAYMENT_STATUS.PAY_IN_REFUNDED,
};

export const mapTransactionPaymentStatusApiToModel: ToDomainMapper<string, TRANSACTION_PAYMENT_STATUS> = (
  input: string
): TRANSACTION_PAYMENT_STATUS => {
  return transactionPaymentStatusApiRelation[input];
};
