/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tap on back button on wallapop register screen after register presentation page
 */
export interface TapRegisterEmailBack {
  /**
   * Identifier of the screen that the user arrives to the register page
   */
  screenId: number;
  [k: string]: any;
}
