export enum FILTER_QUERY_PARAM_KEY {
  categoryId = 'category_ids',
  objectType = 'object_type_id',
  maxPrice = 'max_sale_price',
  minPrice = 'min_sale_price',
  postedAgo = 'time_filter',
  condition = 'condition',

  operation = 'operation',
  gender = 'gender',

  brand = 'brand',
  model = 'model',
  bodyType = 'body_type',
  engine = 'engine',
  gearbox = 'gearbox',
  warranty = 'warranty',
  professional = 'professional',
  maxHorsePower = 'max_horse_power',
  minHorsePower = 'min_horse_power',
  minYear = 'min_year',
  maxYear = 'max_year',
  minKm = 'min_km',
  maxKm = 'max_km',
  minDoors = 'min_num_doors',
  maxDoors = 'max_num_doors',
  minSeats = 'min_seats',
  maxSeats = 'max_seats',

  minSurface = 'min_surface',
  maxSurface = 'max_surface',
  type = 'type',
}
