import { REAL_ESTATE_CONFIGURATION_ID } from '../../../enums/configuration-ids/real-estate-configuration-ids.enum';
import { FILTER_TYPES } from '../../../enums/filter-types/filter-types.enum';
import { FilterConfigType } from '../filter-configurations';

const REAL_ESTATE_FILTER_CONFIGURATION_DEFAULT: FilterConfigType[] = [
  {
    id: REAL_ESTATE_CONFIGURATION_ID.DEFAULT_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [0, 5000000],
    stepsConfig: [
      { range: [0, 1000], step: 100 },
      { range: [1000, 10000], step: 500 },
      { range: [10000, 50000], step: 5000 },
      { range: [50000, 5000000], step: 50000 },
    ],
    limitless: true,
  },
];

const REAL_ESTATE__FILTER_CONFIGURATION_BUY_PRICE: FilterConfigType[] = [
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_BOX_ROOM_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [1000, 100000],
    stepsConfig: [{ range: [1000, 100000], step: 1000 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_DEFAULT_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [0, 5000000],
    stepsConfig: [
      { range: [0, 1000], step: 100 },
      { range: [1000, 10000], step: 500 },
      { range: [10000, 50000], step: 5000 },
      { range: [50000, 5000000], step: 50000 },
    ],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_FLAT_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [50000, 3000000],
    stepsConfig: [{ range: [50000, 3000000], step: 25000 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_GARAGE_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [1000, 100000],
    stepsConfig: [{ range: [1000, 100000], step: 1000 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_HOUSE_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [50000, 3000000],
    stepsConfig: [{ range: [50000, 3000000], step: 25000 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_LAND_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [50000, 3000000],
    stepsConfig: [{ range: [50000, 3000000], step: 25000 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_OFFICE_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [50000, 3000000],
    stepsConfig: [{ range: [50000, 3000000], step: 25000 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BUY_OFFICE_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [50000, 3000000],
    stepsConfig: [{ range: [50000, 3000000], step: 25000 }],
    limitless: true,
  },
];

const REAL_ESTATE__FILTER_CONFIGURATION_RENT_PRICE: FilterConfigType[] = [
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_BOX_ROOM_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [10, 1000],
    stepsConfig: [{ range: [10, 1000], step: 10 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_DEFAULT_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [0, 5000000],
    stepsConfig: [
      { range: [0, 1000], step: 100 },
      { range: [1000, 10000], step: 500 },
      { range: [10000, 50000], step: 5000 },
      { range: [50000, 5000000], step: 50000 },
    ],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_FLAT_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [100, 3000],
    stepsConfig: [{ range: [100, 3000], step: 100 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_GARAGE_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [25, 700],
    stepsConfig: [{ range: [25, 700], step: 25 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_HOUSE_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [100, 3000],
    stepsConfig: [{ range: [100, 3000], step: 100 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_LAND_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [100, 30000],
    stepsConfig: [{ range: [100, 30000], step: 100 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_OFFICE_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [100, 30000],
    stepsConfig: [{ range: [100, 30000], step: 100 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.RENT_ROOM_PRICE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterPriceTitle:How much?`,
    icon: '/assets/icons/filters/price.svg',
    bubblePlaceholder: $localize`:@@filterPriceBubblePlaceholder:Price`,
    mapKey: {
      minKey: 'min_sale_price',
      maxKey: 'max_sale_price',
    },
    units: '€',
    range: [50, 1000],
    stepsConfig: [{ range: [50, 1000], step: 50 }],
    limitless: true,
  },
];

const REAL_ESTATE__FILTER_CONFIGURATION_SURFACE: FilterConfigType[] = [
  {
    id: REAL_ESTATE_CONFIGURATION_ID.FLAT_SURFACE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterSurfaceTitle:Surface`,
    icon: '/assets/icons/filters/surface.svg',
    bubblePlaceholder: $localize`:@@filterSurfaceBubblePlaceholder:Surface`,
    mapKey: {
      minKey: 'min_surface',
      maxKey: 'max_surface',
    },
    units: 'm²',
    range: [40, 1000],
    stepsConfig: [{ range: [40, 1000], step: 20 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.LAND_SURFACE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterSurfaceTitle:Surface`,
    icon: '/assets/icons/filters/surface.svg',
    bubblePlaceholder: $localize`:@@filterSurfaceBubblePlaceholder:Surface`,
    mapKey: {
      minKey: 'min_surface',
      maxKey: 'max_surface',
    },
    units: 'm²',
    range: [100, 10000],
    stepsConfig: [{ range: [100, 1000], step: 100 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.HOUSE_SURFACE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterSurfaceTitle:Surface`,
    icon: '/assets/icons/filters/surface.svg',
    bubblePlaceholder: $localize`:@@filterSurfaceBubblePlaceholder:Surface`,
    mapKey: {
      minKey: 'min_surface',
      maxKey: 'max_surface',
    },
    units: 'm²',
    range: [40, 1000],
    stepsConfig: [{ range: [40, 1000], step: 20 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.OFFICE_SURFACE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterSurfaceTitle:Surface`,
    icon: '/assets/icons/filters/surface.svg',
    bubblePlaceholder: $localize`:@@filterSurfaceBubblePlaceholder:Surface`,
    mapKey: {
      minKey: 'min_surface',
      maxKey: 'max_surface',
    },
    units: 'm²',
    range: [50, 1000],
    stepsConfig: [{ range: [40, 1000], step: 50 }],
    limitless: true,
  },
  {
    id: REAL_ESTATE_CONFIGURATION_ID.BOX_ROOM_SURFACE,
    type: FILTER_TYPES.RANGE,
    title: $localize`:@@filterSurfaceTitle:Surface`,
    icon: '/assets/icons/filters/surface.svg',
    bubblePlaceholder: $localize`:@@filterSurfaceBubblePlaceholder:Surface`,
    mapKey: {
      minKey: 'min_surface',
      maxKey: 'max_surface',
    },
    units: 'm²',
    range: [2, 200],
    stepsConfig: [{ range: [2, 200], step: 2 }],
    limitless: true,
  },
];

export const REAL_ESTATE__FILTERS: FilterConfigType[] = [
  ...REAL_ESTATE_FILTER_CONFIGURATION_DEFAULT,
  ...REAL_ESTATE__FILTER_CONFIGURATION_BUY_PRICE,
  ...REAL_ESTATE__FILTER_CONFIGURATION_RENT_PRICE,
  ...REAL_ESTATE__FILTER_CONFIGURATION_SURFACE,
];
