export enum PAYVIEW_EVENT_TYPE {
  ERROR_ON_GET_CURRENT_STATE,
  ERROR_ON_REFRESH_COSTS,
  ERROR_ON_REFRESH_DELIVERY_COSTS,
  ERROR_ON_REFRESH_DELIVERY_METHODS,
  ERROR_ON_SET_DELIVERY_METHOD,
  SUCCESS_ON_GET_CURRENT_STATE,
  SUCCESS_ON_REFRESH_COSTS,
  SUCCESS_ON_REFRESH_DELIVERY_COSTS,
  SUCCESS_ON_REFRESH_DELIVERY_METHODS,
  SUCCESS_ON_SET_DELIVERY_METHOD,
}
