import { CATEGORY_IDS } from '@core/category/category-ids';

export const CATEGORY_SUBSCRIPTIONS_IDS = {
  ...CATEGORY_IDS,
  CONSUMER_GOODS: 0,
};

export const CATEGORIES_EXCLUDED_FROM_EVERYTHING_ELSE = [CATEGORY_IDS.CAR, CATEGORY_IDS.MOTORBIKE, CATEGORY_IDS.MOTOR_ACCESSORIES];
