import { CATEGORY_IDS } from '@core/category/category-ids';

export enum CATEGORY_SUBSCRIPTIONS_IDS {
  CAR = CATEGORY_IDS.CAR,
  REAL_ESTATE = CATEGORY_IDS.REAL_ESTATE,
  MOTORBIKE = CATEGORY_IDS.MOTORBIKE,
  MOTOR_ACCESSORIES = CATEGORY_IDS.MOTOR_ACCESSORIES,
  CONSUMER_GOODS = 0,
}

export const CATEGORIES_EXCLUDED_FROM_CONSUMER_GOODS = [CATEGORY_IDS.CAR, CATEGORY_IDS.MOTORBIKE, CATEGORY_IDS.MOTOR_ACCESSORIES];
