import { CATEGORY_IDS } from '@core/category/category-ids';

export const SORT_BY_RELEVANCE_CATEGORY_IDS = [
  CATEGORY_IDS.APPLIANCES,
  CATEGORY_IDS.BABIES_CHILD,
  CATEGORY_IDS.BIKES,
  CATEGORY_IDS.CELL_PHONES_ACCESSORIES,
  CATEGORY_IDS.COLLECTIBLES_ART,
  CATEGORY_IDS.COMPUTERS_ELECTRONICS,
  CATEGORY_IDS.CONSTRUCTION,
  CATEGORY_IDS.FASHION_ACCESSORIES,
  CATEGORY_IDS.GAMES_BOOKS,
  CATEGORY_IDS.GAMES_CONSOLES,
  CATEGORY_IDS.HOME_GARDEN,
  CATEGORY_IDS.JOBS,
  CATEGORY_IDS.MOTORBIKE,
  CATEGORY_IDS.MOTOR_ACCESSORIES,
  CATEGORY_IDS.OTHERS,
  CATEGORY_IDS.SERVICES,
  CATEGORY_IDS.SPORTS_LEISURE,
  CATEGORY_IDS.TV_AUDIO_CAMERAS,
];
