import { CAR_CONFIGURATION_ID } from '../../configuration-ids/car-configuration-ids';

export const CAR_CONFIGURATION_FILTERS = {
  bubble: [CAR_CONFIGURATION_ID.PRICE, CAR_CONFIGURATION_ID.PROFESSIONAL, CAR_CONFIGURATION_ID.YEAR, CAR_CONFIGURATION_ID.KM],
  drawer: [CAR_CONFIGURATION_ID.PRICE, CAR_CONFIGURATION_ID.KM, CAR_CONFIGURATION_ID.YEAR, CAR_CONFIGURATION_ID.WARRANTY],
};
