Parameters:
  EnvName:
    Description: 'Environment where it has to be deployed'
    Type: String
  ProjectName:
    Description: 'Name of this project'
    Type: String
  BucketNameFunctionalWebapp:
    Description: 'Name of the bucket where the functional webapp is hosted in multiple locales'
    Type: String

Resources:
  FunctionalWebappCloudFrontOriginaccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access identity for CloudFront functional webapp distribution'

  FunctionalWebappPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketNameFunctionalWebapp
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:List*
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${BucketNameFunctionalWebapp}/*"
              - !Sub "arn:aws:s3:::${BucketNameFunctionalWebapp}"
            Principal:
              CanonicalUser: !GetAtt FunctionalWebappCloudFrontOriginaccessIdentity.S3CanonicalUserId

