import { CATEGORY_SUBSCRIPTIONS_IDS } from '../category-subscription-ids';

export const CATEGORIES_WITH_HIGHEST_LIMIT_ACTIVE = [
  CATEGORY_SUBSCRIPTIONS_IDS.REAL_ESTATE,
  CATEGORY_SUBSCRIPTIONS_IDS.CONSUMER_GOODS,
  CATEGORY_SUBSCRIPTIONS_IDS.CAR,
];
