export enum CAR_SPECIFICATION_TYPE {
  SEATS = 'seats',
  COUPE = 'coupe_cabrio',
  FAMILY = 'family_car',
  MINI_VAN = 'mini_van',
  SEDAN = 'sedan',
  SMALL = 'small_car',
  VAN = 'van',
  FXF = '4X4',
  OTHERS = 'other',
  TWO_DOORS = 'two_doors',
  THREE_DOORS = 'three_doors',
  FOUR_DOORS = 'four_doors',
  FIVE_DOORS = 'five_doors',
  HORSEPOWER = 'horsepower',
  ELECTRIC = 'electric-hybrid',
  GASOIL = 'gasoil',
  GASOLINE = 'gasoline',
  AUTOMATIC = 'automatic',
  MANUAL = 'manual',
  CONDITION_0 = 'brand_new',
  CONDITION_1 = 'mint',
  CONDITION_2 = 'some_blow',
  CONDITION_3 = 'crappy',
}
