export enum REAL_STATE_TYPE {
  GARAGE = 'garage',
  ELEVATOR = 'elevator',
  GARDEN = 'garden',
  POOL = 'pool',
  TERRACE = 'terrace',
  BATHROOMS = 'bathrooms',
  ROOMS = 'rooms',
  SURFACE = 'surface',
  FLAT = 'flat',
  HOUSE = 'house',
  OFFICE = 'office',
  LAND = 'land',
  BOX_ROOM = 'box_room',
  NEW_BUILD = 'new_build',
  GOOD_CONDITION = 'good_condition',
  TO_REFORM = 'to_reform',
}
