import { COMPLETED_TRANSACTION_TRACKING_STATUS } from '@api/core/model/delivery/transaction/status';
import { HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE } from '@shared/historic-list/enums/historic-element-subdescription-type.enum';

export const mapCompletedTransactionTrackingStatusToSubDescription: Record<
  COMPLETED_TRANSACTION_TRACKING_STATUS,
  HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE
> = {
  [COMPLETED_TRANSACTION_TRACKING_STATUS.MONEY_TRANSFERRED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.NORMAL,
  [COMPLETED_TRANSACTION_TRACKING_STATUS.TRANSACTION_CANCELLED_BY_SELLER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [COMPLETED_TRANSACTION_TRACKING_STATUS.TRANSACTION_EXPIRED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [COMPLETED_TRANSACTION_TRACKING_STATUS.TRANSACTION_CANCELLED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [COMPLETED_TRANSACTION_TRACKING_STATUS.DISPUTE_REJECTED_BY_WALLAPOP]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [COMPLETED_TRANSACTION_TRACKING_STATUS.DISPUTE_CLOSED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [COMPLETED_TRANSACTION_TRACKING_STATUS.DISPUTE_EXPIRED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
};
