AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This template contains an imported bucket that already exists in AWS.

Parameters:
  BucketNameES:
    Description: 'Name of the bucket ES'
    Type: String
  BucketNameEN:
    Description: 'Name of the bucket EN'
    Type: String

Resources:
  HostingBucketES:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${BucketNameES}"

  HostingBucketEN:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${BucketNameEN}"
