AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This template contains imported bucket that already exist in AWS.

Parameters:
  BucketNameFunctionalWebapp:
    Description: 'Name of the bucket where the functional webapp is hosted in multiple locales'
    Type: String

Resources:
  HostingBucketFunctionalWebapp:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${BucketNameFunctionalWebapp}"
