AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This template contains imported bucket that already exist in AWS.

Parameters:
  BucketNameES:
    Description: 'Name of the bucket ES' # todo: if we use the same template and properties for beta for both accounts, it'll throw an error because the bucket already exists
    Type: String
  BucketNameEN:
    Description: 'Name of the bucket EN' # todo: if we use the same template and properties for beta for both accounts, it'll throw an error because the bucket already exists
    Type: String

Resources:
  HostingBucketES:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${BucketNameES}"
  HostingBucketEN:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${BucketNameEN}"
