import { PhonePrefixOption } from '../interfaces/phone-prefix-option.interface';

export const PHONE_PREFIXES: PhonePrefixOption[] = [
  { value: '+7 840', label: 'Abkhazia (+7 840)', country_code: 'AB' },
  { value: '+7 940', label: 'Abkhazia (+7 940)', country_code: 'AB' },
  { value: '+93', label: 'Afghanistan (+93)', country_code: 'AF' },
  { value: '+355', label: 'Albania (+355)', country_code: 'AL' },
  { value: '+213', label: 'Algeria (+213)', country_code: 'DZ' },
  { value: '+1 684', label: 'American Samoa (+1 684)', country_code: 'AS' },
  { value: '+376', label: 'Andorra (+376)', country_code: 'AD' },
  { value: '+244', label: 'Angola (+244)', country_code: 'AO' },
  { value: '+1 264', label: 'Anguilla (+1 264)', country_code: 'AI' },
  { value: '+1 268', label: 'Antigua and Barbuda (+1 268)', country_code: 'AG' },
  { value: '+54', label: 'Argentina (+54)', country_code: 'AR' },
  { value: '+374', label: 'Armenia (+374)', country_code: 'AM' },
  { value: '+297', label: 'Aruba (+297)', country_code: 'AW' },
  { value: '+247', label: 'Ascension (+247)', country_code: 'AC' },
  { value: '+61', label: 'Australia (+61)', country_code: 'AU' },
  { value: '+672', label: 'Australian External Territories (+672)', country_code: 'AC' },
  { value: '+43', label: 'Austria (+43)', country_code: 'AT' },
  { value: '+994', label: 'Azerbaijan (+994)', country_code: 'AZ' },
  { value: '+1 242', label: 'Bahamas (+1 242)', country_code: 'BS' },
  { value: '+973', label: 'Bahrain (+973)', country_code: 'BH' },
  { value: '+880', label: 'Bangladesh (+880)', country_code: 'BD' },
  { value: '+1 246', label: 'Barbados (+1 246)', country_code: 'BB' },
  { value: '+1 268', label: 'Barbuda (+1 268)', country_code: 'AG' },
  { value: '+375', label: 'Belarus (+375)', country_code: 'BY' },
  { value: '+32', label: 'Belgium (+32)', country_code: 'BE' },
  { value: '+501', label: 'Belize (+501)', country_code: 'BZ' },
  { value: '+229', label: 'Benin (+229)', country_code: 'BJ' },
  { value: '+1 441', label: 'Bermuda (+1 441)', country_code: 'BM' },
  { value: '+975', label: 'Bhutan (+975)', country_code: 'BT' },
  { value: '+591', label: 'Bolivia (+591)', country_code: 'BO' },
  { value: '+387', label: 'Bosnia and Herzegovina (+387)', country_code: 'BA' },
  { value: '+267', label: 'Botswana (+267)', country_code: 'BW' },
  { value: '+55', label: 'Brazil (+55)', country_code: 'BR' },
  { value: '+246', label: 'British Indian Ocean Territory (+246)', country_code: 'IO' },
  { value: '+1 284', label: 'British Virgin Islands (+1 284)', country_code: 'VG' },
  { value: '+673', label: 'Brunei (+673)', country_code: 'BN' },
  { value: '+359', label: 'Bulgaria (+359)', country_code: 'BG' },
  { value: '+226', label: 'Burkina Faso (+226)', country_code: 'BF' },
  { value: '+257', label: 'Burundi (+257)', country_code: 'BI' },
  { value: '+855', label: 'Cambodia (+855)', country_code: 'KH' },
  { value: '+237', label: 'Cameroon (+237)', country_code: 'CM' },
  { value: '+1', label: 'Canada (+1)', country_code: 'CA' },
  { value: '+238', label: 'Cape Verde (+238)', country_code: 'CV' },
  { value: '+ 345', label: 'Cayman Islands (+ 345)', country_code: 'KY' },
  { value: '+236', label: 'Central African Republic (+236)', country_code: 'CF' },
  { value: '+235', label: 'Chad (+235)', country_code: 'TD' },
  { value: '+56', label: 'Chile (+56)', country_code: 'CL' },
  { value: '+86', label: 'China (+86)', country_code: 'CN' },
  { value: '+61', label: 'Christmas Island (+61)', country_code: 'CX' },
  { value: '+61', label: 'Cocos-Keeling Islands (+61)', country_code: 'CC' },
  { value: '+57', label: 'Colombia (+57)', country_code: 'CO' },
  { value: '+269', label: 'Comoros (+269)', country_code: 'KM' },
  { value: '+242', label: 'Congo (+242)', country_code: 'CG' },
  { value: '+243', label: 'Congo, Dem. Rep. of (Zaire) (+243)', country_code: 'CD' },
  { value: '+682', label: 'Cook Islands (+682)', country_code: 'CK' },
  { value: '+506', label: 'Costa Rica (+506)', country_code: 'CR' },
  { value: '+385', label: 'Croatia (+385)', country_code: 'HR' },
  { value: '+53', label: 'Cuba (+53)', country_code: 'CU' },
  { value: '+599', label: 'Curacao (+599)', country_code: 'CW' },
  { value: '+537', label: 'Cyprus (+537)', country_code: 'CY' },
  { value: '+420', label: 'Czech Republic (+420)', country_code: 'CZ' },
  { value: '+45', label: 'Denmark (+45)', country_code: 'DK' },
  { value: '+246', label: 'Diego Garcia (+246)', country_code: 'DG' },
  { value: '+253', label: 'Djibouti (+253)', country_code: 'DJ' },
  { value: '+1 767', label: 'Dominica (+1 767)', country_code: 'DM' },
  { value: '+1 809', label: 'Dominican Republic (+1 809)', country_code: 'DO' },
  { value: '+1 829', label: 'Dominican Republic (+1 829)', country_code: 'DO' },
  { value: '+1 849', label: 'Dominican Republic (+1 849)', country_code: 'DO' },
  { value: '+670', label: 'East Timor (+670)', country_code: 'TP' },
  { value: '+56', label: 'Easter Island (+56)', country_code: 'EI' },
  { value: '+593', label: 'Ecuador (+593)', country_code: 'EC' },
  { value: '+20', label: 'Egypt (+20)', country_code: 'EG' },
  { value: '+503', label: 'El Salvador (+503)', country_code: 'SV' },
  { value: '+240', label: 'Equatorial Guinea (+240)', country_code: 'GQ' },
  { value: '+291', label: 'Eritrea (+291)', country_code: 'ER' },
  { value: '+372', label: 'Estonia (+372)', country_code: 'EE' },
  { value: '+251', label: 'Ethiopia (+251)', country_code: 'ET' },
  { value: '+500', label: 'Falkland Islands (+500)', country_code: 'FK' },
  { value: '+298', label: 'Faroe Islands (+298)', country_code: 'FO' },
  { value: '+679', label: 'Fiji (+679)', country_code: 'FJ' },
  { value: '+358', label: 'Finland (+358)', country_code: 'FI' },
  { value: '+33', label: 'France (+33)', country_code: 'FR' },
  { value: '+596', label: 'French Antilles (+596)', country_code: '' },
  { value: '+594', label: 'French Guiana (+594)', country_code: 'GF' },
  { value: '+689', label: 'French Polynesia (+689)', country_code: 'PF' },
  { value: '+241', label: 'Gabon (+241)', country_code: 'GA' },
  { value: '+220', label: 'Gambia (+220)', country_code: 'GM' },
  { value: '+995', label: 'Georgia (+995)', country_code: 'GE' },
  { value: '+49', label: 'Germany (+49)', country_code: 'DE' },
  { value: '+233', label: 'Ghana (+233)', country_code: 'GH' },
  { value: '+350', label: 'Gibraltar (+350)', country_code: 'GI' },
  { value: '+30', label: 'Greece (+30)', country_code: 'GR' },
  { value: '+299', label: 'Greenland (+299)', country_code: 'GL' },
  { value: '+1 473', label: 'Grenada (+1 473)', country_code: 'GD' },
  { value: '+590', label: 'Guadeloupe (+590)', country_code: 'GP' },
  { value: '+1 671', label: 'Guam (+1 671)', country_code: 'GU' },
  { value: '+502', label: 'Guatemala (+502)', country_code: 'GT' },
  { value: '+224', label: 'Guinea (+224)', country_code: 'GN' },
  { value: '+245', label: 'Guinea-Bissau (+245)', country_code: 'GW' },
  { value: '+595', label: 'Guyana (+595)', country_code: 'GY' },
  { value: '+509', label: 'Haiti (+509)', country_code: 'HT' },
  { value: '+504', label: 'Honduras (+504)', country_code: 'HN' },
  { value: '+852', label: 'Hong Kong SAR China (+852)', country_code: 'HK' },
  { value: '+36', label: 'Hungary (+36)', country_code: 'HU' },
  { value: '+354', label: 'Iceland (+354)', country_code: 'IS' },
  { value: '+91', label: 'India (+91)', country_code: 'IN' },
  { value: '+62', label: 'Indonesia (+62)', country_code: 'ID' },
  { value: '+98', label: 'Iran (+98)', country_code: 'IR' },
  { value: '+964', label: 'Iraq (+964)', country_code: 'IQ' },
  { value: '+353', label: 'Ireland (+353)', country_code: 'IE' },
  { value: '+972', label: 'Israel (+972)', country_code: 'IL' },
  { value: '+39', label: 'Italy (+39)', country_code: 'IT' },
  { value: '+225', label: 'Ivory Coast (+225)', country_code: 'CI' },
  { value: '+1 876', label: 'Jamaica (+1 876)', country_code: 'JM' },
  { value: '+81', label: 'Japan (+81)', country_code: 'JP' },
  { value: '+962', label: 'Jordan (+962)', country_code: 'JO' },
  { value: '+7 7', label: 'Kazakhstan (+7 7)', country_code: 'KZ' },
  { value: '+254', label: 'Kenya (+254)', country_code: 'KE' },
  { value: '+686', label: 'Kiribati (+686)', country_code: 'KI' },
  { value: '+965', label: 'Kuwait (+965)', country_code: 'KW' },
  { value: '+996', label: 'Kyrgyzstan (+996)', country_code: 'KG' },
  { value: '+856', label: 'Laos (+856)', country_code: 'LA' },
  { value: '+371', label: 'Latvia (+371)', country_code: 'LV' },
  { value: '+961', label: 'Lebanon (+961)', country_code: 'LB' },
  { value: '+266', label: 'Lesotho (+266)', country_code: 'LS' },
  { value: '+231', label: 'Liberia (+231)', country_code: 'LR' },
  { value: '+218', label: 'Libya (+218)', country_code: 'LY' },
  { value: '+423', label: 'Liechtenstein (+423)', country_code: 'LI' },
  { value: '+370', label: 'Lithuania (+370)', country_code: 'LT' },
  { value: '+352', label: 'Luxembourg (+352)', country_code: 'LU' },
  { value: '+853', label: 'Macau SAR China (+853)', country_code: 'MO' },
  { value: '+389', label: 'Macedonia (+389)', country_code: 'MK' },
  { value: '+261', label: 'Madagascar (+261)', country_code: 'MG' },
  { value: '+265', label: 'Malawi (+265)', country_code: 'MW' },
  { value: '+60', label: 'Malaysia (+60)', country_code: 'MY' },
  { value: '+960', label: 'Maldives (+960)', country_code: 'MV' },
  { value: '+223', label: 'Mali (+223)', country_code: 'ML' },
  { value: '+356', label: 'Malta (+356)', country_code: 'MT' },
  { value: '+692', label: 'Marshall Islands (+692)', country_code: 'MH' },
  { value: '+596', label: 'Martinique (+596)', country_code: 'MQ' },
  { value: '+222', label: 'Mauritania (+222)', country_code: 'MR' },
  { value: '+230', label: 'Mauritius (+230)', country_code: 'MU' },
  { value: '+262', label: 'Mayotte (+262)', country_code: 'YT' },
  { value: '+52', label: 'Mexico (+52)', country_code: 'MX' },
  { value: '+691', label: 'Micronesia (+691)', country_code: 'FM' },
  { value: '+1 808', label: 'Midway Island (+1 808)', country_code: 'MI' },
  { value: '+373', label: 'Moldova (+373)', country_code: 'MD' },
  { value: '+377', label: 'Monaco (+377)', country_code: 'MC' },
  { value: '+976', label: 'Mongolia (+976)', country_code: 'MN' },
  { value: '+382', label: 'Montenegro (+382)', country_code: 'ME' },
  { value: '+1664', label: 'Montserrat (+1664)', country_code: 'MS' },
  { value: '+212', label: 'Morocco (+212)', country_code: 'MA' },
  { value: '+95', label: 'Myanmar (+95)', country_code: 'MM' },
  { value: '+264', label: 'Namibia (+264)', country_code: 'NA' },
  { value: '+674', label: 'Nauru (+674)', country_code: 'NR' },
  { value: '+977', label: 'Nepal (+977)', country_code: 'NP' },
  { value: '+31', label: 'Netherlands (+31)', country_code: 'NL' },
  { value: '+599', label: 'Netherlands Antilles (+599)', country_code: 'AN' },
  { value: '+1 869', label: 'Nevis (+1 869)', country_code: 'KN' },
  { value: '+687', label: 'New Caledonia (+687)', country_code: 'NC' },
  { value: '+64', label: 'New Zealand (+64)', country_code: 'NZ' },
  { value: '+505', label: 'Nicaragua (+505)', country_code: 'NI' },
  { value: '+227', label: 'Niger (+227)', country_code: 'NE' },
  { value: '+234', label: 'Nigeria (+234)', country_code: 'NG' },
  { value: '+683', label: 'Niue (+683)', country_code: 'NU' },
  { value: '+672', label: 'Norfolk Island (+672)', country_code: 'NF' },
  { value: '+850', label: 'North Korea (+850)', country_code: 'KP' },
  { value: '+1 670', label: 'Northern Mariana Islands (+1 670)', country_code: 'MP' },
  { value: '+47', label: 'Norway (+47)', country_code: 'NO' },
  { value: '+968', label: 'Oman (+968)', country_code: 'OM' },
  { value: '+92', label: 'Pakistan (+92)', country_code: 'PK' },
  { value: '+680', label: 'Palau (+680)', country_code: 'PW' },
  { value: '+970', label: 'Palestinian Territory (+970)', country_code: 'PS' },
  { value: '+507', label: 'Panama (+507)', country_code: 'PA' },
  { value: '+675', label: 'Papua New Guinea (+675)', country_code: 'PG' },
  { value: '+595', label: 'Paraguay (+595)', country_code: 'PY' },
  { value: '+51', label: 'Peru (+51)', country_code: 'PE' },
  { value: '+63', label: 'Philippines (+63)', country_code: 'PH' },
  { value: '+48', label: 'Poland (+48)', country_code: 'PL' },
  { value: '+351', label: 'Portugal (+351)', country_code: 'PT' },
  { value: '+1 787', label: 'Puerto Rico (+1 787)', country_code: 'PR' },
  { value: '+1 939', label: 'Puerto Rico (+1 939)', country_code: 'PR' },
  { value: '+974', label: 'Qatar (+974)', country_code: 'QA' },
  { value: '+262', label: 'Reunion (+262)', country_code: 'RE' },
  { value: '+40', label: 'Romania (+40)', country_code: 'RO' },
  { value: '+7', label: 'Russia (+7)', country_code: 'RU' },
  { value: '+250', label: 'Rwanda (+250)', country_code: 'RW' },
  { value: '+685', label: 'Samoa (+685)', country_code: 'WS' },
  { value: '+378', label: 'San Marino (+378)', country_code: 'SM' },
  { value: '+966', label: 'Saudi Arabia (+966)', country_code: 'SA' },
  { value: '+221', label: 'Senegal (+221)', country_code: 'SN' },
  { value: '+381', label: 'Serbia (+381)', country_code: 'RS' },
  { value: '+248', label: 'Seychelles (+248)', country_code: 'SC' },
  { value: '+232', label: 'Sierra Leone (+232)', country_code: 'SL' },
  { value: '+65', label: 'Singapore (+65)', country_code: 'SG' },
  { value: '+421', label: 'Slovakia (+421)', country_code: 'SK' },
  { value: '+386', label: 'Slovenia (+386)', country_code: 'SI' },
  { value: '+677', label: 'Solomon Islands (+677)', country_code: 'SB' },
  { value: '+27', label: 'South Africa (+27)', country_code: 'ZA' },
  { value: '+500', label: 'South Georgia and the South Sandwich Islands (+500)', country_code: 'GS' },
  { value: '+82', label: 'South Korea (+82)', country_code: 'KR' },
  { value: '+34', label: 'Spain (+34)', country_code: 'ES' },
  { value: '+94', label: 'Sri Lanka (+94)', country_code: 'LK' },
  { value: '+249', label: 'Sudan (+249)', country_code: 'SD' },
  { value: '+597', label: 'Suriname (+597)', country_code: 'SR' },
  { value: '+268', label: 'Swaziland (+268)', country_code: 'SZ' },
  { value: '+46', label: 'Sweden (+46)', country_code: 'SE' },
  { value: '+41', label: 'Switzerland (+41)', country_code: 'CH' },
  { value: '+963', label: 'Syria (+963)', country_code: 'SY' },
  { value: '+886', label: 'Taiwan (+886)', country_code: 'TW' },
  { value: '+992', label: 'Tajikistan (+992)', country_code: 'TJ' },
  { value: '+255', label: 'Tanzania (+255)', country_code: 'TZ' },
  { value: '+66', label: 'Thailand (+66)', country_code: 'TH' },
  { value: '+670', label: 'Timor Leste (+670)', country_code: 'TL' },
  { value: '+228', label: 'Togo (+228)', country_code: 'TG' },
  { value: '+690', label: 'Tokelau (+690)', country_code: 'TK' },
  { value: '+676', label: 'Tonga (+676)', country_code: 'TO' },
  { value: '+1 868', label: 'Trinidad and Tobago (+1 868)', country_code: 'TT' },
  { value: '+216', label: 'Tunisia (+216)', country_code: 'TN' },
  { value: '+90', label: 'Turkey (+90)', country_code: 'TR' },
  { value: '+993', label: 'Turkmenistan (+993)', country_code: 'TM' },
  { value: '+1 649', label: 'Turks and Caicos Islands (+1 649)', country_code: 'TC' },
  { value: '+688', label: 'Tuvalu (+688)', country_code: 'TV' },
  { value: '+1 340', label: 'U.S. Virgin Islands (+1 340)', country_code: 'VI' },
  { value: '+256', label: 'Uganda (+256)', country_code: 'UG' },
  { value: '+380', label: 'Ukraine (+380)', country_code: 'UA' },
  { value: '+971', label: 'United Arab Emirates (+971)', country_code: 'AE' },
  { value: '+44', label: 'United Kingdom (+44)', country_code: 'GB' },
  { value: '+1', label: 'United States (+1)', country_code: 'US' },
  { value: '+598', label: 'Uruguay (+598)', country_code: 'UY' },
  { value: '+998', label: 'Uzbekistan (+998)', country_code: 'UZ' },
  { value: '+678', label: 'Vanuatu (+678)', country_code: 'VU' },
  { value: '+58', label: 'Venezuela (+58)', country_code: 'VE' },
  { value: '+84', label: 'Vietnam (+84)', country_code: 'VN' },
  { value: '+1 808', label: 'Wake Island (+1 808)', country_code: 'WK' },
  { value: '+681', label: 'Wallis and Futuna (+681)', country_code: 'WF' },
  { value: '+967', label: 'Yemen (+967)', country_code: 'YE' },
  { value: '+260', label: 'Zambia (+260)', country_code: 'ZM' },
  { value: '+255', label: 'Zanzibar (+255)', country_code: '' },
  { value: '+263', label: 'Zimbabwe (+263)', country_code: 'ZW' },
];
