import { APP_LOCALE } from '@configs/subdomains.config';
import { PhonePrefix } from '../interfaces/phone-prefix.interface';

const PHONE_PREFIXES_EN: Array<PhonePrefix> = [
  { prefix: '+7 840', country: 'Abkhazia' },
  { prefix: '+7 940', country: 'Abkhazia' },
  { prefix: '+93', country: 'Afghanistan' },
  { prefix: '+355', country: 'Albania' },
  { prefix: '+213', country: 'Algeria' },
  { prefix: '+1 684', country: 'American Samoa' },
  { prefix: '+376', country: 'Andorra' },
  { prefix: '+244', country: 'Angola' },
  { prefix: '+1 264', country: 'Anguilla' },
  { prefix: '+1 268', country: 'Antigua and Barbuda' },
  { prefix: '+54', country: 'Argentina' },
  { prefix: '+374', country: 'Armenia' },
  { prefix: '+297', country: 'Aruba' },
  { prefix: '+247', country: 'Ascension' },
  { prefix: '+61', country: 'Australia' },
  { prefix: '+672', country: 'Australian External Territories' },
  { prefix: '+43', country: 'Austria' },
  { prefix: '+994', country: 'Azerbaijan' },
  { prefix: '+1 242', country: 'Bahamas' },
  { prefix: '+973', country: 'Bahrain' },
  { prefix: '+880', country: 'Bangladesh' },
  { prefix: '+1 246', country: 'Barbados' },
  { prefix: '+1 268', country: 'Barbuda' },
  { prefix: '+375', country: 'Belarus' },
  { prefix: '+32', country: 'Belgium' },
  { prefix: '+501', country: 'Belize' },
  { prefix: '+229', country: 'Benin' },
  { prefix: '+1 441', country: 'Bermuda' },
  { prefix: '+975', country: 'Bhutan' },
  { prefix: '+591', country: 'Bolivia' },
  { prefix: '+387', country: 'Bosnia and Herzegovina' },
  { prefix: '+267', country: 'Botswana' },
  { prefix: '+55', country: 'Brazil' },
  { prefix: '+246', country: 'British Indian Ocean Territory' },
  { prefix: '+1 284', country: 'British Virgin Islands' },
  { prefix: '+673', country: 'Brunei' },
  { prefix: '+359', country: 'Bulgaria' },
  { prefix: '+226', country: 'Burkina Faso' },
  { prefix: '+257', country: 'Burundi' },
  { prefix: '+855', country: 'Cambodia' },
  { prefix: '+237', country: 'Cameroon' },
  { prefix: '+1', country: 'Canada' },
  { prefix: '+238', country: 'Cape Verde' },
  { prefix: '+ 345', country: 'Cayman Islands' },
  { prefix: '+236', country: 'Central African Republic' },
  { prefix: '+235', country: 'Chad' },
  { prefix: '+56', country: 'Chile' },
  { prefix: '+86', country: 'China' },
  { prefix: '+61', country: 'Christmas Island' },
  { prefix: '+61', country: 'Cocos-Keeling Islands' },
  { prefix: '+57', country: 'Colombia' },
  { prefix: '+269', country: 'Comoros' },
  { prefix: '+242', country: 'Congo' },
  { prefix: '+243', country: 'Congo, Dem. Rep. of (Zaire)' },
  { prefix: '+682', country: 'Cook Islands' },
  { prefix: '+506', country: 'Costa Rica' },
  { prefix: '+385', country: 'Croatia' },
  { prefix: '+53', country: 'Cuba' },
  { prefix: '+599', country: 'Curacao' },
  { prefix: '+537', country: 'Cyprus' },
  { prefix: '+420', country: 'Czech Republic' },
  { prefix: '+45', country: 'Denmark' },
  { prefix: '+246', country: 'Diego Garcia' },
  { prefix: '+253', country: 'Djibouti' },
  { prefix: '+1 767', country: 'Dominica' },
  { prefix: '+1 809', country: 'Dominican Republic' },
  { prefix: '+1 829', country: 'Dominican Republic' },
  { prefix: '+1 849', country: 'Dominican Republic' },
  { prefix: '+670', country: 'East Timor' },
  { prefix: '+56', country: 'Easter Island' },
  { prefix: '+593', country: 'Ecuador' },
  { prefix: '+20', country: 'Egypt' },
  { prefix: '+503', country: 'El Salvador' },
  { prefix: '+240', country: 'Equatorial Guinea' },
  { prefix: '+291', country: 'Eritrea' },
  { prefix: '+372', country: 'Estonia' },
  { prefix: '+251', country: 'Ethiopia' },
  { prefix: '+500', country: 'Falkland Islands' },
  { prefix: '+298', country: 'Faroe Islands' },
  { prefix: '+679', country: 'Fiji' },
  { prefix: '+358', country: 'Finland' },
  { prefix: '+33', country: 'France' },
  { prefix: '+596', country: 'French Antilles' },
  { prefix: '+594', country: 'French Guiana' },
  { prefix: '+689', country: 'French Polynesia' },
  { prefix: '+241', country: 'Gabon' },
  { prefix: '+220', country: 'Gambia' },
  { prefix: '+995', country: 'Georgia' },
  { prefix: '+49', country: 'Germany' },
  { prefix: '+233', country: 'Ghana' },
  { prefix: '+350', country: 'Gibraltar' },
  { prefix: '+30', country: 'Greece' },
  { prefix: '+299', country: 'Greenland' },
  { prefix: '+1 473', country: 'Grenada' },
  { prefix: '+590', country: 'Guadeloupe' },
  { prefix: '+1 671', country: 'Guam' },
  { prefix: '+502', country: 'Guatemala' },
  { prefix: '+224', country: 'Guinea' },
  { prefix: '+245', country: 'Guinea-Bissau' },
  { prefix: '+595', country: 'Guyana' },
  { prefix: '+509', country: 'Haiti' },
  { prefix: '+504', country: 'Honduras' },
  { prefix: '+852', country: 'Hong Kong SAR China' },
  { prefix: '+36', country: 'Hungary' },
  { prefix: '+354', country: 'Iceland' },
  { prefix: '+91', country: 'India' },
  { prefix: '+62', country: 'Indonesia' },
  { prefix: '+98', country: 'Iran' },
  { prefix: '+964', country: 'Iraq' },
  { prefix: '+353', country: 'Ireland' },
  { prefix: '+972', country: 'Israel' },
  { prefix: '+39', country: 'Italy' },
  { prefix: '+225', country: 'Ivory Coast' },
  { prefix: '+1 876', country: 'Jamaica' },
  { prefix: '+81', country: 'Japan' },
  { prefix: '+962', country: 'Jordan' },
  { prefix: '+7 7', country: 'Kazakhstan' },
  { prefix: '+254', country: 'Kenya' },
  { prefix: '+686', country: 'Kiribati' },
  { prefix: '+965', country: 'Kuwait' },
  { prefix: '+996', country: 'Kyrgyzstan' },
  { prefix: '+856', country: 'Laos' },
  { prefix: '+371', country: 'Latvia' },
  { prefix: '+961', country: 'Lebanon' },
  { prefix: '+266', country: 'Lesotho' },
  { prefix: '+231', country: 'Liberia' },
  { prefix: '+218', country: 'Libya' },
  { prefix: '+423', country: 'Liechtenstein' },
  { prefix: '+370', country: 'Lithuania' },
  { prefix: '+352', country: 'Luxembourg' },
  { prefix: '+853', country: 'Macau SAR China' },
  { prefix: '+389', country: 'Macedonia' },
  { prefix: '+261', country: 'Madagascar' },
  { prefix: '+265', country: 'Malawi' },
  { prefix: '+60', country: 'Malaysia' },
  { prefix: '+960', country: 'Maldives' },
  { prefix: '+223', country: 'Mali' },
  { prefix: '+356', country: 'Malta' },
  { prefix: '+692', country: 'Marshall Islands' },
  { prefix: '+596', country: 'Martinique' },
  { prefix: '+222', country: 'Mauritania' },
  { prefix: '+230', country: 'Mauritius' },
  { prefix: '+262', country: 'Mayotte' },
  { prefix: '+52', country: 'Mexico' },
  { prefix: '+691', country: 'Micronesia' },
  { prefix: '+1 808', country: 'Midway Island' },
  { prefix: '+373', country: 'Moldova' },
  { prefix: '+377', country: 'Monaco' },
  { prefix: '+976', country: 'Mongolia' },
  { prefix: '+382', country: 'Montenegro' },
  { prefix: '+1664', country: 'Montserrat' },
  { prefix: '+212', country: 'Morocco' },
  { prefix: '+95', country: 'Myanmar' },
  { prefix: '+264', country: 'Namibia' },
  { prefix: '+674', country: 'Nauru' },
  { prefix: '+977', country: 'Nepal' },
  { prefix: '+31', country: 'Netherlands' },
  { prefix: '+599', country: 'Netherlands Antilles' },
  { prefix: '+1 869', country: 'Nevis' },
  { prefix: '+687', country: 'New Caledonia' },
  { prefix: '+64', country: 'New Zealand' },
  { prefix: '+505', country: 'Nicaragua' },
  { prefix: '+227', country: 'Niger' },
  { prefix: '+234', country: 'Nigeria' },
  { prefix: '+683', country: 'Niue' },
  { prefix: '+672', country: 'Norfolk Island' },
  { prefix: '+850', country: 'North Korea' },
  { prefix: '+1 670', country: 'Northern Mariana Islands' },
  { prefix: '+47', country: 'Norway' },
  { prefix: '+968', country: 'Oman' },
  { prefix: '+92', country: 'Pakistan' },
  { prefix: '+680', country: 'Palau' },
  { prefix: '+970', country: 'Palestinian Territory' },
  { prefix: '+507', country: 'Panama' },
  { prefix: '+675', country: 'Papua New Guinea' },
  { prefix: '+595', country: 'Paraguay' },
  { prefix: '+51', country: 'Peru' },
  { prefix: '+63', country: 'Philippines' },
  { prefix: '+48', country: 'Poland' },
  { prefix: '+351', country: 'Portugal' },
  { prefix: '+1 787', country: 'Puerto Rico' },
  { prefix: '+1 939', country: 'Puerto Rico' },
  { prefix: '+974', country: 'Qatar' },
  { prefix: '+262', country: 'Reunion' },
  { prefix: '+40', country: 'Romania' },
  { prefix: '+7', country: 'Russia' },
  { prefix: '+250', country: 'Rwanda' },
  { prefix: '+685', country: 'Samoa' },
  { prefix: '+378', country: 'San Marino' },
  { prefix: '+966', country: 'Saudi Arabia' },
  { prefix: '+221', country: 'Senegal' },
  { prefix: '+381', country: 'Serbia' },
  { prefix: '+248', country: 'Seychelles' },
  { prefix: '+232', country: 'Sierra Leone' },
  { prefix: '+65', country: 'Singapore' },
  { prefix: '+421', country: 'Slovakia' },
  { prefix: '+386', country: 'Slovenia' },
  { prefix: '+677', country: 'Solomon Islands' },
  { prefix: '+27', country: 'South Africa' },
  { prefix: '+500', country: 'South Georgia and the South Sandwich Islands' },
  { prefix: '+82', country: 'South Korea' },
  { prefix: '+34', country: 'Spain' },
  { prefix: '+94', country: 'Sri Lanka' },
  { prefix: '+249', country: 'Sudan' },
  { prefix: '+597', country: 'Suriname' },
  { prefix: '+268', country: 'Swaziland' },
  { prefix: '+46', country: 'Sweden' },
  { prefix: '+41', country: 'Switzerland' },
  { prefix: '+963', country: 'Syria' },
  { prefix: '+886', country: 'Taiwan' },
  { prefix: '+992', country: 'Tajikistan' },
  { prefix: '+255', country: 'Tanzania' },
  { prefix: '+66', country: 'Thailand' },
  { prefix: '+670', country: 'Timor Leste' },
  { prefix: '+228', country: 'Togo' },
  { prefix: '+690', country: 'Tokelau' },
  { prefix: '+676', country: 'Tonga' },
  { prefix: '+1 868', country: 'Trinidad and Tobago' },
  { prefix: '+216', country: 'Tunisia' },
  { prefix: '+90', country: 'Turkey' },
  { prefix: '+993', country: 'Turkmenistan' },
  { prefix: '+1 649', country: 'Turks and Caicos Islands' },
  { prefix: '+688', country: 'Tuvalu' },
  { prefix: '+1 340', country: 'U.S. Virgin Islands' },
  { prefix: '+256', country: 'Uganda' },
  { prefix: '+380', country: 'Ukraine' },
  { prefix: '+971', country: 'United Arab Emirates' },
  { prefix: '+44', country: 'United Kingdom' },
  { prefix: '+1', country: 'United States' },
  { prefix: '+598', country: 'Uruguay' },
  { prefix: '+998', country: 'Uzbekistan' },
  { prefix: '+678', country: 'Vanuatu' },
  { prefix: '+58', country: 'Venezuela' },
  { prefix: '+84', country: 'Vietnam' },
  { prefix: '+1 808', country: 'Wake Island' },
  { prefix: '+681', country: 'Wallis and Futuna' },
  { prefix: '+967', country: 'Yemen' },
  { prefix: '+260', country: 'Zambia' },
  { prefix: '+255', country: 'Zanzibar' },
  { prefix: '+263', country: 'Zimbabwe' },
];

const PHONE_PREFIXES_ES: Array<PhonePrefix> = [
  { prefix: '+7 840', country: 'Abjasia' },
  { prefix: '+7 940', country: 'Abjasia' },
  { prefix: '+93', country: 'Afganistán' },
  { prefix: '+355', country: 'Albania' },
  { prefix: '+49', country: 'Alemania' },
  { prefix: '+376', country: 'Andorra' },
  { prefix: '+244', country: 'Angola' },
  { prefix: '+1 264', country: 'Anguila' },
  { prefix: '+1 268', country: 'Antigua y Barbuda' },
  { prefix: '+1 268', country: 'Antigua y Barbuda' },
  { prefix: '+596', country: 'Antillas francesas' },
  { prefix: '+966', country: 'Arabia Saudí' },
  { prefix: '+213', country: 'Argelia' },
  { prefix: '+54', country: 'Argentina' },
  { prefix: '+374', country: 'Armenia' },
  { prefix: '+297', country: 'Aruba' },
  { prefix: '+61', country: 'Australia' },
  { prefix: '+43', country: 'Austria' },
  { prefix: '+994', country: 'Azerbaiyán' },
  { prefix: '+1 242', country: 'Bahamas' },
  { prefix: '+880', country: 'Bangladés' },
  { prefix: '+1 246', country: 'Barbados' },
  { prefix: '+973', country: 'Baréin' },
  { prefix: '+501', country: 'Belice' },
  { prefix: '+229', country: 'Benín' },
  { prefix: '+1 441', country: 'Bermudas' },
  { prefix: '+375', country: 'Bielorrusia' },
  { prefix: '+591', country: 'Bolivia' },
  { prefix: '+387', country: 'Bosnia y Herzegovina' },
  { prefix: '+267', country: 'Botsuana' },
  { prefix: '+55', country: 'Brasil' },
  { prefix: '+673', country: 'Brunéi' },
  { prefix: '+359', country: 'Bulgaria' },
  { prefix: '+226', country: 'Burkina Faso' },
  { prefix: '+257', country: 'Burundi' },
  { prefix: '+975', country: 'Bután' },
  { prefix: '+32', country: 'Bélgica' },
  { prefix: '+238', country: 'Cabo Verde' },
  { prefix: '+855', country: 'Camboya' },
  { prefix: '+237', country: 'Camerún' },
  { prefix: '+1', country: 'Canadá' },
  { prefix: '+974', country: 'Catar' },
  { prefix: '+235', country: 'Chad' },
  { prefix: '+420', country: 'Chequia' },
  { prefix: '+56', country: 'Chile' },
  { prefix: '+86', country: 'China' },
  { prefix: '+537', country: 'Chipre' },
  { prefix: '+57', country: 'Colombia' },
  { prefix: '+269', country: 'Comoras' },
  { prefix: '+242', country: 'Congo' },
  { prefix: '+850', country: 'Corea del Norte' },
  { prefix: '+82', country: 'Corea del Sur' },
  { prefix: '+506', country: 'Costa Rica' },
  { prefix: '+385', country: 'Croacia' },
  { prefix: '+53', country: 'Cuba' },
  { prefix: '+599', country: 'Curazao' },
  { prefix: '+599', country: 'Curazao' },
  { prefix: '+225', country: 'Côte d’Ivoire' },
  { prefix: '+246', country: 'Diego García' },
  { prefix: '+45', country: 'Dinamarca' },
  { prefix: '+1 767', country: 'Dominica' },
  { prefix: '+593', country: 'Ecuador' },
  { prefix: '+20', country: 'Egipto' },
  { prefix: '+503', country: 'El Salvador' },
  { prefix: '+971', country: 'Emiratos Árabes Unidos' },
  { prefix: '+291', country: 'Eritrea' },
  { prefix: '+421', country: 'Eslovaquia' },
  { prefix: '+386', country: 'Eslovenia' },
  { prefix: '+34', country: 'España' },
  { prefix: '+1', country: 'Estados Unidos' },
  { prefix: '+372', country: 'Estonia' },
  { prefix: '+268', country: 'Esuatini' },
  { prefix: '+251', country: 'Etiopía' },
  { prefix: '+63', country: 'Filipinas' },
  { prefix: '+358', country: 'Finlandia' },
  { prefix: '+679', country: 'Fiyi' },
  { prefix: '+33', country: 'Francia' },
  { prefix: '+241', country: 'Gabón' },
  { prefix: '+220', country: 'Gambia' },
  { prefix: '+995', country: 'Georgia' },
  { prefix: '+233', country: 'Ghana' },
  { prefix: '+350', country: 'Gibraltar' },
  { prefix: '+1 473', country: 'Granada' },
  { prefix: '+30', country: 'Grecia' },
  { prefix: '+299', country: 'Groenlandia' },
  { prefix: '+590', country: 'Guadalupe' },
  { prefix: '+1 671', country: 'Guam' },
  { prefix: '+502', country: 'Guatemala' },
  { prefix: '+594', country: 'Guayana Francesa' },
  { prefix: '+224', country: 'Guinea' },
  { prefix: '+240', country: 'Guinea Ecuatorial' },
  { prefix: '+245', country: 'Guinea-Bisáu' },
  { prefix: '+595', country: 'Guyana' },
  { prefix: '+509', country: 'Haití' },
  { prefix: '+504', country: 'Honduras' },
  { prefix: '+852', country: 'Hong Kong' },
  { prefix: '+36', country: 'Hungría' },
  { prefix: '+91', country: 'India' },
  { prefix: '+62', country: 'Indonesia' },
  { prefix: '+964', country: 'Irak' },
  { prefix: '+353', country: 'Irlanda' },
  { prefix: '+98', country: 'Irán' },
  { prefix: '+672', country: 'Isla Norfolk' },
  { prefix: '+1 808', country: 'Isla Wake' },
  { prefix: '+61', country: 'Isla de Navidad' },
  { prefix: '+56', country: 'Isla de Pascua' },
  { prefix: '+247', country: 'Isla de la Ascensión' },
  { prefix: '+672', country: 'Isla de la Ascensión' },
  { prefix: '+354', country: 'Islandia' },
  { prefix: '+ 345', country: 'Islas Caimán' },
  { prefix: '+61', country: 'Islas Cocos' },
  { prefix: '+682', country: 'Islas Cook' },
  { prefix: '+298', country: 'Islas Feroe' },
  { prefix: '+500', country: 'Islas Georgia del Sur y Sandwich del Sur' },
  { prefix: '+500', country: 'Islas Malvinas (Islas Falkland)' },
  { prefix: '+1 670', country: 'Islas Marianas del Norte' },
  { prefix: '+692', country: 'Islas Marshall' },
  { prefix: '+1 808', country: 'Islas Midway' },
  { prefix: '+677', country: 'Islas Salomón' },
  { prefix: '+1 649', country: 'Islas Turcas y Caicos' },
  { prefix: '+1 284', country: 'Islas Vírgenes Británicas' },
  { prefix: '+1 340', country: 'Islas Vírgenes de EE. UU.' },
  { prefix: '+972', country: 'Israel' },
  { prefix: '+39', country: 'Italia' },
  { prefix: '+1 876', country: 'Jamaica' },
  { prefix: '+81', country: 'Japón' },
  { prefix: '+962', country: 'Jordania' },
  { prefix: '+7 7', country: 'Kazajistán' },
  { prefix: '+254', country: 'Kenia' },
  { prefix: '+996', country: 'Kirguistán' },
  { prefix: '+686', country: 'Kiribati' },
  { prefix: '+965', country: 'Kuwait' },
  { prefix: '+856', country: 'Laos' },
  { prefix: '+266', country: 'Lesoto' },
  { prefix: '+371', country: 'Letonia' },
  { prefix: '+231', country: 'Liberia' },
  { prefix: '+218', country: 'Libia' },
  { prefix: '+423', country: 'Liechtenstein' },
  { prefix: '+370', country: 'Lituania' },
  { prefix: '+352', country: 'Luxemburgo' },
  { prefix: '+961', country: 'Líbano' },
  { prefix: '+853', country: 'Macao' },
  { prefix: '+389', country: 'Macedonia del Norte' },
  { prefix: '+261', country: 'Madagascar' },
  { prefix: '+60', country: 'Malasia' },
  { prefix: '+265', country: 'Malaui' },
  { prefix: '+960', country: 'Maldivas' },
  { prefix: '+223', country: 'Mali' },
  { prefix: '+356', country: 'Malta' },
  { prefix: '+212', country: 'Marruecos' },
  { prefix: '+596', country: 'Martinica' },
  { prefix: '+230', country: 'Mauricio' },
  { prefix: '+222', country: 'Mauritania' },
  { prefix: '+262', country: 'Mayotte' },
  { prefix: '+691', country: 'Micronesia' },
  { prefix: '+373', country: 'Moldavia' },
  { prefix: '+976', country: 'Mongolia' },
  { prefix: '+382', country: 'Montenegro' },
  { prefix: '+1664', country: 'Montserrat' },
  { prefix: '+95', country: 'Myanmar (Birmania)' },
  { prefix: '+52', country: 'México' },
  { prefix: '+377', country: 'Mónaco' },
  { prefix: '+264', country: 'Namibia' },
  { prefix: '+674', country: 'Nauru' },
  { prefix: '+977', country: 'Nepal' },
  { prefix: '+505', country: 'Nicaragua' },
  { prefix: '+234', country: 'Nigeria' },
  { prefix: '+683', country: 'Niue' },
  { prefix: '+47', country: 'Noruega' },
  { prefix: '+687', country: 'Nueva Caledonia' },
  { prefix: '+64', country: 'Nueva Zelanda' },
  { prefix: '+227', country: 'Níger' },
  { prefix: '+968', country: 'Omán' },
  { prefix: '+92', country: 'Pakistán' },
  { prefix: '+680', country: 'Palaos' },
  { prefix: '+970', country: 'Palestina' },
  { prefix: '+507', country: 'Panamá' },
  { prefix: '+675', country: 'Papúa Nueva Guinea' },
  { prefix: '+595', country: 'Paraguay' },
  { prefix: '+31', country: 'Países Bajos' },
  { prefix: '+51', country: 'Perú' },
  { prefix: '+689', country: 'Polinesia Francesa' },
  { prefix: '+48', country: 'Polonia' },
  { prefix: '+351', country: 'Portugal' },
  { prefix: '+1 787', country: 'Puerto Rico' },
  { prefix: '+1 939', country: 'Puerto Rico' },
  { prefix: '+44', country: 'Reino Unido' },
  { prefix: '+236', country: 'República Centroafricana' },
  { prefix: '+243', country: 'República Democrática del Congo' },
  { prefix: '+1 809', country: 'República Dominicana' },
  { prefix: '+1 829', country: 'República Dominicana' },
  { prefix: '+1 849', country: 'República Dominicana' },
  { prefix: '+262', country: 'Reunión' },
  { prefix: '+250', country: 'Ruanda' },
  { prefix: '+40', country: 'Rumanía' },
  { prefix: '+7', country: 'Rusia' },
  { prefix: '+685', country: 'Samoa' },
  { prefix: '+1 684', country: 'Samoa Americana' },
  { prefix: '+1 869', country: 'San Cristóbal y Nieves' },
  { prefix: '+378', country: 'San Marino' },
  { prefix: '+221', country: 'Senegal' },
  { prefix: '+381', country: 'Serbia' },
  { prefix: '+248', country: 'Seychelles' },
  { prefix: '+232', country: 'Sierra Leona' },
  { prefix: '+65', country: 'Singapur' },
  { prefix: '+963', country: 'Siria' },
  { prefix: '+94', country: 'Sri Lanka' },
  { prefix: '+27', country: 'Sudáfrica' },
  { prefix: '+249', country: 'Sudán' },
  { prefix: '+46', country: 'Suecia' },
  { prefix: '+41', country: 'Suiza' },
  { prefix: '+597', country: 'Surinam' },
  { prefix: '+66', country: 'Tailandia' },
  { prefix: '+886', country: 'Taiwán' },
  { prefix: '+255', country: 'Tanzania' },
  { prefix: '+992', country: 'Tayikistán' },
  { prefix: '+246', country: 'Territorio Británico del Océano Índico' },
  { prefix: '+670', country: 'Timor-Leste' },
  { prefix: '+670', country: 'Timor-Leste' },
  { prefix: '+228', country: 'Togo' },
  { prefix: '+690', country: 'Tokelau' },
  { prefix: '+676', country: 'Tonga' },
  { prefix: '+1 868', country: 'Trinidad y Tobago' },
  { prefix: '+993', country: 'Turkmenistán' },
  { prefix: '+90', country: 'Turquía' },
  { prefix: '+688', country: 'Tuvalu' },
  { prefix: '+216', country: 'Túnez' },
  { prefix: '+380', country: 'Ucrania' },
  { prefix: '+256', country: 'Uganda' },
  { prefix: '+598', country: 'Uruguay' },
  { prefix: '+998', country: 'Uzbekistán' },
  { prefix: '+678', country: 'Vanuatu' },
  { prefix: '+58', country: 'Venezuela' },
  { prefix: '+84', country: 'Vietnam' },
  { prefix: '+681', country: 'Wallis y Futuna' },
  { prefix: '+967', country: 'Yemen' },
  { prefix: '+253', country: 'Yibuti' },
  { prefix: '+260', country: 'Zambia' },
  { prefix: '+255', country: 'Zanzíbar' },
  { prefix: '+263', country: 'Zimbabue' },
];

const PHONE_PREFIXES_IT: Array<PhonePrefix> = [
  { prefix: '+7 840', country: 'Abkhazia' },
  { prefix: '+7 940', country: 'Abkhazia' },
  { prefix: '+93', country: 'Afghanistan' },
  { prefix: '+355', country: 'Albania' },
  { prefix: '+213', country: 'Algeria' },
  { prefix: '+376', country: 'Andorra' },
  { prefix: '+244', country: 'Angola' },
  { prefix: '+1 264', country: 'Anguilla' },
  { prefix: '+1 268', country: 'Antigua e Barbuda' },
  { prefix: '+1 268', country: 'Antigua e Barbuda' },
  { prefix: '+596', country: 'Antille francesi' },
  { prefix: '+966', country: 'Arabia Saudita' },
  { prefix: '+54', country: 'Argentina' },
  { prefix: '+374', country: 'Armenia' },
  { prefix: '+297', country: 'Aruba' },
  { prefix: '+1 808', country: 'Atollo di Midway' },
  { prefix: '+61', country: 'Australia' },
  { prefix: '+43', country: 'Austria' },
  { prefix: '+994', country: 'Azerbaigian' },
  { prefix: '+1 242', country: 'Bahamas' },
  { prefix: '+973', country: 'Bahrein' },
  { prefix: '+880', country: 'Bangladesh' },
  { prefix: '+1 246', country: 'Barbados' },
  { prefix: '+32', country: 'Belgio' },
  { prefix: '+501', country: 'Belize' },
  { prefix: '+229', country: 'Benin' },
  { prefix: '+1 441', country: 'Bermuda' },
  { prefix: '+975', country: 'Bhutan' },
  { prefix: '+375', country: 'Bielorussia' },
  { prefix: '+591', country: 'Bolivia' },
  { prefix: '+387', country: 'Bosnia ed Erzegovina' },
  { prefix: '+267', country: 'Botswana' },
  { prefix: '+55', country: 'Brasile' },
  { prefix: '+673', country: 'Brunei' },
  { prefix: '+359', country: 'Bulgaria' },
  { prefix: '+226', country: 'Burkina Faso' },
  { prefix: '+257', country: 'Burundi' },
  { prefix: '+855', country: 'Cambogia' },
  { prefix: '+237', country: 'Camerun' },
  { prefix: '+1', country: 'Canada' },
  { prefix: '+238', country: 'Capo Verde' },
  { prefix: '+420', country: 'Cechia' },
  { prefix: '+235', country: 'Ciad' },
  { prefix: '+56', country: 'Cile' },
  { prefix: '+86', country: 'Cina' },
  { prefix: '+537', country: 'Cipro' },
  { prefix: '+57', country: 'Colombia' },
  { prefix: '+269', country: 'Comore' },
  { prefix: '+243', country: 'Congo - Kinshasa' },
  { prefix: '+242', country: 'Congo-Brazzaville' },
  { prefix: '+850', country: 'Corea del Nord' },
  { prefix: '+82', country: 'Corea del Sud' },
  { prefix: '+506', country: 'Costa Rica' },
  { prefix: '+225', country: 'Costa d’Avorio' },
  { prefix: '+385', country: 'Croazia' },
  { prefix: '+53', country: 'Cuba' },
  { prefix: '+599', country: 'Curaçao' },
  { prefix: '+599', country: 'Curaçao' },
  { prefix: '+45', country: 'Danimarca' },
  { prefix: '+246', country: 'Diego Garcia' },
  { prefix: '+1 767', country: 'Dominica' },
  { prefix: '+593', country: 'Ecuador' },
  { prefix: '+20', country: 'Egitto' },
  { prefix: '+503', country: 'El Salvador' },
  { prefix: '+971', country: 'Emirati Arabi Uniti' },
  { prefix: '+291', country: 'Eritrea' },
  { prefix: '+372', country: 'Estonia' },
  { prefix: '+251', country: 'Etiopia' },
  { prefix: '+679', country: 'Figi' },
  { prefix: '+63', country: 'Filippine' },
  { prefix: '+358', country: 'Finlandia' },
  { prefix: '+33', country: 'Francia' },
  { prefix: '+241', country: 'Gabon' },
  { prefix: '+220', country: 'Gambia' },
  { prefix: '+995', country: 'Georgia' },
  { prefix: '+500', country: 'Georgia del Sud e Sandwich australi' },
  { prefix: '+49', country: 'Germania' },
  { prefix: '+233', country: 'Ghana' },
  { prefix: '+1 876', country: 'Giamaica' },
  { prefix: '+81', country: 'Giappone' },
  { prefix: '+350', country: 'Gibilterra' },
  { prefix: '+253', country: 'Gibuti' },
  { prefix: '+962', country: 'Giordania' },
  { prefix: '+30', country: 'Grecia' },
  { prefix: '+1 473', country: 'Grenada' },
  { prefix: '+299', country: 'Groenlandia' },
  { prefix: '+590', country: 'Guadalupa' },
  { prefix: '+1 671', country: 'Guam' },
  { prefix: '+502', country: 'Guatemala' },
  { prefix: '+224', country: 'Guinea' },
  { prefix: '+240', country: 'Guinea Equatoriale' },
  { prefix: '+245', country: 'Guinea-Bissau' },
  { prefix: '+595', country: 'Guyana' },
  { prefix: '+594', country: 'Guyana francese' },
  { prefix: '+509', country: 'Haiti' },
  { prefix: '+504', country: 'Honduras' },
  { prefix: '+852', country: 'Hong Kong' },
  { prefix: '+91', country: 'India' },
  { prefix: '+62', country: 'Indonesia' },
  { prefix: '+98', country: 'Iran' },
  { prefix: '+964', country: 'Iraq' },
  { prefix: '+353', country: 'Irlanda' },
  { prefix: '+354', country: 'Islanda' },
  { prefix: '+247', country: 'Isola Ascensione' },
  { prefix: '+672', country: 'Isola Ascensione' },
  { prefix: '+61', country: 'Isola Christmas' },
  { prefix: '+672', country: 'Isola Norfolk' },
  { prefix: '+56', country: 'Isola di Pasqua' },
  { prefix: '+1 808', country: 'Isola di Wake' },
  { prefix: '+ 345', country: 'Isole Cayman' },
  { prefix: '+61', country: 'Isole Cocos (Keeling)' },
  { prefix: '+682', country: 'Isole Cook' },
  { prefix: '+500', country: 'Isole Falkland (Isole Malvine)' },
  { prefix: '+298', country: 'Isole Fær Øer' },
  { prefix: '+1 670', country: 'Isole Marianne settentrionali' },
  { prefix: '+692', country: 'Isole Marshall' },
  { prefix: '+677', country: 'Isole Salomone' },
  { prefix: '+1 649', country: 'Isole Turks e Caicos' },
  { prefix: '+1 340', country: 'Isole Vergini Americane' },
  { prefix: '+1 284', country: 'Isole Vergini Britanniche' },
  { prefix: '+972', country: 'Israele' },
  { prefix: '+39', country: 'Italia' },
  { prefix: '+7 7', country: 'Kazakistan' },
  { prefix: '+254', country: 'Kenya' },
  { prefix: '+996', country: 'Kirghizistan' },
  { prefix: '+686', country: 'Kiribati' },
  { prefix: '+965', country: 'Kuwait' },
  { prefix: '+856', country: 'Laos' },
  { prefix: '+266', country: 'Lesotho' },
  { prefix: '+371', country: 'Lettonia' },
  { prefix: '+961', country: 'Libano' },
  { prefix: '+231', country: 'Liberia' },
  { prefix: '+218', country: 'Libia' },
  { prefix: '+423', country: 'Liechtenstein' },
  { prefix: '+370', country: 'Lituania' },
  { prefix: '+352', country: 'Lussemburgo' },
  { prefix: '+853', country: 'Macao' },
  { prefix: '+389', country: 'Macedonia del Nord' },
  { prefix: '+261', country: 'Madagascar' },
  { prefix: '+265', country: 'Malawi' },
  { prefix: '+60', country: 'Malaysia' },
  { prefix: '+960', country: 'Maldive' },
  { prefix: '+223', country: 'Mali' },
  { prefix: '+356', country: 'Malta' },
  { prefix: '+212', country: 'Marocco' },
  { prefix: '+596', country: 'Martinica' },
  { prefix: '+222', country: 'Mauritania' },
  { prefix: '+230', country: 'Mauritius' },
  { prefix: '+262', country: 'Mayotte' },
  { prefix: '+52', country: 'Messico' },
  { prefix: '+691', country: 'Micronesia' },
  { prefix: '+373', country: 'Moldavia' },
  { prefix: '+377', country: 'Monaco' },
  { prefix: '+976', country: 'Mongolia' },
  { prefix: '+382', country: 'Montenegro' },
  { prefix: '+1664', country: 'Montserrat' },
  { prefix: '+95', country: 'Myanmar (Birmania)' },
  { prefix: '+264', country: 'Namibia' },
  { prefix: '+674', country: 'Nauru' },
  { prefix: '+977', country: 'Nepal' },
  { prefix: '+505', country: 'Nicaragua' },
  { prefix: '+227', country: 'Niger' },
  { prefix: '+234', country: 'Nigeria' },
  { prefix: '+683', country: 'Niue' },
  { prefix: '+47', country: 'Norvegia' },
  { prefix: '+687', country: 'Nuova Caledonia' },
  { prefix: '+64', country: 'Nuova Zelanda' },
  { prefix: '+968', country: 'Oman' },
  { prefix: '+31', country: 'Paesi Bassi' },
  { prefix: '+92', country: 'Pakistan' },
  { prefix: '+680', country: 'Palau' },
  { prefix: '+970', country: 'Palestina' },
  { prefix: '+507', country: 'Panamá' },
  { prefix: '+675', country: 'Papua Nuova Guinea' },
  { prefix: '+595', country: 'Paraguay' },
  { prefix: '+51', country: 'Perù' },
  { prefix: '+689', country: 'Polinesia francese' },
  { prefix: '+48', country: 'Polonia' },
  { prefix: '+351', country: 'Portogallo' },
  { prefix: '+1 787', country: 'Portorico' },
  { prefix: '+1 939', country: 'Portorico' },
  { prefix: '+974', country: 'Qatar' },
  { prefix: '+44', country: 'Regno Unito' },
  { prefix: '+236', country: 'Repubblica Centrafricana' },
  { prefix: '+1 809', country: 'Repubblica Dominicana' },
  { prefix: '+1 829', country: 'Repubblica Dominicana' },
  { prefix: '+1 849', country: 'Repubblica Dominicana' },
  { prefix: '+262', country: 'Riunione' },
  { prefix: '+40', country: 'Romania' },
  { prefix: '+250', country: 'Ruanda' },
  { prefix: '+7', country: 'Russia' },
  { prefix: '+1 869', country: 'Saint Kitts e Nevis' },
  { prefix: '+685', country: 'Samoa' },
  { prefix: '+1 684', country: 'Samoa americane' },
  { prefix: '+378', country: 'San Marino' },
  { prefix: '+221', country: 'Senegal' },
  { prefix: '+381', country: 'Serbia' },
  { prefix: '+248', country: 'Seychelles' },
  { prefix: '+232', country: 'Sierra Leone' },
  { prefix: '+65', country: 'Singapore' },
  { prefix: '+963', country: 'Siria' },
  { prefix: '+421', country: 'Slovacchia' },
  { prefix: '+386', country: 'Slovenia' },
  { prefix: '+34', country: 'Spagna' },
  { prefix: '+94', country: 'Sri Lanka' },
  { prefix: '+1', country: 'Stati Uniti' },
  { prefix: '+27', country: 'Sudafrica' },
  { prefix: '+249', country: 'Sudan' },
  { prefix: '+597', country: 'Suriname' },
  { prefix: '+46', country: 'Svezia' },
  { prefix: '+41', country: 'Svizzera' },
  { prefix: '+268', country: 'Swaziland' },
  { prefix: '+992', country: 'Tagikistan' },
  { prefix: '+886', country: 'Taiwan' },
  { prefix: '+255', country: 'Tanzania' },
  { prefix: '+246', country: 'Territorio britannico dell’Oceano Indiano' },
  { prefix: '+66', country: 'Thailandia' },
  { prefix: '+670', country: 'Timor Est' },
  { prefix: '+670', country: 'Timor Est' },
  { prefix: '+228', country: 'Togo' },
  { prefix: '+690', country: 'Tokelau' },
  { prefix: '+676', country: 'Tonga' },
  { prefix: '+1 868', country: 'Trinidad e Tobago' },
  { prefix: '+216', country: 'Tunisia' },
  { prefix: '+90', country: 'Turchia' },
  { prefix: '+993', country: 'Turkmenistan' },
  { prefix: '+688', country: 'Tuvalu' },
  { prefix: '+380', country: 'Ucraina' },
  { prefix: '+256', country: 'Uganda' },
  { prefix: '+36', country: 'Ungheria' },
  { prefix: '+598', country: 'Uruguay' },
  { prefix: '+998', country: 'Uzbekistan' },
  { prefix: '+678', country: 'Vanuatu' },
  { prefix: '+58', country: 'Venezuela' },
  { prefix: '+84', country: 'Vietnam' },
  { prefix: '+681', country: 'Wallis e Futuna' },
  { prefix: '+967', country: 'Yemen' },
  { prefix: '+260', country: 'Zambia' },
  { prefix: '+255', country: 'Zanzibar' },
  { prefix: '+263', country: 'Zimbabwe' },
];

export const PHONE_PREFIXES: Record<APP_LOCALE, Array<PhonePrefix>> = {
  es: PHONE_PREFIXES_ES,
  en: PHONE_PREFIXES_EN,
  it: PHONE_PREFIXES_IT,
};
