export const PHONE_PREFIXES = [
  { prefix: '+7 840', country: 'Abkhazia', country_code: 'AB' },
  { prefix: '+7 940', country: 'Abkhazia', country_code: 'AB' },
  { prefix: '+93', country: 'Afghanistan', country_code: 'AF' },
  { prefix: '+355', country: 'Albania', country_code: 'AL' },
  { prefix: '+213', country: 'Algeria', country_code: 'DZ' },
  { prefix: '+1 684', country: 'American Samoa', country_code: 'AS' },
  { prefix: '+376', country: 'Andorra', country_code: 'AD' },
  { prefix: '+244', country: 'Angola', country_code: 'AO' },
  { prefix: '+1 264', country: 'Anguilla', country_code: 'AI' },
  { prefix: '+1 268', country: 'Antigua and Barbuda', country_code: 'AG' },
  { prefix: '+54', country: 'Argentina', country_code: 'AR' },
  { prefix: '+374', country: 'Armenia', country_code: 'AM' },
  { prefix: '+297', country: 'Aruba', country_code: 'AW' },
  { prefix: '+247', country: 'Ascension', country_code: 'AC' },
  { prefix: '+61', country: 'Australia', country_code: 'AU' },
  { prefix: '+672', country: 'Australian External Territories', country_code: 'AC' },
  { prefix: '+43', country: 'Austria', country_code: 'AT' },
  { prefix: '+994', country: 'Azerbaijan', country_code: 'AZ' },
  { prefix: '+1 242', country: 'Bahamas', country_code: 'BS' },
  { prefix: '+973', country: 'Bahrain', country_code: 'BH' },
  { prefix: '+880', country: 'Bangladesh', country_code: 'BD' },
  { prefix: '+1 246', country: 'Barbados', country_code: 'BB' },
  { prefix: '+1 268', country: 'Barbuda', country_code: 'AG' },
  { prefix: '+375', country: 'Belarus', country_code: 'BY' },
  { prefix: '+32', country: 'Belgium', country_code: 'BE' },
  { prefix: '+501', country: 'Belize', country_code: 'BZ' },
  { prefix: '+229', country: 'Benin', country_code: 'BJ' },
  { prefix: '+1 441', country: 'Bermuda', country_code: 'BM' },
  { prefix: '+975', country: 'Bhutan', country_code: 'BT' },
  { prefix: '+591', country: 'Bolivia', country_code: 'BO' },
  { prefix: '+387', country: 'Bosnia and Herzegovina', country_code: 'BA' },
  { prefix: '+267', country: 'Botswana', country_code: 'BW' },
  { prefix: '+55', country: 'Brazil', country_code: 'BR' },
  { prefix: '+246', country: 'British Indian Ocean Territory', country_code: 'IO' },
  { prefix: '+1 284', country: 'British Virgin Islands', country_code: 'VG' },
  { prefix: '+673', country: 'Brunei', country_code: 'BN' },
  { prefix: '+359', country: 'Bulgaria', country_code: 'BG' },
  { prefix: '+226', country: 'Burkina Faso', country_code: 'BF' },
  { prefix: '+257', country: 'Burundi', country_code: 'BI' },
  { prefix: '+855', country: 'Cambodia', country_code: 'KH' },
  { prefix: '+237', country: 'Cameroon', country_code: 'CM' },
  { prefix: '+1', country: 'Canada', country_code: 'CA' },
  { prefix: '+238', country: 'Cape Verde', country_code: 'CV' },
  { prefix: '+ 345', country: 'Cayman Islands', country_code: 'KY' },
  { prefix: '+236', country: 'Central African Republic', country_code: 'CF' },
  { prefix: '+235', country: 'Chad', country_code: 'TD' },
  { prefix: '+56', country: 'Chile', country_code: 'CL' },
  { prefix: '+86', country: 'China', country_code: 'CN' },
  { prefix: '+61', country: 'Christmas Island', country_code: 'CX' },
  { prefix: '+61', country: 'Cocos-Keeling Islands', country_code: 'CC' },
  { prefix: '+57', country: 'Colombia', country_code: 'CO' },
  { prefix: '+269', country: 'Comoros', country_code: 'KM' },
  { prefix: '+242', country: 'Congo', country_code: 'CG' },
  { prefix: '+243', country: 'Congo, Dem. Rep. of (Zaire)', country_code: 'CD' },
  { prefix: '+682', country: 'Cook Islands', country_code: 'CK' },
  { prefix: '+506', country: 'Costa Rica', country_code: 'CR' },
  { prefix: '+385', country: 'Croatia', country_code: 'HR' },
  { prefix: '+53', country: 'Cuba', country_code: 'CU' },
  { prefix: '+599', country: 'Curacao', country_code: 'CW' },
  { prefix: '+537', country: 'Cyprus', country_code: 'CY' },
  { prefix: '+420', country: 'Czech Republic', country_code: 'CZ' },
  { prefix: '+45', country: 'Denmark', country_code: 'DK' },
  { prefix: '+246', country: 'Diego Garcia', country_code: 'DG' },
  { prefix: '+253', country: 'Djibouti', country_code: 'DJ' },
  { prefix: '+1 767', country: 'Dominica', country_code: 'DM' },
  { prefix: '+1 809', country: 'Dominican Republic', country_code: 'DO' },
  { prefix: '+1 829', country: 'Dominican Republic', country_code: 'DO' },
  { prefix: '+1 849', country: 'Dominican Republic', country_code: 'DO' },
  { prefix: '+670', country: 'East Timor', country_code: 'TP' },
  { prefix: '+56', country: 'Easter Island', country_code: 'EI' },
  { prefix: '+593', country: 'Ecuador', country_code: 'EC' },
  { prefix: '+20', country: 'Egypt', country_code: 'EG' },
  { prefix: '+503', country: 'El Salvador', country_code: 'SV' },
  { prefix: '+240', country: 'Equatorial Guinea', country_code: 'GQ' },
  { prefix: '+291', country: 'Eritrea', country_code: 'ER' },
  { prefix: '+372', country: 'Estonia', country_code: 'EE' },
  { prefix: '+251', country: 'Ethiopia', country_code: 'ET' },
  { prefix: '+500', country: 'Falkland Islands', country_code: 'FK' },
  { prefix: '+298', country: 'Faroe Islands', country_code: 'FO' },
  { prefix: '+679', country: 'Fiji', country_code: 'FJ' },
  { prefix: '+358', country: 'Finland', country_code: 'FI' },
  { prefix: '+33', country: 'France', country_code: 'FR' },
  { prefix: '+596', country: 'French Antilles', country_code: '' },
  { prefix: '+594', country: 'French Guiana', country_code: 'GF' },
  { prefix: '+689', country: 'French Polynesia', country_code: 'PF' },
  { prefix: '+241', country: 'Gabon', country_code: 'GA' },
  { prefix: '+220', country: 'Gambia', country_code: 'GM' },
  { prefix: '+995', country: 'Georgia', country_code: 'GE' },
  { prefix: '+49', country: 'Germany', country_code: 'DE' },
  { prefix: '+233', country: 'Ghana', country_code: 'GH' },
  { prefix: '+350', country: 'Gibraltar', country_code: 'GI' },
  { prefix: '+30', country: 'Greece', country_code: 'GR' },
  { prefix: '+299', country: 'Greenland', country_code: 'GL' },
  { prefix: '+1 473', country: 'Grenada', country_code: 'GD' },
  { prefix: '+590', country: 'Guadeloupe', country_code: 'GP' },
  { prefix: '+1 671', country: 'Guam', country_code: 'GU' },
  { prefix: '+502', country: 'Guatemala', country_code: 'GT' },
  { prefix: '+224', country: 'Guinea', country_code: 'GN' },
  { prefix: '+245', country: 'Guinea-Bissau', country_code: 'GW' },
  { prefix: '+595', country: 'Guyana', country_code: 'GY' },
  { prefix: '+509', country: 'Haiti', country_code: 'HT' },
  { prefix: '+504', country: 'Honduras', country_code: 'HN' },
  { prefix: '+852', country: 'Hong Kong SAR China', country_code: 'HK' },
  { prefix: '+36', country: 'Hungary', country_code: 'HU' },
  { prefix: '+354', country: 'Iceland', country_code: 'IS' },
  { prefix: '+91', country: 'India', country_code: 'IN' },
  { prefix: '+62', country: 'Indonesia', country_code: 'ID' },
  { prefix: '+98', country: 'Iran', country_code: 'IR' },
  { prefix: '+964', country: 'Iraq', country_code: 'IQ' },
  { prefix: '+353', country: 'Ireland', country_code: 'IE' },
  { prefix: '+972', country: 'Israel', country_code: 'IL' },
  { prefix: '+39', country: 'Italy', country_code: 'IT' },
  { prefix: '+225', country: 'Ivory Coast', country_code: 'CI' },
  { prefix: '+1 876', country: 'Jamaica', country_code: 'JM' },
  { prefix: '+81', country: 'Japan', country_code: 'JP' },
  { prefix: '+962', country: 'Jordan', country_code: 'JO' },
  { prefix: '+7 7', country: 'Kazakhstan', country_code: 'KZ' },
  { prefix: '+254', country: 'Kenya', country_code: 'KE' },
  { prefix: '+686', country: 'Kiribati', country_code: 'KI' },
  { prefix: '+965', country: 'Kuwait', country_code: 'KW' },
  { prefix: '+996', country: 'Kyrgyzstan', country_code: 'KG' },
  { prefix: '+856', country: 'Laos', country_code: 'LA' },
  { prefix: '+371', country: 'Latvia', country_code: 'LV' },
  { prefix: '+961', country: 'Lebanon', country_code: 'LB' },
  { prefix: '+266', country: 'Lesotho', country_code: 'LS' },
  { prefix: '+231', country: 'Liberia', country_code: 'LR' },
  { prefix: '+218', country: 'Libya', country_code: 'LY' },
  { prefix: '+423', country: 'Liechtenstein', country_code: 'LI' },
  { prefix: '+370', country: 'Lithuania', country_code: 'LT' },
  { prefix: '+352', country: 'Luxembourg', country_code: 'LU' },
  { prefix: '+853', country: 'Macau SAR China', country_code: 'MO' },
  { prefix: '+389', country: 'Macedonia', country_code: 'MK' },
  { prefix: '+261', country: 'Madagascar', country_code: 'MG' },
  { prefix: '+265', country: 'Malawi', country_code: 'MW' },
  { prefix: '+60', country: 'Malaysia', country_code: 'MY' },
  { prefix: '+960', country: 'Maldives', country_code: 'MV' },
  { prefix: '+223', country: 'Mali', country_code: 'ML' },
  { prefix: '+356', country: 'Malta', country_code: 'MT' },
  { prefix: '+692', country: 'Marshall Islands', country_code: 'MH' },
  { prefix: '+596', country: 'Martinique', country_code: 'MQ' },
  { prefix: '+222', country: 'Mauritania', country_code: 'MR' },
  { prefix: '+230', country: 'Mauritius', country_code: 'MU' },
  { prefix: '+262', country: 'Mayotte', country_code: 'YT' },
  { prefix: '+52', country: 'Mexico', country_code: 'MX' },
  { prefix: '+691', country: 'Micronesia', country_code: 'FM' },
  { prefix: '+1 808', country: 'Midway Island', country_code: 'MI' },
  { prefix: '+373', country: 'Moldova', country_code: 'MD' },
  { prefix: '+377', country: 'Monaco', country_code: 'MC' },
  { prefix: '+976', country: 'Mongolia', country_code: 'MN' },
  { prefix: '+382', country: 'Montenegro', country_code: 'ME' },
  { prefix: '+1664', country: 'Montserrat', country_code: 'MS' },
  { prefix: '+212', country: 'Morocco', country_code: 'MA' },
  { prefix: '+95', country: 'Myanmar', country_code: 'MM' },
  { prefix: '+264', country: 'Namibia', country_code: 'NA' },
  { prefix: '+674', country: 'Nauru', country_code: 'NR' },
  { prefix: '+977', country: 'Nepal', country_code: 'NP' },
  { prefix: '+31', country: 'Netherlands', country_code: 'NL' },
  { prefix: '+599', country: 'Netherlands Antilles', country_code: 'AN' },
  { prefix: '+1 869', country: 'Nevis', country_code: 'KN' },
  { prefix: '+687', country: 'New Caledonia', country_code: 'NC' },
  { prefix: '+64', country: 'New Zealand', country_code: 'NZ' },
  { prefix: '+505', country: 'Nicaragua', country_code: 'NI' },
  { prefix: '+227', country: 'Niger', country_code: 'NE' },
  { prefix: '+234', country: 'Nigeria', country_code: 'NG' },
  { prefix: '+683', country: 'Niue', country_code: 'NU' },
  { prefix: '+672', country: 'Norfolk Island', country_code: 'NF' },
  { prefix: '+850', country: 'North Korea', country_code: 'KP' },
  { prefix: '+1 670', country: 'Northern Mariana Islands', country_code: 'MP' },
  { prefix: '+47', country: 'Norway', country_code: 'NO' },
  { prefix: '+968', country: 'Oman', country_code: 'OM' },
  { prefix: '+92', country: 'Pakistan', country_code: 'PK' },
  { prefix: '+680', country: 'Palau', country_code: 'PW' },
  { prefix: '+970', country: 'Palestinian Territory', country_code: 'PS' },
  { prefix: '+507', country: 'Panama', country_code: 'PA' },
  { prefix: '+675', country: 'Papua New Guinea', country_code: 'PG' },
  { prefix: '+595', country: 'Paraguay', country_code: 'PY' },
  { prefix: '+51', country: 'Peru', country_code: 'PE' },
  { prefix: '+63', country: 'Philippines', country_code: 'PH' },
  { prefix: '+48', country: 'Poland', country_code: 'PL' },
  { prefix: '+351', country: 'Portugal', country_code: 'PT' },
  { prefix: '+1 787', country: 'Puerto Rico', country_code: 'PR' },
  { prefix: '+1 939', country: 'Puerto Rico', country_code: 'PR' },
  { prefix: '+974', country: 'Qatar', country_code: 'QA' },
  { prefix: '+262', country: 'Reunion', country_code: 'RE' },
  { prefix: '+40', country: 'Romania', country_code: 'RO' },
  { prefix: '+7', country: 'Russia', country_code: 'RU' },
  { prefix: '+250', country: 'Rwanda', country_code: 'RW' },
  { prefix: '+685', country: 'Samoa', country_code: 'WS' },
  { prefix: '+378', country: 'San Marino', country_code: 'SM' },
  { prefix: '+966', country: 'Saudi Arabia', country_code: 'SA' },
  { prefix: '+221', country: 'Senegal', country_code: 'SN' },
  { prefix: '+381', country: 'Serbia', country_code: 'RS' },
  { prefix: '+248', country: 'Seychelles', country_code: 'SC' },
  { prefix: '+232', country: 'Sierra Leone', country_code: 'SL' },
  { prefix: '+65', country: 'Singapore', country_code: 'SG' },
  { prefix: '+421', country: 'Slovakia', country_code: 'SK' },
  { prefix: '+386', country: 'Slovenia', country_code: 'SI' },
  { prefix: '+677', country: 'Solomon Islands', country_code: 'SB' },
  { prefix: '+27', country: 'South Africa', country_code: 'ZA' },
  { prefix: '+500', country: 'South Georgia and the South Sandwich Islands', country_code: 'GS' },
  { prefix: '+82', country: 'South Korea', country_code: 'KR' },
  { prefix: '+34', country: 'Spain', country_code: 'ES' },
  { prefix: '+94', country: 'Sri Lanka', country_code: 'LK' },
  { prefix: '+249', country: 'Sudan', country_code: 'SD' },
  { prefix: '+597', country: 'Suriname', country_code: 'SR' },
  { prefix: '+268', country: 'Swaziland', country_code: 'SZ' },
  { prefix: '+46', country: 'Sweden', country_code: 'SE' },
  { prefix: '+41', country: 'Switzerland', country_code: 'CH' },
  { prefix: '+963', country: 'Syria', country_code: 'SY' },
  { prefix: '+886', country: 'Taiwan', country_code: 'TW' },
  { prefix: '+992', country: 'Tajikistan', country_code: 'TJ' },
  { prefix: '+255', country: 'Tanzania', country_code: 'TZ' },
  { prefix: '+66', country: 'Thailand', country_code: 'TH' },
  { prefix: '+670', country: 'Timor Leste', country_code: 'TL' },
  { prefix: '+228', country: 'Togo', country_code: 'TG' },
  { prefix: '+690', country: 'Tokelau', country_code: 'TK' },
  { prefix: '+676', country: 'Tonga', country_code: 'TO' },
  { prefix: '+1 868', country: 'Trinidad and Tobago', country_code: 'TT' },
  { prefix: '+216', country: 'Tunisia', country_code: 'TN' },
  { prefix: '+90', country: 'Turkey', country_code: 'TR' },
  { prefix: '+993', country: 'Turkmenistan', country_code: 'TM' },
  { prefix: '+1 649', country: 'Turks and Caicos Islands', country_code: 'TC' },
  { prefix: '+688', country: 'Tuvalu', country_code: 'TV' },
  { prefix: '+1 340', country: 'U.S. Virgin Islands', country_code: 'VI' },
  { prefix: '+256', country: 'Uganda', country_code: 'UG' },
  { prefix: '+380', country: 'Ukraine', country_code: 'UA' },
  { prefix: '+971', country: 'United Arab Emirates', country_code: 'AE' },
  { prefix: '+44', country: 'United Kingdom', country_code: 'GB' },
  { prefix: '+1', country: 'United States', country_code: 'US' },
  { prefix: '+598', country: 'Uruguay', country_code: 'UY' },
  { prefix: '+998', country: 'Uzbekistan', country_code: 'UZ' },
  { prefix: '+678', country: 'Vanuatu', country_code: 'VU' },
  { prefix: '+58', country: 'Venezuela', country_code: 'VE' },
  { prefix: '+84', country: 'Vietnam', country_code: 'VN' },
  { prefix: '+1 808', country: 'Wake Island', country_code: 'WK' },
  { prefix: '+681', country: 'Wallis and Futuna', country_code: 'WF' },
  { prefix: '+967', country: 'Yemen', country_code: 'YE' },
  { prefix: '+260', country: 'Zambia', country_code: 'ZM' },
  { prefix: '+255', country: 'Zanzibar', country_code: '' },
  { prefix: '+263', country: 'Zimbabwe', country_code: 'ZW' },
];
