import { DELIVERY_ONGOING_STATES } from '@api/core/model/delivery/transaction/delivery-status/delivery-ongoing-states.enum';
import { DELIVERY_ONGOING_STATUS } from '@api/core/model/delivery/transaction/delivery-status/delivery-ongoing-status.enum';
import { ToDomainMapper } from '@api/core/utils/types';

const deliveryPendingTransactionStateRelation: Record<DELIVERY_ONGOING_STATUS, DELIVERY_ONGOING_STATES> = {
  [DELIVERY_ONGOING_STATUS.REQUEST_CREATED]: DELIVERY_ONGOING_STATES.REQUEST_CREATED,
  [DELIVERY_ONGOING_STATUS.TRANSACTION_CREATED]: DELIVERY_ONGOING_STATES.TRANSACTION_CREATED,
  [DELIVERY_ONGOING_STATUS.DELIVERED_TO_CARRIER]: DELIVERY_ONGOING_STATES.ITEM_DELIVERED_TO_CARRIER,
  [DELIVERY_ONGOING_STATUS.IN_TRANSIT]: DELIVERY_ONGOING_STATES.IN_TRANSIT,
  [DELIVERY_ONGOING_STATUS.DELIVERED]: DELIVERY_ONGOING_STATES.ITEM_DELIVERED,
  [DELIVERY_ONGOING_STATUS.ON_HOLD_AT_CARRIER]: DELIVERY_ONGOING_STATES.ON_HOLD_AT_CARRIER,
  [DELIVERY_ONGOING_STATUS.ON_HOLD_INSTRUCTIONS_RECEIVED]: DELIVERY_ONGOING_STATES.ON_HOLD_INSTRUCTIONS_RECEIVED,
  [DELIVERY_ONGOING_STATUS.AVAILABLE_FOR_THE_RECIPIENT_CARRIER_OFFICE]: DELIVERY_ONGOING_STATES.ITEM_AVAILABLE_FOR_THE_RECIPIENT,
  [DELIVERY_ONGOING_STATUS.AVAILABLE_FOR_THE_RECIPIENT_HOME_PICKUP]: DELIVERY_ONGOING_STATES.ITEM_AVAILABLE_FOR_THE_RECIPIENT,
  [DELIVERY_ONGOING_STATUS.DELIVERY_PENDING_TO_RETRY]: DELIVERY_ONGOING_STATES.DELIVERY_PENDING_TO_RETRY,
  [DELIVERY_ONGOING_STATUS.PICKUP_PENDING_TO_RETRY]: DELIVERY_ONGOING_STATES.PENDING_TO_RETRY,
  [DELIVERY_ONGOING_STATUS.HOME_PICK_DELIVERY_FAILED]: DELIVERY_ONGOING_STATES.PENDING_TO_RETRY,
  [DELIVERY_ONGOING_STATUS.TRANSACTION_ERROR]: DELIVERY_ONGOING_STATES.SHIPPING_FAILED,
  [DELIVERY_ONGOING_STATUS.DISPUTE_OPEN]: DELIVERY_ONGOING_STATES.DISPUTE_OPEN,
  [DELIVERY_ONGOING_STATUS.DISPUTE_ACCEPTED]: DELIVERY_ONGOING_STATES.DISPUTE_ACCEPTED,
  [DELIVERY_ONGOING_STATUS.DISPUTE_ACCEPTED_BY_WALLAPOP]: DELIVERY_ONGOING_STATES.DISPUTE_ACCEPTED_BY_WALLAPOP,
  [DELIVERY_ONGOING_STATUS.DISPUTE_ESCALATED]: DELIVERY_ONGOING_STATES.DISPUTE_ESCALATED,
  [DELIVERY_ONGOING_STATUS.TRANSACTION_DEFAULT]: null,
  [DELIVERY_ONGOING_STATUS.REQUEST_DEFAULT]: null,
};

export const mapDeliveryPendingTransactionState: ToDomainMapper<DELIVERY_ONGOING_STATUS, DELIVERY_ONGOING_STATES> = (
  input: DELIVERY_ONGOING_STATUS
): DELIVERY_ONGOING_STATES => {
  return deliveryPendingTransactionStateRelation[input];
};
