export const ITEM_BAN_REASONS: any = [
  '',
  'wrong_category',
  'people_or_animals',
  'joke',
  'fake_item',
  'explicit_content',
  'wrong_image',
  'food',
  'drugs_or_medicines',
  'duplicate_product',
  'forbidden_product_service',
  'resale',
  'ad_or_spam',
  'other',
];
