/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users clicks on item card displayed in different screens
 */
export interface ClickItemCard {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId?: number;
  /**
   * Index of the item displayed in the screen
   */
  position: number;
  /**
   * The unique identifier of the search that the click is under
   */
  searchId: string;
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId: number;
  /**
   * If the item clicked is from a professional user
   */
  isPro?: boolean;
  /**
   * Item price
   */
  salePrice: number;
  /**
   * Item title
   */
  title: string;
  [k: string]: any;
}
