/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User edits an uploaded product
 */
export interface EditItem {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Item price
   */
  salePrice: number;
  /**
   * Item title
   */
  title: string;
  /**
   * Car Brand
   */
  car_brand?: string;
  /**
   * Car Model
   */
  car_model?: string;
  /**
   * Car Bodytype
   */
  car_bodytype?: string;
  /**
   * Car km
   */
  car_km?: number;
  /**
   * Car Year
   */
  car_year?: number;
  /**
   * Car Engine
   */
  car_engine?: string;
  /**
   * Consumer Goods Type of Object
   */
  cg_to?: string;
  /**
   * Consumer Goods Brand
   */
  cg_brand?: string;
  /**
   * Consumer Goods Model
   */
  cg_model?: string;
  /**
   * Real State Operation
   */
  re_operation?: string;
  /**
   * Real State Property Type
   */
  re_type?: string;
  /**
   * Real State surface area
   */
  re_m2?: number;
  /**
   * If the item clicked is from a professional user
   */
  isPro: boolean;
  /**
   * Identifier of the screen that the item was edited from
   */
  screenId: number;
  [k: string]: any;
}
