/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * View register presentation screen
 */
export interface DisplayRegisterPresentationPage {
  /**
   * Identifier of the screen that the user arrives to the register presentation
   */
  screenId: number;
  [k: string]: any;
}
