- name: Set stack name
  set_fact:
    stack_name: 'Webapp-{{ env }}'

- name: Set template parameters
  set_fact:
    template_parameters:
      EnvName: '{{ env }}'
      Branch: '{{ branch }}'
      Commit: '{{ commit }}'
      BucketES: '{{ origin_bucket_es }}'
      BucketEN: '{{ origin_bucket_en }}'
      HostES: '{{ host_es }}'
      HostEN: '{{ host_en }}'
  when: env_action != 'destroy'

#########
# Create
#########

- name: Create / Update {{ stack_name }} stack
  cloudformation:
    stack_name: '{{ stack_name }}'
    stack_policy: '{{ policies_path }}/webapp.json'
    state: 'present'
    region: '{{ aws_region }}'
    template_url: '{{ templates_url }}/webapp.yaml'
    template_parameters: '{{ template_parameters }}'
    tags:
      'Env': '{{ env }}'
  register: vpc_stack
  when: env_action == 'create'

##########
# Destroy
##########

- name: Delete {{ stack_name }} stack
  cloudformation:
    stack_name: '{{ stack_name }}'
    state: 'absent'
    region: '{{ aws_region }}'
  when: env_action == 'destroy' and stack_name in stack_list_json

#######
# Test
#######

- include: 'includes/change_set_test.yml'
  when: env_action == 'test' and stack_name in stack_list_json
