import { CATEGORY_IDS } from '@core/category/category-ids';
import { ITEM_DATA_FIELD } from './item-data-field-constants';

export const COMMON_REQUIRED_FIELDS = [
  ITEM_DATA_FIELD.CATEGORY_ID,
  ITEM_DATA_FIELD.IMAGES,
  ITEM_DATA_FIELD.DESCRIPTION,
  ITEM_DATA_FIELD.SALE_PRICE,
  ITEM_DATA_FIELD.CURRENCY_CODE,
];
export const CATEGORY_IDS_WITH_REQUIRED_SECOND_LEVEL_OBJECT_TYPE = [CATEGORY_IDS.CELL_PHONES_ACCESSORIES, CATEGORY_IDS.FASHION_ACCESSORIES];

export const ITEM_REQUIRED_FIELDS_BY_CATEGORY_ID = {
  [CATEGORY_IDS.AGRICULTURE_INDUSTRIAL]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.APPLIANCES]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.BABIES_CHILD]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.BIKES]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.CAR]: [
    ...COMMON_REQUIRED_FIELDS,
    ITEM_DATA_FIELD.MODEL,
    ITEM_DATA_FIELD.BRAND,
    ITEM_DATA_FIELD.YEAR,
    ITEM_DATA_FIELD.VERSION,
  ],
  [CATEGORY_IDS.CELL_PHONES_ACCESSORIES]: [
    ...COMMON_REQUIRED_FIELDS,
    `${ITEM_DATA_FIELD.EXTRA_INFO}.${ITEM_DATA_FIELD.OBJECT_TYPE}.${ITEM_DATA_FIELD.ID}`,
    `${ITEM_DATA_FIELD.EXTRA_INFO}.${ITEM_DATA_FIELD.BRAND}`,
  ],
  [CATEGORY_IDS.COLLECTIBLES_ART]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.COMPUTERS_ELECTRONICS]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.CONSTRUCTION]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.FASHION_ACCESSORIES]: [
    ...COMMON_REQUIRED_FIELDS,
    `${ITEM_DATA_FIELD.EXTRA_INFO}.${ITEM_DATA_FIELD.OBJECT_TYPE}.${ITEM_DATA_FIELD.ID}`,
    `${ITEM_DATA_FIELD.EXTRA_INFO}.${ITEM_DATA_FIELD.BRAND}`,
    `${ITEM_DATA_FIELD.EXTRA_INFO}.${ITEM_DATA_FIELD.GENDER}`,
  ],
  [CATEGORY_IDS.GAMES_BOOKS]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.GAMES_CONSOLES]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.HOME_GARDEN]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.JOBS]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.MOTORBIKE]: [...COMMON_REQUIRED_FIELDS],
  [CATEGORY_IDS.MOTOR_ACCESSORIES]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.OTHERS]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.REAL_ESTATE]: [
    ...COMMON_REQUIRED_FIELDS,
    ITEM_DATA_FIELD.CONDITION,
    ITEM_DATA_FIELD.TYPE,
    ITEM_DATA_FIELD.OPERATION,
    ITEM_DATA_FIELD.STORYTELLING,
    `${ITEM_DATA_FIELD.LOCATION}.${ITEM_DATA_FIELD.ADDRESS}`,
    `${ITEM_DATA_FIELD.LOCATION}.${ITEM_DATA_FIELD.LATITUDE}`,
    `${ITEM_DATA_FIELD.LOCATION}.${ITEM_DATA_FIELD.LONGITUDE}`,
  ],
  [CATEGORY_IDS.SERVICES]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.SPORTS_LEISURE]: COMMON_REQUIRED_FIELDS,
  [CATEGORY_IDS.TV_AUDIO_CAMERAS]: COMMON_REQUIRED_FIELDS,
};
