export enum ITEM_DATA_FIELD {
  CATEGORY_ID = 'category_id',
  IMAGES = 'images',
  TITLE = 'title',
  DESCRIPTION = 'description',
  SALE_PRICE = 'sale_price',
  CURRENCY_CODE = 'currency_code',
  BRAND = 'brand',
  EXTRA_INFO = 'extra_info',
  GENDER = 'gender',
  ID = 'id',
  OBJECT_TYPE = 'object_type',
  PARENT_OBJECT_TYPE = 'parent_object_type',
  SIZE = 'size',
  MODEL = 'model',
  YEAR = 'year',
  VERSION = 'version',
  CONDITION = 'condition',
  TYPE = 'type',
  OPERATION = 'operation',
  STORYTELLING = 'storytelling',
  LOCATION = 'location',
  ADDRESS = 'address',
  LATITUDE = 'latitude',
  LONGITUDE = 'longitude',
  SURFACE = 'surface',
}
