import { ONGOING_TRANSACTION_TRACKING_STATUS } from '@api/core/model/delivery/transaction/status';
import { HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE } from '@shared/historic-list/enums/historic-element-subdescription-type.enum';

export const mapOngoingTransactionTrackingStatusToSubDescriptionType: Record<
  ONGOING_TRANSACTION_TRACKING_STATUS,
  HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE
> = {
  [ONGOING_TRANSACTION_TRACKING_STATUS.REQUEST_CREATED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.TRANSACTION_CREATED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.PENDING_TO_RETRY_HPU]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [ONGOING_TRANSACTION_TRACKING_STATUS.ITEM_DELIVERED_TO_CARRIER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.IN_TRANSIT]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.DELIVERY_PENDING_TO_RETRY_HPU]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [ONGOING_TRANSACTION_TRACKING_STATUS.ON_HOLD_AT_CARRIER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [ONGOING_TRANSACTION_TRACKING_STATUS.ON_HOLD_INSTRUCTIONS_RECEIVED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [ONGOING_TRANSACTION_TRACKING_STATUS.ITEM_AVAILABLE_FOR_THE_RECIPIENT]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.ITEM_AVAILABLE_FOR_THE_RECIPIENT_HPU]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.ITEM_DELIVERED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.SHIPPING_FAILED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [ONGOING_TRANSACTION_TRACKING_STATUS.DISPUTE_OPEN]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.DISPUTE_ACCEPTED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.DISPUTE_ESCALATED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [ONGOING_TRANSACTION_TRACKING_STATUS.DISPUTE_ACCEPTED_BY_WALLAPOP]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
};
