import { DELIVERY_ONGOING_STATES } from '@api/core/model/delivery/transaction/delivery-status/delivery-ongoing-states.enum';
import { HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE } from '@shared/historic-list/enums/historic-element-subdescription-type.enum';

export const mapOngoingTransactionTrackingStatusToSubDescriptionType: Record<
  DELIVERY_ONGOING_STATES,
  HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE
> = {
  [DELIVERY_ONGOING_STATES.REQUEST_CREATED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.TRANSACTION_CREATED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.ITEM_DELIVERED_TO_CARRIER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.IN_TRANSIT]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.ITEM_DELIVERED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.ON_HOLD_AT_CARRIER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.ON_HOLD_INSTRUCTIONS_RECEIVED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [DELIVERY_ONGOING_STATES.ITEM_AVAILABLE_FOR_THE_RECIPIENT]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.DELIVERY_PENDING_TO_RETRY]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [DELIVERY_ONGOING_STATES.PENDING_TO_RETRY]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [DELIVERY_ONGOING_STATES.SHIPPING_FAILED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [DELIVERY_ONGOING_STATES.DISPUTE_OPEN]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.DISPUTE_ACCEPTED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.DISPUTE_ACCEPTED_BY_WALLAPOP]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [DELIVERY_ONGOING_STATES.DISPUTE_ESCALATED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
};
