export enum MetricTypeEnum {
  XMPP_CONNECTION_TIME = 'XMPP_CONNECTION_TIME',
  XMPP_CONNECTION_CLOSED_WITH_ERROR = 'XMPP_CONNECTION_CLOSED_WITH_ERROR',
  CLIENT_SEND_MESSAGE_TIME = 'CLIENT_SEND_MESSAGE_TIME',
  XMPP_ACCEPT_MESSAGE_TIME = 'XMPP_ACCEPT_MESSAGE_TIME',
  CLIENT_PRESENTATION_MESSAGE_TIME = 'CLIENT_PRESENTATION_MESSAGE_TIME',
  DUPLICATE_CONVERSATION = 'DUPLICATE_CONVERSATION',
}
