export enum MetricTypeEnum {
  XMPP_CONNECTION_TIME = 'XMPP_CONNECTION_TIME',
  XMPP_SEND_MESSAGE_TIME = 'XMPP_SEND_MESSAGE_TIME',
  XMPP_ACCEPT_MESSAGE_TIME = 'XMPP_ACCEPT_MESSAGE_TIME',
  DUPLICATE_CONVERSATION = 'DUPLICATE_CONVERSATION'
}
