import { VERIFICATIONS_N_SECURITY_STATUS } from './verifications-n-security-status.enum';
import { VERIFICATIONS_N_SECURITY_TYPES } from './verifications-n-security-types.enum';

export interface UserVerificationsStatus {
  [VERIFICATIONS_N_SECURITY_TYPES.EMAIL]: VERIFICATIONS_N_SECURITY_STATUS;
  [VERIFICATIONS_N_SECURITY_TYPES.PHONE]: VERIFICATIONS_N_SECURITY_STATUS;
  [VERIFICATIONS_N_SECURITY_TYPES.PASSWORD]: VERIFICATIONS_N_SECURITY_STATUS;
}
