Description: 'Template containing webapp pipeline, all its resources and the deployment.'

Parameters:
  EnvName:
    Description: 'Environment where it has to be deployed'
    Type: String
  ImageTag:
    Description: 'Tag how the .zip file is tagged'
    Type: String
  ProjectName:
    Description: 'Name of the project'
    Type: String
  BucketNameFunctionalWebapp:
    Description: 'Name of the bucket where the functional webapp is hosted in multiple locales'
    Type: String
  FunctionalWebappDistributionID:
    Description: 'ID for the CloudFront distribution for the web project. This variable is temporary until CF is scripted'
    Type: String
  ArtifactBucket:
    Description: Bucket where pipeline store its artifacts
    Type: String
    Default: "codebuild-cache-wallapop"
  S3SourceBucket:
    Description: Bucket where the .zip file is pushed to trigger this pipeline
    Type: String
    Default: "wallapop-trigger-link-cicd"

Resources:
  CodeBuildDeployScripts:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "webapp-deploy-service-${EnvName}"
      Description: !Sub "Uploads webapp project to ${EnvName} hosting buckets"
      ServiceRole:
        Fn::ImportValue: execute-predeploy-role
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
              build:
                  commands:
                    - aws s3 sync ./ s3://$HOSTING_BUCKET_FUNCTIONAL_WEBAPP --delete --exclude "infrastructure/*" --exclude "dist/*"
                    - aws s3 cp ./ s3://$HOSTING_BUCKET_FUNCTIONAL_WEBAPP --recursive --exclude "*" --include "*.html" --exclude "dist/*.html" --cache-control max-age=0,must-revalidate
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/docker:17.09.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: HOSTING_BUCKET_FUNCTIONAL_WEBAPP
            Value: !Ref BucketNameFunctionalWebapp
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "Core-${EnvName}-SSHSecurityGroup"
        VpcId:
          Fn::ImportValue:
            !Sub "${EnvName}-vpc"
        Subnets:
          - Fn::ImportValue:
              !Sub "${EnvName}-public-subnet-a"
      Tags:
        - Key: Env
          Value: !Ref EnvName
        - Key: Project
          Value: !Ref ProjectName

  DeployServiceCodebuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/codebuild/webapp-deploy-service-${EnvName}"
      RetentionInDays: 90

  CodeBuildScripts:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "webapp-invalidate-caches-${EnvName}"
      Description: !Sub "Invalidate caches for webapp ${EnvName} distributions"
      ServiceRole:
        Fn::ImportValue: execute-predeploy-role
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
              build:
                  commands:
                    - aws cloudfront create-invalidation --distribution-id $FUNCTIONAL_WEBAPP_DISTRIBUTION_ID --paths "/app/index.html" "/app/ngsw-worker.js" "/app/ngsw.json"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/docker:17.09.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: FUNCTIONAL_WEBAPP_DISTRIBUTION_ID
            Value: !Ref FunctionalWebappDistributionID
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "Core-${EnvName}-SSHSecurityGroup"
        VpcId:
          Fn::ImportValue:
            !Sub "${EnvName}-vpc"
        Subnets:
          - Fn::ImportValue:
              !Sub "${EnvName}-private-subnet-a"
      Tags:
        - Key: Env
          Value: !Ref EnvName
        - Key: Project
          Value: !Ref ProjectName

  InvalidateCachesCodebuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/codebuild/webapp-invalidate-caches-${EnvName}"
      RetentionInDays: 90

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub webapp-${EnvName}
      RoleArn:
        Fn::ImportValue: execute-pipeline-role
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: webapp
              ActionTypeId:
                Category: Source
                Provider: S3
                Owner: AWS
                Version: "1"
              Configuration:
                S3Bucket: !Ref S3SourceBucket
                S3ObjectKey: !Sub webapp/webapp-${ImageTag}.zip
              OutputArtifacts:
                - Name: App

        - Name: Infrastructure
          Actions:
            - Name: Pipeline
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                StackName: !Sub webapp-pipeline-${EnvName}
                TemplateConfiguration: !Sub 'App::infrastructure/pipeline/${EnvName}.json'
                TemplatePath: App::infrastructure/pipeline/template.yaml
                RoleArn:
                  Fn::ImportValue: manage-pipeline-stack-role
              InputArtifacts:
                - Name: App
              RunOrder: 1
            - Name: S3
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                StackName: !Sub webapp-s3-${EnvName}
                TemplateConfiguration: !Sub 'App::infrastructure/s3/${EnvName}.json'
                TemplatePath: App::infrastructure/s3/template.yml
                RoleArn:
                  Fn::ImportValue: manage-serverless-stack-role
              InputArtifacts:
                - Name: App
              RunOrder: 2
            - Name: Cloudfront
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                StackName: !Sub Webapp-${EnvName}
                TemplateConfiguration: !Sub 'App::infrastructure/cloudfront/${EnvName}.json'
                TemplatePath: App::infrastructure/cloudfront/template.yaml
                RoleArn:
                  Fn::ImportValue: manage-serverless-stack-role
              InputArtifacts:
                - Name: App
              RunOrder: 3

        - Name: Deploy
          Actions:
            - Name: Service
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildDeployScripts
              InputArtifacts:
                - Name: App
              RunOrder: 1
            - Name: Invalidate-Caches
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildScripts
              InputArtifacts:
                - Name: App
              RunOrder: 2
