export const MOCK_CATEGORIES_RESPONSE = [
  {
    category_id: 100,
    name: 'Coches',
    icon_id: 'car',
    vertical_id: 'cars',
    fields: {},
    hasShipping: false,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 14000,
    name: 'Motos',
    icon_id: 'motorbike',
    vertical_id: 'consumer_goods',
    fields: {},
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12800,
    name: 'Motor y Accesorios',
    icon_id: 'helmet',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12465,
    name: 'Moda y Accesorios',
    icon_id: 't-shirt',
    vertical_id: 'consumer_goods',
    fields: {
      type_of_object: { title: 'Tipo de prenda', order: 0 },
      brand: { title: 'Marca', order: 1 },
      size: { title: 'Talla', order: 3 },
      gender: { title: 'Género', order: 2 },
    },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 200,
    name: 'Inmobiliaria',
    icon_id: 'house',
    vertical_id: 'real_estate',
    fields: {},
    hasShipping: false,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12545,
    name: 'TV, Audio y Foto',
    icon_id: 'tv',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 16000,
    name: 'Móviles y Telefonía',
    icon_id: 'phone',
    vertical_id: 'consumer_goods',
    fields: {
      type_of_object: { title: 'Tipo de producto', order: 0 },
      brand: { title: 'Marca', order: 1 },
      model: { title: 'Modelo', order: 2 },
    },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 15000,
    name: 'Informática y Electrónica',
    icon_id: 'pc',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12579,
    name: 'Deporte y Ocio',
    icon_id: 'ball',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 17000,
    name: 'Bicicletas',
    icon_id: 'bike',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12900,
    name: 'Consolas y Videojuegos',
    icon_id: 'gamepad',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12467,
    name: 'Hogar y Jardín',
    icon_id: 'furniture',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 13100,
    name: 'Electrodomésticos',
    icon_id: 'laundry',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12463,
    name: 'Cine, Libros y Música',
    icon_id: 'bookshelf',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12461,
    name: 'Niños y Bebés',
    icon_id: 'baby_car',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 18000,
    name: 'Coleccionismo',
    icon_id: 'collecting',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 19000,
    name: 'Materiales de construcción',
    icon_id: 'building',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 20000,
    name: 'Industria y Agricultura',
    icon_id: 'farming',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 21000,
    name: 'Empleo',
    icon_id: 'jobs',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 } },
    hasShipping: false,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 13200,
    name: 'Servicios',
    icon_id: 'toolbox',
    vertical_id: 'consumer_goods',
    fields: { type_of_object: { title: 'Subcategoría', order: 0 }, type_of_object_level_2: { title: '¿Puedes especificar?', order: 1 } },
    hasShipping: false,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
  {
    category_id: 12485,
    name: 'Otros',
    icon_id: 'ghost',
    vertical_id: 'consumer_goods',
    fields: {},
    hasShipping: true,
    profile_slider: { text: 'Vendedores destacados', has_call_to_action: true },
    bump_slider: { has_call_to_action: true },
    bump_item_icon: 'default_icon',
    has_num_item_top_sellers: true,
  },
];
