import { Car } from '@core/item/car';
import { Item } from '@core/item/item';
import { Image } from '@core/user/user-response.interface';
import { CAR_DATA } from '@fixtures/car.fixtures.spec';
import { ITEM_DATA } from '@fixtures/item.fixtures.spec';

const MOCK_ITEM_IMAGES: Image[] = [
  {
    id: '4z4vl5ygwvzy',
    legacy_id: 500002514,
    original_width: 100,
    original_height: 62,
    average_hex_color: '6a707b',
    urls_by_size: {
      original: 'http://localhost:6006/images/item-camera.jpg',
      small: 'http://localhost:6006/images/item-camera.jpg',
      large: 'http://localhost:6006/images/item-camera.jpg',
      medium: 'http://localhost:6006/images/item-camera.jpg',
      xlarge: 'http://localhost:6006/images/item-camera.jpg',
    },
  },
  {
    id: '4z4vl5ygwvzy',
    legacy_id: 500002514,
    original_width: 100,
    original_height: 62,
    average_hex_color: '6a707b',
    urls_by_size: {
      original: 'http://localhost:6006/images/item-pc.jpg',
      small: 'http://localhost:6006/images/item-pc.jpg',
      large: 'http://localhost:6006/images/item-pc.jpg',
      medium: 'http://localhost:6006/images/item-pc.jpg',
      xlarge: 'http://localhost:6006/images/item-pc.jpg',
    },
  },
];

const MOCK_ITEM_IMAGES_CAR: Image[] = [
  {
    id: '4z4vl5ygwvzy',
    legacy_id: 500002514,
    original_width: 100,
    original_height: 62,
    average_hex_color: '6a707b',
    urls_by_size: {
      original: 'http://localhost:6006/images/item-car.jpg',
      small: 'http://localhost:6006/images/item-car.jpg',
      large: 'http://localhost:6006/images/item-car.jpg',
      medium: 'http://localhost:6006/images/item-car.jpg',
      xlarge: 'http://localhost:6006/images/item-car.jpg',
    },
  },
  {
    id: '4z4vl5ygwvzy',
    legacy_id: 500002514,
    original_width: 100,
    original_height: 62,
    average_hex_color: '6a707b',
    urls_by_size: {
      original: 'http://localhost:6006/images/item-car2.jpg',
      small: 'http://localhost:6006/images/item-car2.jpg',
      large: 'http://localhost:6006/images/item-car2.jpg',
      medium: 'http://localhost:6006/images/item-car2.jpg',
      xlarge: 'http://localhost:6006/images/item-car2.jpg',
    },
  },
];

const MOCK_DESCRIPTION =
  'se vende 407 perfecto estado recién revisado correa distribución cambiada gomas nuevas es el tope gama cuero,clima,pantalla multifunción ,sensor aparcamiento ,etc .se entrega con la ITV recién pasada .abstenerse curiosos solo gente seria .cambiaría solo por moto enduro o quad precio poco negociable está en Málaga. Peugeot 407 Sedan en Málaga';

export const MOCK_ITEM: Item = new Item(
  ITEM_DATA.id,
  ITEM_DATA.legacy_id,
  ITEM_DATA.owner,
  ITEM_DATA.title,
  MOCK_DESCRIPTION,
  ITEM_DATA.category_id,
  ITEM_DATA.location,
  ITEM_DATA.sale_price,
  ITEM_DATA.currency_code,
  ITEM_DATA.modified_date,
  ITEM_DATA.url,
  ITEM_DATA.flags,
  ITEM_DATA.actions_allowed,
  ITEM_DATA.sale_conditions,
  ITEM_DATA.main_image,
  MOCK_ITEM_IMAGES,
  ITEM_DATA.web_slug,
  ITEM_DATA.published_date,
  ITEM_DATA.delivery_info
);

export const MOCK_CAR: Car = new Car(
  CAR_DATA.content.id,
  CAR_DATA.content.seller_id,
  CAR_DATA.content.title,
  'This is the storytelling',
  CAR_DATA.content.sale_price,
  CAR_DATA.content.currency_code,
  CAR_DATA.content.modified_date,
  CAR_DATA.content.url,
  CAR_DATA.content.flags,
  CAR_DATA.content.sale_conditions,
  MOCK_ITEM_IMAGES_CAR,
  CAR_DATA.content.web_slug,
  CAR_DATA.content.brand,
  CAR_DATA.content.model,
  CAR_DATA.content.year,
  CAR_DATA.content.gearbox,
  CAR_DATA.content.engine,
  CAR_DATA.content.color,
  CAR_DATA.content.horsepower,
  CAR_DATA.content.body_type,
  CAR_DATA.content.num_doors,
  CAR_DATA.content.extras,
  CAR_DATA.content.warranty,
  CAR_DATA.content.num_seats,
  CAR_DATA.content.condition,
  CAR_DATA.content.version,
  CAR_DATA.content.sale_price,
  undefined,
  undefined,
  CAR_DATA.content.km
);

export const MOCK_ITEM_RESERVED: Item = new Item(
  ITEM_DATA.id,
  ITEM_DATA.legacy_id,
  ITEM_DATA.owner,
  ITEM_DATA.title,
  MOCK_DESCRIPTION,
  ITEM_DATA.category_id,
  ITEM_DATA.location,
  ITEM_DATA.sale_price,
  ITEM_DATA.currency_code,
  ITEM_DATA.modified_date,
  ITEM_DATA.url,
  {
    pending: false,
    banned: false,
    expired: false,
    favorite: false,
    sold: false,
    reserved: true,
    bumped: false,
  },
  ITEM_DATA.actions_allowed,
  ITEM_DATA.sale_conditions,
  ITEM_DATA.main_image,
  MOCK_ITEM_IMAGES,
  ITEM_DATA.web_slug,
  ITEM_DATA.published_date,
  ITEM_DATA.delivery_info
);

export const MOCK_ITEM_FAVOURITE = new Item(
  ITEM_DATA.id,
  ITEM_DATA.legacy_id,
  ITEM_DATA.owner,
  ITEM_DATA.title,
  MOCK_DESCRIPTION,
  ITEM_DATA.category_id,
  ITEM_DATA.location,
  ITEM_DATA.sale_price,
  ITEM_DATA.currency_code,
  ITEM_DATA.modified_date,
  ITEM_DATA.url,
  {
    pending: false,
    banned: false,
    expired: false,
    favorite: true,
    sold: false,
    reserved: false,
    bumped: false,
  },
  ITEM_DATA.actions_allowed,
  ITEM_DATA.sale_conditions,
  ITEM_DATA.main_image,
  MOCK_ITEM_IMAGES,
  ITEM_DATA.web_slug,
  ITEM_DATA.published_date,
  ITEM_DATA.delivery_info
);

export const MOCK_ITEM_SOLD = new Item(
  ITEM_DATA.id,
  ITEM_DATA.legacy_id,
  ITEM_DATA.owner,
  ITEM_DATA.title,
  MOCK_DESCRIPTION,
  ITEM_DATA.category_id,
  ITEM_DATA.location,
  ITEM_DATA.sale_price,
  ITEM_DATA.currency_code,
  ITEM_DATA.modified_date,
  ITEM_DATA.url,
  {
    pending: false,
    banned: false,
    expired: false,
    favorite: false,
    sold: true,
    reserved: false,
    bumped: false,
  },
  ITEM_DATA.actions_allowed,
  ITEM_DATA.sale_conditions,
  ITEM_DATA.main_image,
  MOCK_ITEM_IMAGES,
  ITEM_DATA.web_slug,
  ITEM_DATA.published_date,
  ITEM_DATA.delivery_info
);

export const MOCK_ITEM_BUMPED = new Item(
  ITEM_DATA.id,
  ITEM_DATA.legacy_id,
  ITEM_DATA.owner,
  ITEM_DATA.title,
  ITEM_DATA.description,
  ITEM_DATA.category_id,
  ITEM_DATA.location,
  ITEM_DATA.sale_price,
  ITEM_DATA.currency_code,
  ITEM_DATA.modified_date,
  ITEM_DATA.url,
  ITEM_DATA.flags,
  ITEM_DATA.actions_allowed,
  ITEM_DATA.sale_conditions,
  ITEM_DATA.main_image,
  MOCK_ITEM_IMAGES,
  ITEM_DATA.web_slug,
  ITEM_DATA.published_date,
  ITEM_DATA.delivery_info,
  null,
  null,
  null,
  null,
  {
    bumped: true,
    highlighted: false,
    urgent: false,
    country_bumped: false,
    boosted: false,
  }
);

export const MOCK_ITEM_COUNTRY_BUMPED = new Item(
  ITEM_DATA.id,
  ITEM_DATA.legacy_id,
  ITEM_DATA.owner,
  ITEM_DATA.title,
  ITEM_DATA.description,
  ITEM_DATA.category_id,
  ITEM_DATA.location,
  ITEM_DATA.sale_price,
  ITEM_DATA.currency_code,
  ITEM_DATA.modified_date,
  ITEM_DATA.url,
  ITEM_DATA.flags,
  ITEM_DATA.actions_allowed,
  ITEM_DATA.sale_conditions,
  ITEM_DATA.main_image,
  MOCK_ITEM_IMAGES,
  ITEM_DATA.web_slug,
  ITEM_DATA.published_date,
  ITEM_DATA.delivery_info,
  null,
  null,
  null,
  null,
  {
    bumped: false,
    highlighted: false,
    urgent: false,
    country_bumped: true,
    boosted: false,
  }
);

export const MOCK_ITEM_WITHOUT_IMAGES = new Item(
  ITEM_DATA.id,
  ITEM_DATA.legacy_id,
  ITEM_DATA.owner,
  ITEM_DATA.title,
  ITEM_DATA.description,
  ITEM_DATA.category_id,
  ITEM_DATA.location,
  ITEM_DATA.sale_price,
  ITEM_DATA.currency_code,
  ITEM_DATA.modified_date,
  ITEM_DATA.url,
  ITEM_DATA.flags,
  ITEM_DATA.actions_allowed,
  ITEM_DATA.sale_conditions,
  ITEM_DATA.main_image,
  null,
  ITEM_DATA.web_slug,
  ITEM_DATA.published_date,
  ITEM_DATA.delivery_info
);
