import { TRANSACTION_DELIVERY_STATUS } from '@api/core/model/delivery/transaction/status';
import { HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE } from '@shared/historic-list/enums/historic-element-subdescription-type.enum';

export const mapTransactionStatusToSubDescriptionType: Record<TRANSACTION_DELIVERY_STATUS, HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE> = {
  [TRANSACTION_DELIVERY_STATUS.PENDING_REGISTRATION]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.PENDING_DELIVERY_TO_CARRIER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.DELIVERED_TO_CARRIER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.IN_TRANSIT]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.DELIVERED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.LOST]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [TRANSACTION_DELIVERY_STATUS.RETURNED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.AVAILABLE_FOR_THE_RECIPIENT]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.FAILED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [TRANSACTION_DELIVERY_STATUS.ATTEMPT_PICKUP_FAILED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [TRANSACTION_DELIVERY_STATUS.ATTEMPT_DELIVERY_FAILED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.ERROR,
  [TRANSACTION_DELIVERY_STATUS.ON_HOLD_AT_CARRIER]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.ON_HOLD_INSTRUCTIONS_RECEIVED]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.VALID,
  [TRANSACTION_DELIVERY_STATUS.NONE]: HISTORIC_ELEMENT_SUBDESCRIPTION_TYPE.NORMAL,
};
