import { COMMON_FILTERS } from '../common.enum';
import { REAL_ESTATE_COMMON, REAL_ESTATE_SURFACES_BY_TYPE } from './real-estate-common.enum';

export enum REAL_ESTATE_RENT_DEFAULT_FILTERS {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-default-price',
  LOCATION = COMMON_FILTERS.LOCATION,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_HOUSE_FILTERS {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-house-price',
  SURFACE = REAL_ESTATE_SURFACES_BY_TYPE.HOUSE,
  LOCATION = COMMON_FILTERS.LOCATION,
  EXTRAS = REAL_ESTATE_COMMON.EXTRAS,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
  ROOMS = REAL_ESTATE_COMMON.ROOMS,
  BATHROOMS = REAL_ESTATE_COMMON.BATHROOMS,
}

export enum REAL_ESTATE_RENT_FLAT_FILTERS {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-flat-price',
  SURFACE = REAL_ESTATE_SURFACES_BY_TYPE.FLAT,
  LOCATION = COMMON_FILTERS.LOCATION,
  EXTRAS = REAL_ESTATE_COMMON.EXTRAS,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
  ROOMS = REAL_ESTATE_COMMON.ROOMS,
  BATHROOMS = REAL_ESTATE_COMMON.BATHROOMS,
}

export enum REAL_ESTATE_RENT_ROOM_FILTERS {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-room-price',
  SURFACE = REAL_ESTATE_SURFACES_BY_TYPE.ROOM,
  LOCATION = COMMON_FILTERS.LOCATION,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_OFFICE_FILTERS {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-office-price',
  SURFACE = REAL_ESTATE_SURFACES_BY_TYPE.OFFICE,
  LOCATION = COMMON_FILTERS.LOCATION,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_GARAGE_FILTERS {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-garage-price',
  LOCATION = COMMON_FILTERS.LOCATION,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_LAND_FILTERS {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-land-price',
  SURFACE = REAL_ESTATE_SURFACES_BY_TYPE.LAND,
  LOCATION = COMMON_FILTERS.LOCATION,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_BOX_ROOM {
  OPERATION = REAL_ESTATE_COMMON.OPERATION,
  TYPE = REAL_ESTATE_COMMON.TYPE,
  PRICE = 'real_estate-rent-box_room-price',
  SURFACE = REAL_ESTATE_SURFACES_BY_TYPE.ROOM,
  LOCATION = COMMON_FILTERS.LOCATION,
  CONDITION = REAL_ESTATE_COMMON.CONDITION,
  POSTED_BEFORE = COMMON_FILTERS.POSTED_BEFORE,
}
