import { REAL_ESTATE_CONFIGURATION_ID } from '../../configuration-ids/real-estate-configuration-ids.enum';
import { COMMON_CONFIGURATION_ID } from '../../configuration-ids/common-configuration-ids.enum';

export enum REAL_ESTATE_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.DEFAULT_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
}
