import { REAL_ESTATE_CONFIGURATION_ID } from '../../configuration-ids/real-estate-configuration-ids.enum';
import { COMMON_CONFIGURATION_ID } from '../../configuration-ids/common-configuration-ids.enum';

export enum REAL_ESTATE_BUY_DEFAULT_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.BUY_DEFAULT_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_BUY_HOUSE_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.BUY_HOUSE_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.HOUSE_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  EXTRAS = REAL_ESTATE_CONFIGURATION_ID.EXTRAS,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
  ROOMS = REAL_ESTATE_CONFIGURATION_ID.ROOMS,
  BATHROOMS = REAL_ESTATE_CONFIGURATION_ID.BATHROOMS,
}

export enum REAL_ESTATE_BUY_FLAT_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.BUY_FLAT_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.FLAT_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  EXTRAS = REAL_ESTATE_CONFIGURATION_ID.EXTRAS,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
  ROOMS = REAL_ESTATE_CONFIGURATION_ID.ROOMS,
  BATHROOMS = REAL_ESTATE_CONFIGURATION_ID.BATHROOMS,
}

export enum REAL_ESTATE_BUY_OFFICE_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.BUY_OFFICE_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.OFFICE_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_BUY_GARAGE_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.BUY_GARAGE_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_BUY_LAND_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.BUY_LAND_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.LAND_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_BUY_BOX_ROOM_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.BUY_BOX_ROOM_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.BOX_ROOM_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}
