import { REAL_ESTATE_CONFIGURATION_ID } from '../../configuration-ids/real-estate-configuration-ids.enum';
import { COMMON_CONFIGURATION_ID } from '../../configuration-ids/common-configuration-ids.enum';

export enum REAL_ESTATE_RENT_DEFAULT_FILTERS {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_DEFAULT_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_HOUSE_FILTERS {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_HOUSE_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.HOUSE_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  EXTRAS = REAL_ESTATE_CONFIGURATION_ID.EXTRAS,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
  ROOMS = REAL_ESTATE_CONFIGURATION_ID.ROOMS,
  BATHROOMS = REAL_ESTATE_CONFIGURATION_ID.BATHROOMS,
}

export enum REAL_ESTATE_RENT_FLAT_FILTERS {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_FLAT_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.FLAT_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  EXTRAS = REAL_ESTATE_CONFIGURATION_ID.EXTRAS,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
  ROOMS = REAL_ESTATE_CONFIGURATION_ID.ROOMS,
  BATHROOMS = REAL_ESTATE_CONFIGURATION_ID.BATHROOMS,
}

export enum REAL_ESTATE_RENT_ROOM_FILTERS {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_ROOM_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.ROOM_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_OFFICE_FILTERS {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_OFFICE_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.OFFICE_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_GARAGE_FILTERS {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_GARAGE_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_LAND_FILTERS {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_LAND_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.LAND_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
}

export enum REAL_ESTATE_RENT_BOX_ROOM {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_BOX_ROOM_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.ROOM_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_BEFORE = COMMON_CONFIGURATION_ID.POSTED_BEFORE,
}
