import { REAL_ESTATE_CONFIGURATION_ID } from '../../configuration-ids/real-estate-configuration-ids.enum';
import { COMMON_CONFIGURATION_ID } from '../../configuration-ids/common-configuration-ids.enum';

export enum REAL_ESTATE_FILTER_ID {
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.DEFAULT_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
}

export enum REAL_ESTATE_HOUSE_FILTER_ID {
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_HOUSE_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.HOUSE_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  EXTRAS = REAL_ESTATE_CONFIGURATION_ID.EXTRAS,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
  ROOMS = REAL_ESTATE_CONFIGURATION_ID.ROOMS,
  BATHROOMS = REAL_ESTATE_CONFIGURATION_ID.BATHROOMS,
}

export enum REAL_ESTATE_APARTMENT_FILTER_ID {
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_FLAT_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.FLAT_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  EXTRAS = REAL_ESTATE_CONFIGURATION_ID.EXTRAS,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
  ROOMS = REAL_ESTATE_CONFIGURATION_ID.ROOMS,
  BATHROOMS = REAL_ESTATE_CONFIGURATION_ID.BATHROOMS,
}

export enum REAL_ESTATE_ROOM_FILTER_ID {
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_ROOM_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_OFFICE_FILTER_ID {
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_OFFICE_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.OFFICE_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_GARAGE_FILTER_ID {
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_GARAGE_PRICE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_LAND_FILTER_ID {
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_LAND_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.LAND_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}

export enum REAL_ESTATE_BOX_ROOM_FILTER_ID {
  CATEGORIES = COMMON_CONFIGURATION_ID.CATEGORIES,
  OPERATION = REAL_ESTATE_CONFIGURATION_ID.OPERATION,
  TYPE = REAL_ESTATE_CONFIGURATION_ID.TYPE,
  PRICE = REAL_ESTATE_CONFIGURATION_ID.RENT_BOX_ROOM_PRICE,
  SURFACE = REAL_ESTATE_CONFIGURATION_ID.BOX_ROOM_SURFACE,
  LOCATION = COMMON_CONFIGURATION_ID.LOCATION,
  CONDITION = REAL_ESTATE_CONFIGURATION_ID.CONDITION,
  POSTED_AGO = COMMON_CONFIGURATION_ID.POSTED_AGO,
}
