export enum BUY_REQUEST_ERROR_CODES {
  NO_ADDRESS_FOR_USER = 'user does not have address',
  NO_CARRIER_OFFICE_ADDRESS_FOR_USER = 'user does not have a carrier office address',
  ALREADY_IN_PROGRESS_TRANSACTION = 'already in progress transaction',
  DUPLICATED_REQUEST = 'duplicated request',
  NON_PURCHASABLE_ITEM = 'non purchasable item',
  BLOCKED_SELLER = 'seller blocked by buyer',
  BLOCKED_BUYER = 'buyer blocked by seller',
  USER_HAS_NO_CARD = 'invalid card',
  CURRENCY_NOT_ACCEPTED = 'currency not accepted',
  MAX_REQUEST_NUMBER_EXCEEDED = 'transaction number exceeded',
  ALREADY_USED_PROMOCODE = 'promocode already used',
  EXPIRED_PROMOCODE = 'promocode expired',
  ITEM_CATEGORY_DIFFERENT_TO_PROMOCODE_ITEM_CATEGORY = 'item category different to promocode item category',
  ITEM_MAX_WEIGHT_GREATER_THAN_PROMOCODE_MAX_WEIGHT = 'item max weight greater than promocode max weight',
  ITEM_PRICE_SMALLER_THAN_PROMOCODE_MIN_PRICE = 'item price smaller than promocode min price',
  NOT_ACTIVE_YET_PROMOCODE = 'promocode not active yet',
  NOT_EXISTING_PROMOCODE = 'promocode does not exist',
  POSTAL_CODE_TEMPORARILY_RESTRICTED = 'código postal temporalmente restringido',
  NOT_SHIPPABLE_ITEM = 'not shippable item',
  INTERNATIONAL_SHIPPING_NOT_ENABLED_FOR_USER = 'international shipping is not enabled for user',
  CARRIER_OFFICE_ADDRESS_AND_HOME_ADDRESS_COUNTRIES_DO_NOT_MATCH = `carrier office address and home address countries don't match`,
}
