/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Seller accepts P2P payment offer
 */
export interface AcceptP2PPayment {
  /**
   * Identifier of the wallet screen
   */
  screenId: 299;
  /**
   * Payment amount of the offer
   */
  paymentAmount: number;
  /**
   * Payment amount of the offer
   */
  buyerUserId: string;
  /**
   * Payment amount of the offer
   */
  itemId: string;
}
