/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event triggered by the MGM host when the guest has successfully listed an item in the required time and the host has achieved the reward
 */
export interface AchieveMGMHostReward {
  /**
   * The name of the guest that has accepted the invitation. The format should be like Adrian R.
   */
  MGMguestName: string;
  /**
   * Identifier of the guest that has accepted the invitation
   */
  MGMguestUserId: string;
  /**
   * The unique identifier of the reward achieve
   */
  rewardId?: string;
}
