/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The user activates shipping in CG outside item edit pencil option
 */
export interface ActivateShippingItemCG {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the screen that the item was activate from
   */
  screenId: 303;
  /**
   * If the item has the weight informed
   */
  shippingWeight: number;
  /**
   * If the item has a preselected weight informed
   */
  preselectedItemWeight?: number;
}
