/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users chooses one of the 5 options in the feedback for the wall recommendation slider product
 */
export interface AnswerWallRecommendationFeedback {
  /**
   * Identifier of the screen where the user has given the wall recommendation slider feedback
   */
  screenId: 267;
  /**
   * Identifier of the feedback value given by the user, 1 as the lowest and 5 the highest
   */
  feedbackValue: 1 | 2 | 3 | 4 | 5;
  /**
   * Name of the experiment or A/B testing applied to the user who has given feedback. The default value would be 'baseline'
   */
  experiment?: string;
  /**
   * The unique identifier of the browsing
   */
  searchId?: string;
}
