/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User begins a subscription
 */
export interface BeginSubscription {
  /**
   * Subscription type
   */
  subscription: 0 | 100 | 200 | 14000 | 12800;
  /**
   * Identifier of the subscription tier
   */
  tier?: string;
}
