/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users perform a browse. A browse can be a search with only the category filter applied or a visit to the home page
 */
export interface Browse {
  /**
   * Identifier of the category that has been filtered in the browsing
   */
  categoryId?: number;
  /**
   * Identifier of the subcategory that has been filtered in the browsing
   */
  objectTypeId?: string;
  /**
   * The unique identifier of the browsing
   */
  searchId: string;
  /**
   * The unique identifier of the saved search
   */
  savedSearchId?: string;
  /**
   * Name of the experiment or A/B testing applied to the user who has performed the browsing. The default value would be 'baseline'
   */
  experiment?: string;
  /**
   * The source from which the browsing comes. The sources for the app clients can be: home, quickfilters, stored_filters, category_slider and default_filters. The sources for web can be: home (all categories), quickfilters, seo_category_slider, seo_sitemap and seo_home
   */
  source:
    | 'home'
    | 'quick_filters'
    | 'stored_filters'
    | 'category_slider'
    | 'default_filters'
    | 'seo_category_slider'
    | 'seo_home'
    | 'seo_sitemap'
    | 'item_detail'
    | 'subcategory_slider';
  /**
   * Identifier of the screen where the browsing has been done
   */
  screenId: 110 | 111 | 193;
  /**
   * Latitude of the performed browse
   */
  latitude: number;
  /**
   * Latitude of the performed browse
   */
  longitude: number;
  /**
   * The distance in km from the location where the browsing is performed and the location of the first item returned in the browse results
   */
  firstItemDistance: number;
  /**
   * Order criteria in which the results of the browsing are shown
   */
  orderBy: 'distance' | 'price_low_to_high' | 'price_high_to_low' | 'newest' | 'most_relevant';
  /**
   * Other properties sent by JSON format, ONLY FOR A/B TESTING PURPOSE
   */
  otherProperties?: string;
}
