/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The event is sent when apps receive the user info and item info.
 */
export interface BumpFlowEntryInfo {
  /**
   * If the item is from a professional user
   */
  isPro: boolean;
  /**
   * If the user has subscriptions bumps
   */
  hasSubscriptionBumps: boolean;
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * The source from which visibilty entry point comes the user
   */
  source: 'item_detail' | 'list_item' | 'reactivate_item' | 'my_catalog' | 'my_profile' | 'slider';
  /**
   * Identifier of the last screen the user have seen
   */
  screenId: number;
}
