/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users changes the email and saves the changes
 */
export interface ChangeEmail {
  /**
   * Identifier of the screen where the user was changing the email
   */
  screenId: 263;
}
