/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the subscribe button
 */
export interface ClickProfileSubscribeButton {
  /**
   * Identifier of the screen
   */
  screenId: 205;
  /**
   * Subscription type
   */
  subscription: 0 | 100 | 14000 | 12800;
}
