/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User selects a buyer to mark an item as sold
 */
export interface ClickSelectBuyer {
  /**
   * Identifier of the payment amount screen
   */
  screenId: 289;
  /**
   * Hashed Identifier of the item
   */
  itemId: string;
  /**
   * Hashed Identifier of the user the seller selects as the buyer
   */
  buyerUserId: string;
}
