/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users accepts updating the app version from the popup
 */
export interface ClickUpdateAppVersion {
  /**
   * Identifier of the popup screen where the has clicked to accept updating the app version
   */
  screenId: 265 | 266;
}
