/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The event is sent when the pro lister click on buy extra bump
 */
export interface ClickBuyExtraBump {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the last screen the user have seen.
   */
  screenId?: 319;
}
