/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PRO users clicks on the additional services save button in App
 */
export interface ClickConfirmAdditionalServicesUpload {
  /**
   * Identifier of the category clicked
   */
  categoryId: number;
  /**
   * Identifier of the upload screen
   */
  screenId: 41;
  /**
   * If the installation switch is on
   */
  installation?: boolean;
  /**
   * If the configuration switch is on
   */
  configuration?: boolean;
  /**
   * If the warranty switch is on
   */
  warranty?: boolean;
}
