/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users click on item card displayed in different screens
 */
export interface ClickItemCard {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Index of the item displayed in the screen
   */
  position: number;
  /**
   * The unique identifier of the search that the click is under
   */
  searchId?: string;
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId: 110 | 111 | 29 | 187 | 188 | 140 | 190 | 194;
  /**
   * If the item clicked is from a professional user
   */
  isPro?: boolean;
  /**
   * Item price
   */
  salePrice: number;
  /**
   * Item title
   */
  title: string;
  /**
   * Identifier of the source item for which recommendations have been given
   */
  itemSourceRecommendationId?: string;
  /**
   * The distance in km from the location where the search is performed and the location of the item clicked
   */
  itemDistance?: number;
  /**
   * If the listing has shipping allowed
   */
  shippingAllowed?: boolean;
}
