/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks back button without editing card in Edit Card screen
 */
export interface ClickBackEditCard {
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 220;
}
