/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the button to resend the verification in order to complete the register process
 */
export interface ClickRegisterResendVerification {
  /**
   * The email address the user has introduced to verify the register process
   */
  emailAddress: string;
  /**
   * Identifier of the register verification screen
   */
  screenId: 222;
}
