/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * After subscription selection click in the done button
 */
export interface ClickDoneSubscriptionPlan {
  /**
   * Identifier of the screen
   */
  screenId: 191;
  /**
   * Tier of the subscription
   */
  tier?: number;
}
