/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the Buy button
 */
export interface ClickBuy {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * The unique identifier of the search that the click is under
   */
  searchId?: string;
  /**
   * Identifier of the screen that the button was clicked from
   */
  screenId: 27 | 115;
  /**
   * If the item is from a professional user
   */
  isPro?: boolean;
  /**
   * Item price without fees
   */
  itemPrice: number;
}
