/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on a CTA or banner that takes them to the PRO landing page
 */
export interface ClickProInfo {
  /**
   * Identifier of the screen in which the user has clicked
   */
  screenId: 216;
  /**
   * Location of the CTA or the banner where the user clicks
   */
  clickLocation: 'banner_navigation_bar' | 'awareness_module' | 'footer';
  /**
   * Experiment group of the user
   */
  experiment?: string;
}
