/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the bump button after selecting the items in the catalog management
 */
export interface ClickBumpItems {
  /**
   * If the item clicked is from a professional user
   */
  isPro: boolean;
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId: number;
  /**
   * Number of items selected in the catalog management
   */
  itemsSelected?: number;
  /**
   * If the item clicked is from the upload popup
   */
  uploadPopUp?: boolean;
}
