/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users click to see the register help center after viewing the verification screen
 */
export interface ClickRegisterHelpCenter {
  /**
   * Identifier of the screen of the register help center
   */
  screenId: 223;
}
