/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on 'Transfer to bank account' button in wallet
 */
export interface ClickTransferBankAccount {
  /**
   * Identifier of the main wallet screen
   */
  screenId: 235;
  /**
   * Balance amount in the wallet
   */
  balanceAmount: number;
}
