/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to access wallet
 */
export interface ClickWallet {
  /**
   * Identifier of the screen from where the user clicks to access
   */
  screenId: 27 | 205 | 233;
}
