/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Button continue with the payment after selecting tier
 */
export interface ClickContinuePaymentSubscription {
  /**
   * Identifier of the screen
   */
  screenId: 206;
  /**
   * Stripe id of the tier of the subscription
   */
  tier?: string;
}
