/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on ebay shopping ad
 */
export interface ClickEbayShoppingAd {
  /**
   * Identifier of the category where the ad is shown
   */
  categoryId?: string;
  /**
   * Position where the ad is displayed
   */
  position?: number;
  /**
   * Identifier of the screen that the ad was clicked from
   */
  screenId: 111 | 114 | 115;
}
