/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks edit password in verifications and security screen
 */
export interface ClickEditPassword {
  /**
   * If the user has email verified
   */
  emailVerified?: boolean;
  /**
   * Identifier of verifications and security screen
   */
  screenId: 248;
}
