/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to access their bank details (bank card, account etc)
 */
export interface ClickBankDetails {
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 235;
  /**
   * Status of the KYC verification
   */
  kycStatus?: 'verified' | 'pending' | 'inProgress';
}
