/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on timeline cancel transaction button
 */
export interface ClickCancelTransaction {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the user interested in the item
   */
  buyerUserId: string;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId: string;
  /**
   * Identifier of the transaction request
   */
  requestId: string;
  /**
   * Identifier of the category that the transaction item belongs to
   */
  categoryId: number;
  /**
   * If the item is from a professional user
   */
  isPro?: boolean;
  /**
   * Item total price
   */
  totalPrice: number;
  /**
   * Item offered price
   */
  offeredPrice: number;
  /**
   * Item price without fees
   */
  itemPrice: number;
  /**
   * Item title
   */
  title: string;
  /**
   * Identifier of the accept offer screen
   */
  screenId: 205;
  /**
   * Method select by seller for drop off
   */
  sellerDropOffMethod: "Correos" | "HPU";
}
