/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * PRO users clicks on the warranty button in the additional services section
 */
export interface ClickWarrantyAdditionalServicesUpload {
  /**
   * Identifier of the category clicked
   */
  categoryId: number;
  /**
   * Identifier of the upload screen
   */
  screenId: 41;
  /**
   * If the switch is on
   */
  switchOn: boolean;
}
