/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the Subscription Managment Plus
 */
export interface ClickSubscriptionManagementPlusButton {
  /**
   * Identifier of the screen
   */
  screenId: 191;
  /**
   * Subscription type
   */
  subscription: 0 | 100 | 14000 | 12800;
  /**
   * If the user is a new subscriber
   */
  isNewSubscriber: boolean;
}
