/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Click to go to inform weight screen
 */
export interface ClickInformWeight {
  /**
   * The unique identifier for an item
   */
  itemId?: string;
  /**
   * Identifier of the screen that the button was clicked from
   */
  screenId: 302 | 316;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId: string;
}
