/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on Reserve button
 */
export interface ClickReserveItem {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the transaction item belongs to
   */
  categoryId: number;
  /**
   * Listing price of the item
   */
  itemPrice: number;
  /**
   * Item title
   */
  itemTitle: string;
  /**
   * Identifier of the accept offer screen
   */
  screenId: 115;
}
