/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the Catalog Management button
 */
export interface ClickCatalogManagement {
  /**
   * Identifier of the User Catalog screen
   */
  screenId: 219 | 112;
}
