/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on 'Activate' on inactive items
 */
export interface ClickActivateProItem {
  /**
   * Identifier of the screen where the user clicks on activate
   */
  screenId: 112 | 114 | 219 | 240;
  /**
   * Number of items that the user wants to activate
   */
  numberOfItems?: number;
  /**
   * Category id of the item to activate, in case of bulk activate not sent
   */
  categoryId?: number;
}
