/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on an item to select it
 */
export interface ClickSelectP2PItem {
  /**
   * Identifier of the item selection screen
   */
  screenId: 287;
  /**
   * Hashed identifier of the item the user selects for payment
   */
  itemId: string;
}
