/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks subscribe button or card on the subcription page
 */
export interface ClickProfileSubscribeButton {
  /**
   * Subscription category type
   */
  subscription: 0 | 100 | 14000 | 12800;
  /**
   * If the user is a new or recurrent subscriber
   */
  isNewSubscriber: boolean;
  /**
   * Identifier of the subscription page screen
   */
  screenId: 206;
}
