/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User confirms amount for p2p payment
 */
export interface ClickSelectP2PPaymentAmount {
  /**
   * Identifier of the payment amount screen
   */
  screenId: 276;
  /**
   * Balance amount in the wallet
   */
  walletBalanceAmount: number;
  /**
   * Amount that the user wants to pay to the seller
   */
  paymentAmount: number;
}
