/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on ad banner
 */
export interface ClickAdBanner {
  /**
   * Identifier of the category where the ad is shown
   */
  categoryId?: string;
  /**
   * The unique identifier for an item
   */
  itemId?: string;
  /**
   * Identifier of the campaign that the ad belongs to
   */
  lineitemId: string;
  /**
   * Identifier of the screen that the ad was showed from
   */
  screenId: 115 | 226;
}
