/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users click on user profile of another user displayed in different screens
 */
export interface ClickOtherProfile {
  /**
   * Identifier of the screen that the user profile was clicked from
   */
  screenId: 115 | 27 | 188 | 214 | 215;
  /**
   * If the user clicked is from a professional user
   */
  isPro?: boolean;
  /**
   * Identifier of the user that is clicked
   */
  sellerUserId: string;
}
