/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to continue with the 3DS flow
 */
export interface ClickContinue3DS {
  /**
   * Identifier of the 3DS popup screen
   */
  screenId: 283;
  /**
   * Hashed Id of the item of the shipping request
   */
  itemId?: string;
  /**
   * True if user checks the box that it should not be shown again
   */
  doNotShowAgain: boolean;
}
