/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A user clicks to Accept the update in Terms and Communications Consent
 */
export interface ClickAcceptTermsAndCommunications {
  /**
   * Identifier of the screen
   */
  screenId: 326;
  /**
   * If the user has given consent for communications
   */
  communicationsConsent: boolean;
}
