/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Buyer clicks on the chat button to start a conversation
 */
export interface ClickChatButton {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId: string;
  /**
   * The unique identifier of the search that the chat is under
   */
  searchId?: string;
  /**
   * If the chat button item is from a professional user
   */
  isPro?: boolean;
  /**
   * If the chat button item is a bumped item
   */
  isBumped?: boolean;
  /**
   * Identifier of the screen from which the message was sent from
   */
  screenId: 115;
  /**
   * When the event is triggered in SavedSearchesNewVsOld screen (217), specify if it is in the 'new' results or 'old'
   */
  savedSearchResults?: string;
  /**
   * Button clicked on the Item Detail
   */
  source?: 'primary' | 'secondary';
  /**
   * If the item has the shipping toggle ON and a shipping weight informed
   */
  shippingAllowed: boolean;
}
