/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on Subscribe button after selecting a subscription plan
 */
export interface ClickSubscriptionSubscribe {
  /**
   * Identifier of the subscription plan chosen by user
   */
  planId: string;
  /**
   * Identifier of the Subscription screen
   */
  screenId: 207;
}
