/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Potential Cars PRO clicks on Subscribe Button after selecting a car subscription plan
 */
export interface ClickCarsSubscriptionSubscribeButton {
  /**
   * Identifier of the Car subscription plan chosen by user
   */
  planId: string;
  /**
   * Identifier of the Cars subscription screen
   */
  screenId: 207;
}
