/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks an action button or information button on a transactional timeline screen
 */
export interface ClickActionTappedTransactionalTimeline {
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 205;
  /**
   * Identifier of the transaction request
   */
  requestId: string;
  /**
   * Name of the button or screen that the user is clicking on
   */
  actionName: 'Help General Doubts' | 'Help Packet On Hold' | 'Help Packet Delivered' | 'Tracer';
}
