/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks subscription button on the limit reached screen
 */
export interface ClickSubscriptionLimitReached {
  /**
   * Identifier of the My Catalog screen
   */
  screenId: 219;
}
