/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users clicks on item icon in wallet movements history
 */
export interface ClickItemWalletMovements {
  /**
   * Identifier of the screen the item was clicked on
   */
  screenId: 254 | 255 | 256;
}
