/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Seller clicks on Activate Shipping
 */
export interface ClickActivateShipping {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * The unique identifier of the search that the click is under
   */
  searchId?: string;
  /**
   * Identifier of the screen where the button was clicked
   */
  screenId: 27 | 115;
  /**
   * If the item is from a professional user
   */
  isPro?: boolean;
  /**
   * Item price without fees
   */
  itemPrice: number;
}
