/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to access a Frequently Asked Question about shipping transactions
 */
export interface ClickFAQTransactional {
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 317;
  /**
   * The FAQ the user clicks on
   */
  FAQ: 'get started' | 'protection' | 'shippable products' | 'dimensions and weight' | 'packaging' | 'HPU';
}
