/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users clicks on the subcategory when uploading an item
 */
export interface ClickItemSubcategoryFieldUpload {
  /**
   * Identifier of the category
   */
  categoryId?: number;
  /**
   * Identifier of the upload screen
   */
  screenId: 41;
}
