/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users clicks to view the MGM info in the MGM Host Section
 */
export interface ClickMGMHostInfo {
  /**
   * Identifier of the screen where the user clicked to see more MGM Info
   */
  screenId: 293;
}
