/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the edit price button in the chat screen
 */
export interface ClickEditItemPrice {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Item price without fees
   */
  itemPrice: number;
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 27;
}
