/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on Subscribe button after selecting a subscription plan
 */
export interface ClickSubscriptionSubscribe {
  /**
   * Subscription category type that reached the limit
   */
  subscription: 0 | 100 | 200 | 14000 | 12800;
  /**
   * Identifier of the tier choosen
   */
  tier?: string;
  /**
   * Price of the subscription and tier choosen (if tier N/A, price of the plan)
   */
  price: number;
  /**
   * Identifier of the Subscription screen
   */
  screenId: 207;
  /**
   * If the view offers discount or not
   */
  discount?: boolean;
  /**
   * Whether the subscription offers free trial
   */
  freeTrial?: boolean;
}
