/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on Receive button in the wallet screen
 */
export interface ClickP2PReceivePayment {
  /**
   * Identifier of the wallet screen
   */
  screenId: 235;
  /**
   * Balance of the wallet
   */
  walletBalanceAmount: number;
}
