/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the bump confirmation button after selecting bump type and days
 */
export interface ClickBumpConfirmation {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * If the item clicked is from a professional user
   */
  isPro?: boolean;
  /**
   * If is a bump from a subscription package
   */
  isSubscriptionBump?: boolean;
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId?: 213 | 318 | 319;
}
