/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on an onboarding intention option
 */
export interface ClickOnboardingIntentionOption {
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 296;
  /**
   * Onboarding intention option
   */
  option: 'Buyer' | 'Seller' | 'Not Sure';
}
