/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks start verification button on KYC tutorial screen
 */
export interface ClickKYCStartVerification {
  /**
   * Identifier of the user closing KYC tutorial screen
   */
  userId?: string;
  /**
   * Identifier of the KYC tutorial screen
   */
  screenId: 196;
}
