/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks the subscribe button on the Subscription Benefits screen
 */
export interface ClickSubscriptionBenefits {
  /**
   * Identifier of the Subscription Benefits Screen
   */
  screenId: 192;
}
