/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on one of the affiliation partner buttons to visit their website
 */
export interface ClickAffiliationPartner {
  /**
   * Identifier of the partner that the user has clicked
   */
  partnerName: string;
  /**
   * Url of the landing where the affiliation partner button was clicked
   */
  landingUrl: string;
  /**
   * The unique identifier of the item where the affiliation button was clicked
   */
  itemId?: string;
  /**
   * Identifier of the category where the affiliation button was clicked
   */
  categoryId?: string;
  /**
   * Identifier of the screen that the affiliation button partner was showed from
   */
  screenId?: 115 | 258;
  /**
   * Name of the experiment or A/B testing applied to the user who click the affiliation partner button. The default value would be 'baseline'
   */
  experiment?: string;
  /**
   * The type of affiliation service
   */
  typeOfService?: 'Insurance' | 'Loan' | 'Mortgage' | 'Guaranty' | 'Internet' | 'Energy' | 'Other';
}
