/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the PRO subscription button or banner
 */
export interface ClickProSubscription {
  /**
   * If the view offers free trial or not
   */
  freeTrial?: boolean;
  /**
   * If the view offers discount or not
   */
  discount?: boolean;
  /**
   * Identifier of the screen in which the user has clicked
   */
  screenId: 111 | 112 | 216 | 219 | 233;
  /**
   * Whether the user is logged in
   */
  isLoggedIn?: boolean;
  /**
   * Whether the user is a PRO
   */
  isPro?: boolean;
}
