/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on Continue on the Reserve Item info screen
 */
export interface ClickContinueReserveInfo {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the accept offer screen
   */
  screenId: 259;
}
