/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users clicks to share the a link to invite a guest in the Member Get Member program
 */
export interface ClickShareMGMLink {
  /**
   * Identifier of the screen that the link was shared from
   */
  screenId: 293;
  /**
   * MGM code that the user has shared
   */
  referralCode: string;
}
