/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Button to confirm the unsuscribe
 */
export interface ClickUnsuscribeConfirmation {
  /**
   * Identifier of the screen
   */
  screenId: 206;
}
