/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to choose a subscription from the subscription list
 */
export interface ClickSubscriptionManagementPlus {
  /**
   * Identifier of the Subscription screen
   */
  screenId: 191;
  /**
   * Subscription type
   */
  subscription: 0 | 100 | 200 | 14000 | 12800;
  /**
   * If the user is a new subscriber
   */
  isNewSubscriber: boolean;
  /**
   * Whether the subscription clicked offers free trial
   */
  freeTrial?: boolean;
}
