/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to mark the item as sold
 */
export interface ClickMarkItemSold {
  /**
   * Hashed id of the item the user wants to mark as sold
   */
  itemId: string;
  /**
   * Identifier of the page where the user starts the mark as sold flow
   */
  screenId: 114;
}
