/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to Resend the email on the Login Verification Sent screen
 */
export interface ClickResendLoginVerification {
  /**
   * Identifier of the Login Verification Sent screen
   */
  screenId: 284;
}
