/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User selects timeframe to reserve item
 */
export interface ClickSelectReserveTimeframe {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Selected Timeframe
   */
  timeframe: '1 day' | '3 days' | '5 days';
  /**
   * Identifier of the accept offer screen
   */
  screenId: 260;
}
