/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User selects a method to add an image of their document
 */
export interface ClickKYCSelectImageMethod {
  /**
   * Identifier of the KYC tutorial screen
   */
  screenId: 304;
  /**
   * Whether the user chooses to upload or take a new picture with the webcam
   */
  method?: 'upload' | 'camera';
}
