/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users click on shipping allowed
 */
export interface ClickReactivationShippingAllowed {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the screen id
   */
  screenId: 246;
}
