/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on View my wall on the activation flow for buyers
 */
export interface ClickViewMyWall {
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 297;
  /**
   * Categories selected by the user separated by comma
   */
  categories: string;
}
