/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the bump button at the end of the featured items slider on the Wall
 */
export interface ClickBumpFeaturedSliderWall {
  /**
   * If the user clicking is a professional user
   */
  isPro?: boolean;
  /**
   * Identifier of the screen that the bump button was clicked from
   */
  screenId: 110;
}
