/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User confirms payout to bank account after selecting the transfer amount
 */
export interface ConfirmTransferBankAccount {
  /**
   * Identifier of the screen for payout confirmation
   */
  screenId: 237;
  /**
   * Balance amount in the wallet
   */
  balanceAmount: number;
  /**
   * Amount that the user wants to transfer
   */
  transferAmount: number;
}
