/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User confirms to activate an item in a pro category
 */
export interface ConfirmActivateProItem {
  /**
   * Number of Items the user wants to activate
   */
  numberOfItems?: number;
  /**
   * Identifier of the inactive items section in catalog management
   */
  screenId: 219 | 240;
  /**
   * Category id of the item to activate, in case of bulk activate not sent
   */
  categoryId?: number;
}
