/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User confirms that they sold the item outside (no chats or confirms on the buyer list screen)
 */
export interface ConfirmItemSoldOutside {
  /**
   * Identifier of the confirmation screen
   */
  screenId: 114 | 289;
  /**
   * Hashed identifier of the item
   */
  itemId: string;
  /**
   * Identifier of the item category
   */
  categoryId: number;
  /**
   * Number of chat conversations the item has received
   */
  numberOfChatConversations: number;
  /**
   * Price of the item the user marks as sold
   */
  itemPrice: number;
}
