/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A conversation involving a Malicious user has been detected
 */
export interface DetectMaliciousUserConversation {
  /**
   * Identifier of the conversation
   */
  conversationId: string;
  /**
   * Identifier of the malicious user
   */
  maliciousUserId: string;
  /**
   * Identifier of the impacted user
   */
  impactedUserId: string;
  /**
   * Identifier of the item
   */
  itemId: string;
  /**
   * Item title
   */
  itemTitle: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId?: number;
}
