/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User edits an uploaded product (in consumer goods)
 */
export interface EditItemCG {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Item price
   */
  salePrice?: number;
  /**
   * Change in the sale price
   */
  salePriceChange: number;
  /**
   * Item title
   */
  title: string;
  /**
   * CG Brand
   */
  brand?: string;
  /**
   * CG Model
   */
  model?: string;
  /**
   * CG Object type name
   */
  objectType?: string;
  /**
   * If the item edited is from a professional user
   */
  isPro: boolean;
  /**
   * Identifier of the screen that the item was edited from
   */
  screenId: 162 | 115 | 292;
  /**
   * Hashtags
   */
  hashtags?: string;
  /**
   * shippingAllowed
   */
  shippingAllowed: boolean;
  /**
   * Change in the shipping toggle
   */
  shippingAllowedChange: -1 | 0 | 1;
  /**
   * If the item has the weight informed
   */
  shippingWeight?: number;
  /**
   * If the item has a preselected weight informed
   */
  preselectedItemWeight?: number;
  /**
   * Change in the shipping weight
   */
  shippingWeightChange?: number;
  /**
   * The source from which the edit item comes
   */
  source?: 'item_detail' | 'chat' | 'deeplink' | 'edit_screen' | 'reactivation_item';
}
