/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User scrolls the wall recommendation slider until the end
 */
export interface EndScrollWallRecommendationSlider {
  /**
   * The unique identifier of the browsing
   */
  searchId: string;
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId: 110;
  /**
   * Recommended categories in the wall recommendation slider separated by comma
   */
  categoriesInWallRecommendationSlider?: string;
  /**
   * Recommended subcategories in the wall recommendation slider separated by comma
   */
  subcategoriesInWallRecommendationSlider?: string;
}
