/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event triggered by the MGM host when the guest ran out of time to list an item and achieve the reward
 */
export interface ExpireMGMHostListingTime {
  /**
   * The name of the guest that has accepted the invitation. The format should be like Adrian R.
   */
  MGMguestName: string;
  /**
   * Identifier of the guest that has accepted the invitation
   */
  MGMguestUserId: string;
}
