/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * BE event when user favorites product
 */
export interface FavoriteItemWithDistance {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Distance between buyer and item/seller in km
   */
  buyerSellerDistance?: number;
  /**
   * Item title
   */
  title: string;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId: string;
  /**
   * Identifier of the user that the item belongs to
   */
  salePrice: number;
  /**
   * Whether the shipping toggle is activated for the item (buyer can send shipping request)
   */
  shippingAllowed: boolean;
}
