/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on Finish to send feedback
 */
export interface FinishReserveTest {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * All option numbers selected by the user, separated by commas in ascending order
   */
  reserveReason: string;
  /**
   * Identifier of the screen that the item was favorited from
   */
  screenId: 262;
}
