/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Collects consent status to user idfa as identifier
 */
export interface IDFAConsentStatus {
  /**
   * Status of the user's consent based on the response on the popup
   */
  consentStatus: 'notDetermined' | 'restricted' | 'denied' | 'authorized';
}
