/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views an impression of the Favorite/Saved Searches Tooltip
 */
export interface ImpressionFavoriteSearchesTooltip {
  /**
   * The unique identifier of the search where the impression is done
   */
  searchId: string;
  /**
   * Identifier of the screen
   */
  screenId: 111;
}
