/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views an impression of the Verification Banner
 */
export interface ImpressionVerificationBanner {
  /**
   * Identifier of the screen
   */
  screenId: 110;
  /**
   * Identifier of the verification done
   */
  verificationMethod: 'email';
  /**
   * Name of the experiment or A/B testing applied to the user who has performed the view. The default value would be 'baseline'
   */
  experiment?: string;
}
