/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User uploads or edits a RealEstate product location
 */
export interface ItemRELocation {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Item region
   */
  region: string;
  /**
   * Real State Operation
   */
  operation: string;
}
