/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User leaves review for a seller
 */
export interface LeaveReviewForSeller {
  /**
   * Identifier of the review screen to leave review for seller
   */
  screenId: 291;
  /**
   * Hashed identifier of the item that is marked as sold
   */
  itemId: string;
  /**
   * Hashed identifier of the seller
   */
  sellerUserId: string;
  /**
   * The item price on the listing
   */
  itemPrice: number;
  /**
   * Reviews score on a scale from 0 to 100. This is equivalent to the amount of stars * 20
   */
  reviewsScore: number;
  /**
   * Open text review for seller
   */
  reviewText?: string;
}
