/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User uploads a ConsumerGoods product
 */
export interface ListItemCG {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Identifier of the subcategory that the item belongs to
   */
  subcategoryId?: number;
  /**
   * Item price
   */
  salePrice?: number;
  /**
   * Item title
   */
  title: string;
  /**
   * CG Brand
   */
  brand?: string;
  /**
   * CG Model
   */
  model?: string;
  /**
   * CG Object type name
   */
  objectType?: string;
  /**
   * If the item clicked is from a professional user
   */
  isPro: boolean;
  /**
   * Identifier of the screen that the item was uploaded from
   */
  screenId: number;
  /**
   * Hashtags
   */
  hashtags?: string;
  /**
   * shippingAllowed
   */
  shippingAllowed?: boolean;
  /**
   * If the item has the weight informed
   */
  shippingWeight?: number;
  /**
   * Country of the user (seller) that lists the item (e.g.: ES, IT, etc.)
   */
  country?: string;
  /**
   * Language of the user (seller) that lists the item (e.g.: ES, IT, etc.)
   */
  language?: string;
}
