/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users successfully login with Apple
 */
export interface LoginAppleSuccess {
  /**
   * Identifier of the screen where the options to login or register appear
   */
  screenId: 177;
}
