/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event triggered by the MGM host or guest when there have been x days since the reward was achieved and has not been used
 */
export interface MGMRewardUnused {
  /**
   * The unique identifier of the reward unused
   */
  rewardId: string;
  /**
   * Number of days since the reward was achieved
   */
  daysUnused?: number;
}
