/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * View launched when the user joins the private web, default = my_catalog
 */
export interface OpenMyZone {
  /**
   * Whether the user is a PRO
   */
  isPro: boolean;
  /**
   * Identifier of the edit screen
   */
  screenId: 140;
}
