/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users start a session by opening the app or web
 */
export interface OpenWallapop {
  /**
   * Name of the experiment or A/B testing applied to the user who has opened the app or web. The default value would be 'baseline'
   */
  experiment?: string;
  /**
   * Url of the current page that the user is visiting. This attribute is only for web
   */
  currentUrl?: string;
  /**
   * Url from where the user has reached the current url. This attribute is only for web
   */
  refererUrl?: string;
  /**
   * Identifier of the category to which the item belongs to. This attribute is only for web
   */
  urlCategoryId?: number;
  /**
   * Identify the keywords of the landing seo. This attribute is only for web
   */
  urlKeyword?: string;
  /**
   * Whether the landing is an item page or not. This attribute is only for web
   */
  urlItem?: boolean;
  /**
   * Identifier the province of the landing seo. This attribute is only for web
   */
  urlProvince?: string;
  /**
   * Identify the city of the landing seo. This attribute is only for web
   */
  urlCity?: string;
  /**
   * Identifier of the opening screen. It app this is not informed because the event is triggered before knowing the opening screen. For web, it can take the value of any landing SEO screen
   */
  screenId?: 193 | 115 | 29 | 111 | 216 | 110;
  /**
   * Type of platform. This attribute is only for web
   */
  webPlatformType?: "desktop" | "tablet" | "mobile";
  /**
   * Identifier of the device. This attribute is only for web
   */
  webDeviceId?: string;
}
