/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the bump button before payment in the payment summary screen
 */
export interface PayBumpItems {
  /**
   * If the item clicked is from a professional user
   */
  isPro: boolean;
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId: number;
  /**
   * Number of total bumped items
   */
  bumps: number;
  /**
   * Number of total bumped items from a subscription package
   */
  subscriptionBumps?: number;
  /**
   * Number of zone bumped items
   */
  zoneBumps: number;
  /**
   * Number of city bumped items
   */
  cityBumps: number;
  /**
   * Number of country bumped items
   */
  countryBumps: number;
  /**
   * Total amount paid
   */
  amountPaid?: number;
}
