/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User scans QR Code or introduces manual code
 */
export interface PayP2P {
  /**
   * Identifier of the wallet screen
   */
  screenId: 279 | 282;
  /**
   * Amount the user wants to pay
   */
  paymentAmount: number;
}
