/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on the Pay button to pay for an item reservation
 */
export interface PayReserveItem {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Selected payment method
   */
  paymentMethod: "bank card" | "paypal";
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId: 261;
}
