/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users have successfully verified the account in the register process
 */
export interface RegisterVerificationSuccess {
  /**
   * The email address the user has verified
   */
  emailAddress: string;
  /**
   * Identifier of the register verification screen
   */
  screenId: 222;
}
