/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks to remove a promotional banner for subscriptions
 */
export interface RemoveProSubscriptionBanner {
  /**
   * Identifier of the screen where the banner is displayed
   */
  screenId: 219;
  /**
   * Whether the banner offers free trial
   */
  freeTrial?: boolean;
}
