/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users successfully reset the password and BE answers FE with a success
 */
export interface ResetPasswordSuccess {
  /**
   * Identifier of the screen where the user was reseting the password
   */
  screenId: 251;
  /**
   * Identifier to distinguish if the password change comes from the Account Take Over flow
   */
  source?: 'ATO' | 'other';
}
