/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User saves an address (either for delivery, hpu, return)
 */
export interface SaveAddress {
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 245;
}
