/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users perform a search in another user's profile
 */
export interface SearchInOtherProfile {
  /**
   * Identifier of the screen where the searching has been done
   */
  screenId: 29;
  /**
   * Identifier of the user profile
   */
  sellerUserId: string;
  /**
   * Keywords applied in the search
   */
  keywords: string;
}
