/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users perform a search
 */
export interface Search {
  /**
   * The unique identifier of the search
   */
  searchId: string;
  /**
   * The unique identifier of the saved search
   */
  savedSearchId?: string;
  /**
   * Name of the experiment or A/B testing applied to tgghe user who has performed the search. The default value would be 'baseline'
   */
  experiment?: string;
  /**
   * The source from which the searching comes. The sources for the app clients can be: search_box, recent_searches, quick_filters, stored_filters, category_slider and default_filters. The sources for web can be: search_box, default_filters, quick_filters, seo_section, seo_list, seo_location_list, seo_sitemap
   */
  source:
    | 'search_box'
    | 'recent_searches'
    | 'default_filters'
    | 'quick_filters'
    | 'stored_filters'
    | 'seo_section'
    | 'seo_list'
    | 'seo_location_list'
    | 'seo_sitemap'
    | 'item_detail';
  /**
   * Identifier of the screen where the searching has been done
   */
  screenId: 110 | 111 | 193 | 217;
  /**
   * Latitude of the performed search
   */
  latitude: number;
  /**
   * Latitude of the performed search
   */
  longitude: number;
  /**
   * The distance in km from the location where the search is performed and the location of the first item returned in the search results
   */
  firstItemDistance?: number;
  hasResults?: boolean;
  /**
   * Identifier of the category that has been filtered in the search
   */
  categoryId?: number;
  /**
   * Keywords applied in the search
   */
  keywords?: string;
  /**
   * Minimum price set as a filter in the search
   */
  minPrice?: number;
  /**
   * Maximum price set as a filter in the search
   */
  maxPrice?: number;
  /**
   * Distance in km set as a filter in the search
   */
  distance?: number;
  /**
   * Order criteria in which the results of the search are shown
   */
  orderBy: 'distance' | 'price_low_to_high' | 'price_high_to_low' | 'newest' | 'most_relevant';
  professional?: boolean;
  shipping?: boolean;
  exchange?: boolean;
  urgent?: boolean;
  timeFilter?: 'today' | 'lastWeek' | 'lastMonth';
  minKm?: number;
  maxKm?: number;
  minYear?: number;
  maxYear?: number;
  minNumSeats?: number;
  maxNumSeats?: number;
  bodyType?: string;
  warranty?: boolean;
  minHorsePower?: number;
  maxHorsePower?: number;
  minNumDoors?: number;
  maxNumDoors?: number;
  engine?: string;
  gearbox?: string;
  carBrand?: string;
  carModel?: string;
  operation?: 'buy' | 'rent';
  propertyType?: 'box_room' | 'apartment' | 'room' | 'garage' | 'office' | 'house' | 'land';
  minSurface?: number;
  maxSurface?: number;
  rooms?: number;
  bathrooms?: number;
  elevator?: boolean;
  terrace?: boolean;
  pool?: boolean;
  garden?: boolean;
  garage?: boolean;
  condition?: 'to_reform' | 'new_construction' | 'mint';
  objectTypeId?: string;
  brandModel?: string;
  size?: string;
  gender?: 'female' | 'male';
  /**
   * Item condition set as a filter in the search
   */
  itemCondition?: string;
  /**
   * Other properties sent by JSON format, ONLY FOR A/B TESTING PURPOSE
   */
  otherProperties?: string;
}
