/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users perform a search in another user's profile
 */
export interface SearchInOtherProfile {
  /**
   * Identifier of the screen where the searching has been done
   */
  screenId: 29;
  /**
   * Identifier of the user profile
   */
  sellerUserId: string;
  /**
   * Keywords applied in the search
   */
  keywords?: string;
  /**
   * Number of items the viewed user has on sale
   */
  numberOfItems?: number;
  /**
   * Identifier of the category that has been filtered in the search
   */
  categoryId?: number;
  /**
   * Minimum price set as a filter in the search
   */
  minPrice?: number;
  /**
   * Maximum price set as a filter in the search
   */
  maxPrice?: number;
  /**
   * Time of publication of the listing set as filter in the search
   */
  timeFilter?: 'today' | 'lastWeek' | 'lastMonth';
}
