/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User selects amount to transfer to bank account
 */
export interface SelectTransferAmount {
  /**
   * Identifier of the wallet payout screen
   */
  screenId: 236;
  /**
   * Balance amount in the wallet
   */
  balanceAmount: number;
  /**
   * Amount that the user wants to transfer
   */
  transferAmount: number;
}
