/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks on Send on TRACER screen
 */
export interface SendTracer {
  /**
   * Identifier of the TRACER screen
   */
  screenId: 268;
  /**
   * Identifier of the transaction Id
   */
  transactionId: string;
  /**
   * Rating of the total transactional experience - 1 = bad, 5 = excellent
   */
  coreScoreRating: number;
}
