/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * BE event when buyer sends first conversation message
 */
export interface SendFirstMessageWithDistance {
  /**
   * Distance between buyer and item/seller
   */
  buyerSellerDistance?: number;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Hashed identifier of the user that the item belongs to
   */
  sellerUserId: string;
  /**
   * Hashed identifier of the item
   */
  itemId: string;
  /**
   * Identifier of the conversation
   */
  conversationId: string;
  /**
   * Whether the shipping toggle is activated for the item (buyer can send shipping request)
   */
  shippingAllowed?: boolean;
}
