/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * System event triggered when a shipping is delivered to the buyer
 */
export interface ShippingDeliveredBuyer {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId: string;
  /**
   * Identifier of the shipping request
   */
  requestId: string;
  /**
   * Identifier of the transaction
   */
  transactionId?: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * Item price without fees
   */
  itemPrice?: number;
  /**
   * Item weight in kg
   */
  itemWeight?: number;
}
