/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users starts the verification process by clicking on send email, send sms or verify facebook profile
 */
export interface StartVerificationProcess {
  /**
   * Identifier of the screen of the register help center
   */
  screenId: 248 | 249 | 270;
  /**
   * Identifier of the verification done
   */
  verificationMethod: 'phone' | 'email' | 'facebook';
}
