/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User clicks the confirmation payment on the subcription web flow
 */
export interface SubscriptionPaymentFailed {
  /**
   * Subscription category type
   */
  subscription: 0 | 100 | 200 | 14000 | 12800;
  /**
   * Tier of the subscription
   */
  tier: string;
  /**
   * If the payment is to automatically renew an existing subscription
   */
  isRenewal: boolean;
  /**
   * Number of retries that have failed for the payment
   */
  retryNumber: number;
  /**
   * Error causing the payment to fail
   */
  error: string;
}
