/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User is allowed to click on the pay button in the subscription flow
 */
export interface SubscriptionPaymentButtonAvailable {
  /**
   * Subscription category type
   */
  subscription: 0 | 100 | 200 | 14000 | 12800;
  /**
   * Tier of the subscription
   */
  tier: string;
  /**
   * If the user needs the invoice
   */
  invoiceNeeded?: boolean;
  /**
   * Identifier of the screen
   */
  screenId: 206;
  /**
   * If the view offers discount or not
   */
  discount?: boolean;
  /**
   * Whether the subscription offers free trial
   */
  freeTrial?: boolean;
}
