/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users do a suspicious login
 */
export interface SuspiciousLogin {
  /**
   * Name of the experiment or A/B testing applied to the user who has done the suspicious login. The default value would be 'baseline'
   */
  experiment?: string;
}
