/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tap on login button
 */
export interface TapRegisterPresentationLogin {
  /**
   * Identifier of the screen that the user tap to the login
   */
  screenId: number;
}
