/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A buyer submits a TRACER survey
 */
export interface TracerResponseBuyer {
  /**
   * Identifier of the request Id
   */
  requestId: string;
  /**
   * Identifier of the transaction Id
   */
  transactionId: string;
  /**
   * Rating of the overall transactional experience - 1 = bad, 5 = excellent
   */
  coreScoreRating: number;
  /**
   * Rating of parcel tracking - 0 = bad, 1 = good
   */
  parcelTracking?: number;
  /**
   * Rating of payment tracking - 0 = bad, 1 = good
   */
  paymentTracking?: number;
  /**
   * Rating of condition of the parcel - 0 = bad, 1 = good
   */
  parcelPackaging?: number;
  /**
   * Rating of delivery time - 0 = bad, 1 = good
   */
  deliveryTime?: number;
  /**
   * Rating of customer support - 0 = bad, 1 = good
   */
  customerSupport?: number;
  /**
   * Rating of trust in the seller - 0 = bad, 1 = good
   */
  userTrust?: number;
  /**
   * Rating of help documentation - 0 = bad, 1 = good
   */
  helpInformation?: number;
  /**
   * Free text box for the user to leave feedback for improvement
   */
  openFeedback?: string;
}
