/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The transaction is successful and the seller receives the money in the wallet
 */
export interface TransactionPaymentSeller {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the shipping request
   */
  requestId: string;
  /**
   * Identifier of the transaction
   */
  transactionId: string;
  /**
   * Amount of the payment received in the wallet
   */
  paymentAmount: number;
  /**
   * Whether the seller should receive a tracer push
   */
  sendTracerPush: boolean;
}
