/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A shipping request is created and sent to the seller
 */
export interface TransactionRequestCreated {
  /**
   * The hashed ID for the buyer that sent the shipping request
   */
  buyerUserId: string;
  /**
   * Country of the buyer (ES/IT)
   */
  buyerCountry: string;
  /**
   * Country of the seller (ES/IT)
   */
  sellerCountry: string;
  /**
   * Item category
   */
  categoryId: number;
  /**
   * The unique identifier for an item
   */
  itemId: string;
}
