/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users unfavorites a search
 */
export interface UnfavoriteSearch {
  /**
   * The unique identifier of the favorite search
   */
  savedSearchId: string;
  /**
   * Identifier of the screen where the favorite search has been unfavorited
   */
  screenId: 323 | 110 | 111;
  /**
   * Latitude of the performed search
   */
  latitude?: number;
  /**
   * Latitude of the performed search
   */
  longitude?: number;
  /**
   * Identifier of the category that has been filtered in the favorite search
   */
  categoryId?: number;
  /**
   * Keywords applied in the favorite search
   */
  keywords?: string;
  /**
   * Minimum price set as a filter in the favorite search
   */
  minPrice?: number;
  /**
   * Maximum price set as a filter in the favorite search
   */
  maxPrice?: number;
  /**
   * Distance in km set as a filter in the favorite search
   */
  distance?: number;
  /**
   * Order criteria in which the results of the favorite search are shown
   */
  orderBy?: 'distance' | 'price_low_to_high' | 'price_high_to_low' | 'newest' | 'most_relevant';
  timeFilter?: 'today' | 'lastWeek' | 'lastMonth';
  /**
   * List of the subcategory ids that have been filtered in the favorite search, separated by comma
   */
  objectTypeId?: string;
  /**
   * Item condition set as a filter in the favorite search
   */
  itemCondition?: string;
}
