/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User changes the setting of the Promotions & new features notification
 */
export interface UpdatePromoNotification {
  /**
   * Identifier of the screen where the user can activate or deactivate different types of notifications
   */
  screenId: 320;
  /**
   * User's new setting on the notification, True if it is moved to Active and False otherwise
   */
  consent: boolean;
}
