/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Collects consent status to user commercial communications when asking for it for existing users with a pop-up
 */
export interface UpdateCommercialCommunicationsConsent {
  /**
   * User's consent based on the response on the popup
   */
  consent: boolean;
}
