/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * There is a problem or an error with the upload or edit item process
 */
export interface UploadItemError {
  /**
   * The unique identifier for an item
   */
  itemId?: string;
  /**
   * Short description of the error
   */
  errorType?: 'missing information';
  /**
   * Identifier of the checkout screen
   */
  screenId: 160 | 302 | 303;
  /**
   * Id of the item category
   */
  categoryId?: number;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId: string;
}
