/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users successfully verifies email, facebook or phone number
 */
export interface VerificationSuccess {
  /**
   * Identifier of the verification done
   */
  verificationMethod: "phone" | "email" | "facebook";
  /**
   * From where is the verification being done
   */
  verificationSource: "profile" | "register";
  /**
   * The email address the user has verified during register
   */
  emailAddress?: string;
}
