/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * View modal after unsuscribe success
 */
export interface ViewSuccessUnsubscription {
  /**
   * Identifier of the screen from which the message was sent from
   */
  screenId: 206;
}
