/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views transaction logistics screen
 */
export interface ViewTransactionLogisticsScreen {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Item price without fees
   */
  itemPrice: number;
  /**
   * Delivery and insurance fees
   */
  feesPrice?: number;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId: string;
  /**
   * Identifier of the screen where the click is done
   */
  screenId: 311;
  /**
   * Preselected delivery method
   */
  preselectedDeliveryMethod?: 'buyer address' | 'carrier office';
  /**
   * Country of the item/seller (e.g.: ES, IT, etc.) using 2-digit ISO Code
   */
  sellerCountry: string;
}
