/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Seller sees screen to select a buyer when marking an item as sold
 */
export interface ViewSelectBuyer {
  /**
   * Identifier of the Select Buyer Screen
   */
  screenId: 289;
  /**
   * Hashed Id of the item
   */
  itemId: string;
  /**
   * Number of chat conversations that the item received
   */
  numberOfChatConversations: number;
}
