/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the Account Deletion screen
 */
export interface ViewAccountDeletion {
  /**
   * Identifier of the Account Deletion screen
   */
  screenId: 314;
  /**
   * True if the user is a car dealer
   */
  isCarDealer: boolean;
  /**
   * True if the user is a professional user
   */
  isPro: boolean;
}
