/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * View other profile screen
 */
export interface ViewOtherProfile {
  /**
   * Identifier of the screen from which the message was sent from
   */
  screenId: 29;
  /**
   * If the user profile is a pro user
   */
  isPro: boolean;
  /**
   * Identifier of the user profile
   */
  sellerUserId: string;
  /**
   * Number of items the viewed user has on sale
   */
  numberOfItems?: number;
  /**
   * Name of the experiment or A/B testing applied to the user who has performed the view. The default value would be 'baseline'
   */
  experiment?: string;
}
