/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views transactional timeline screen
 */
export interface ViewTransactionalTimeline {
  /**
   * The unique identifier for an item
   */
  itemId?: string;
  /**
   * Identifier of the user interested in the item
   */
  buyerUserId?: string;
  /**
   * Identifier of the user that the item belongs to
   */
  sellerUserId?: string;
  /**
   * Identifier of the transaction request
   */
  requestId: string;
  /**
   * Identifier of the category that the transaction item belongs to
   */
  categoryId?: number;
  /**
   * Status of the transaction
   */
  status?: string;
  /**
   * Identifier of the transaction timeline screen
   */
  screenId: 205;
  /**
   * Test group of the users
   */
  experiment?: "jtrex_tts_baseline" | "jtrex_tts_variation";
}
