/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the section of favorite items
 */
export interface ViewFavoriteItems {
  /**
   * Identifier of my favorite items section screen
   */
  screenId: 194;
  /**
   * Number of different items the user has in the my favorite items section
   */
  numberOfItems?: number;
  /**
   * Flag true or false is the view shows an empty state
   */
  emptyState?: boolean;
  /**
   * Name of the experiment or A/B testing applied to the user who has viewed the favorite items section.
   */
  experiment?: string;
}
