/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views the terms&conditions and communications screen in which they need to check the update
 */
export interface ViewTermsAndCommunicationsUpdate {
  /**
   * Identifier of the screen of Terms and Communications Update
   */
  screenId: 326;
}
