/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the screen asking to verify the phone during the onboarding
 */
export interface ViewOnboardingPhoneVerification {
  /**
   * Identifier of the Onboarding Phone Verification screen
   */
  screenId: 269;
}
