/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the register form to write their information in order to proceed with the registration process
 */
export interface ViewRegisterForm {
  /**
   * Identifier of the screen of the register form
   */
  screenId: 221;
}
