/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Seller views P2P Payment success screen
 */
export interface ViewP2PPaymentSuccessSeller {
  /**
   * Identifier of QR code screen
   */
  screenId: 280;
  /**
   * Amount the seller received
   */
  paymentAmount: number;
  /**
   * Hashed Id of the buyer
   */
  itemId?: string;
  /**
   * Hashed Id of the buyer
   */
  buyerUserId?: string;
}
