/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view login or register screen
 */
export interface ViewLoginRegisterScreen {
  /**
   * Identifier of the screen where the options to login or register appear
   */
  screenId: 177;
  /**
   * The source that takes the user to the login/register page
   */
  source?: 'landing_banner' | 'landing_details';
  /**
   * Name of the experiment or A/B testing applied to the user who has viewed the login register screen. The default value would be 'baseline'
   */
  experiment?: string;
  /**
   * The value proposition shown on the screen from the walkthrough slider
   */
  valuePropositionScreen?: 'sell' | 'buy' | 'your_way' | 'shipping' | 'safety';
}
