/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the Reset Password screen after clicking on link from the warning email
 */
export interface ViewResetPassword {
  /**
   * Identifier of the Reset Password screen
   */
  screenId: 251;
}
