/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views of all hashtags view in the upload
 */
export interface ViewHashtagsAllUpload {
  /**
   * Identifier of the category selected
   */
  categoryId: number;
  /**
   * Identifier of the screen
   */
  screenId: 231;
}
