/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views Subscription Management screen
 */
export interface ViewSubscriptionManagement {
  /**
   * Identifier of the Subscription Management screen
   */
  screenId: 191;
}
