/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Seller views scanning screen for the QR code for P2P payment
 */
export interface ViewP2PScanQRCode {
  /**
   * Identifier of QR code screen
   */
  screenId: 279;
}
