/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the section of messages
 */
export interface ViewMessages {
  /**
   * Identifier of my messages section screen
   */
  screenId: 228;
  /**
   * Number of unread messages the user has in the my messages section
   */
  numberOfUnreadMessages: number;
}
