/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the section of own completed sales
 */
export interface ViewCompletedSales {
  /**
   * Identifier of my catalog section screen
   */
  screenId: 308;
  /**
   * Flag true or false is the view shows an empty state
   */
  emptyState: boolean;
}
