/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views KYC upload identity verification screen
 */
export interface ViewKYCUploadIdentityVerificationScreen {
  /**
   * Identifier of the user viewing KYC upload identity verification screen
   */
  userId?: string;
  /**
   * Chosen nationality on the KYC identity verification screen (European Community - USA, UK and Canada - Rest of the world)
   */
  nationality: 'european_community' | 'usa_uk_and_canada' | 'rest_of_the_world';
  /**
   * Identifier of the KYC upload identity verification screen
   */
  screenId: 199;
}
