/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the section of favorite profiles
 */
export interface ViewFavoriteProfiles {
  /**
   * Identifier of the my favorite profiles section screen
   */
  screenId: 214;
  /**
   * Number of different profiles the user has in the my favorite profiles section
   */
  numberOfProfiles?: number;
  /**
   * Flag true or false is the view shows an empty state
   */
  emptyState?: boolean;
  /**
   * Name of the experiment or A/B testing applied to the user who has viewed the section of favorite profiles. The default value would be 'baseline'
   */
  experiment?: string;
}
