/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view login or register screen
 */
export interface ViewLoginRegisterScreen {
  /**
   * Identifier of the screen where the options to login or register appear
   */
  screenId: 177;
  /**
   * The source that takes the user to the login/register page
   */
  source?: 'landing_banner' | 'landing_details';
}
