/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the Login Verification Sent screen after trying a login with a suspicous device
 */
export interface ViewLoginVerificationSent {
  /**
   * Identifier of the Login Verification Sent screen
   */
  screenId: 284;
  /**
   * Name of the experiment or A/B testing applied to the user who has viewed the login verification sent screen. The default value would be 'baseline'
   */
  experiment?: string;
}
