/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views subscription screen (to purchase or manage subscriptions)
 */
export interface ViewSubscription {
  /**
   * Identifier of the Subscription screen
   */
  screenId: 191;
  /**
   * Whether the user is a PRO
   */
  isPro: boolean;
  /**
   * "All the subscription options that are shown as free trial"
   */
  freeTrialSubscriptions?: '100' | '100, 12800' | '100, 14000' | '100, 12800, 14000' | '12800' | '12800, 14000' | '14000';
}
