/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views Cars Subscription Payment Success screen
 */
export interface ViewCarsSubscriptionPaymentSuccess {
  /**
   * Identifier of the Car subscription plan chosen by user
   */
  planId: string;
  /**
   * Identifier of the Cars Subscription Paymnent Success screen
   */
  screenId: 208;
}
