/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views a popup explaining the advantages of a pro account
 */
export interface ViewProExpiredItemsPopup {
  /**
   * Identifier of the pro subscription expired items popup screen
   */
  screenId: 257;
  /**
   * If the view offers discount or not
   */
  discount?: boolean;
  /**
   * If the view offers free trial or not
   */
  freeTrial?: boolean;
}
