/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views shipping address screen from the shipping menu
 */
export interface ViewShippingAddress {
  /**
   * Identifier of the shipping address screen
   */
  screenId: 310;
}
