/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Buyer views screen to introduce manual code for seller
 */
export interface ViewP2PManualCode {
  /**
   * Identifier of QR code screen
   */
  screenId: 282;
}
