/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the Reset Password Error screen if the link has expired or any other error happens
 */
export interface ViewResetPasswordError {
  /**
   * Identifier of the Reset Password screen
   */
  screenId: 252;
  /**
   * The error caused when trying to access the link to reset the password
   */
  errorType: 'expired_link' | 'other';
}
