/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * View the verifications and security screen from own profile
 */
export interface ViewVerificationsAndSecurityScreen {
  /**
   * Identifier of the view verification and security screen
   */
  screenId: 248;
  /**
   * If the user has email verified
   */
  emailVerified: boolean;
  /**
   * If the user has phone number verified
   */
  phoneVerified: boolean;
  /**
   * If the user has Facebook profile verified
   */
  facebookVerified: boolean;
}
