/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views KYC tutorial screen
 */
export interface ViewKYCTutorialScreen {
  /**
   * Identifier of the KYC tutorial screen
   */
  userId?: string;
  /**
   * Identifier of the KYC tutorial screen
   */
  screenId: 196;
}
