/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the MGM host screen from where they can share a referral link
 */
export interface ViewMGMHostSection {
  /**
   * Identifier of the view own profile menu screen
   */
  screenId: 293;
  /**
   * Name of the experiment or A/B testing applied to the user who has performed the view. The default value would be 'baseline'
   */
  experiment?: string;
}
