/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views subscription screen categories (to purchase or manage subscriptions)
 */
export interface ViewSubscriptionCategories {
  /**
   * Identifier of the Subscription screen
   */
  screenId: 253;
}
