/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views shipping menu
 */
export interface ViewShippingMenu {
  /**
   * Identifier of the user viewing the shipping menu
   */
  userId: string;
  /**
   * Identifier of the shipping menu
   */
  screenId: 203;
}
