/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the verification screen for the register process after the filling in the register form successfully
 */
export interface ViewRegisterVerificationScreen {
  /**
   * The email address the user has introduced to verify the register process
   */
  emailAddress: string;
  /**
   * Identifier of the register verification screen
   */
  screenId: 222;
  /**
   * If the user has given consent for communications
   */
  communicationsConsent?: boolean;
}
