/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views error when trying to access Tracer
 */
export interface ViewTracerError {
  /**
   * Identifier of error screen
   */
  screenId: 288;
  /**
   * Error type for Tracer
   */
  errorType: 'expired' | 'already submitted';
}
