/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views KYC banner in chat inbox, shipping menu, shipping inbox or shipping timeline screen
 */
export interface ViewKYCBannerScreen {
  /**
   * Identifier of the user viewing KYC banner screen
   */
  userId?: string;
  /**
   * KYC status of the user viewing the banner
   */
  status: 'pending' | 'pending_verification' | 'verified' | 'rejected' | 'unneeded';
  /**
   * Identifier of the screen where the KYC banner is shown
   */
  screenId: 195 | 203 | 204 | 205;
}
