/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views the terms&conditions and communications screen in which they need to check the consent
 */
export interface ViewTermsCommunicationsConsent {
  /**
   * Identifier of the Terms and Communications Consent screen
   */
  screenId: 244;
  /**
   * The social source the user is using to register
   */
  socialSource: "apple" | "facebook" | "google";
}
