/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Screeb view of Edit Subscription Plan
 */
export interface ViewEditSubscriptionPlan {
  /**
   * Identifier of the screen from which the message was sent from
   */
  screenId: 191;
}
