/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views informative 3DS Popup
 */
export interface View3DSPopup {
  /**
   * Identifier of the popup screen
   */
  screenId: 283;
  /**
   * Hashed Id of the item of the shipping request
   */
  itemId?: string;
}
