/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * View own profile screen
 */
export interface ViewOwnProfile {
  /**
   * Identifier of the screen from which the message was sent from
   */
  screenId: number;
  /**
   * If the user profile is a pro user
   */
  isPro: boolean;
  /**
   * If the card of manage is shown
   */
  showManageCard?: boolean;
  /**
   * Name of the experiment or A/B testing applied to the user who has performed the view. The default value would be 'baseline'
   */
  experiment?: string;
}
