/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views error during the P2P flow
 */
export interface ViewP2PPaymentError {
  /**
   * Identifier of error screen
   */
  screenId: 277 | 281;
  /**
   * Error type for P2P payment
   */
  errorType: 'code generation failed' | 'code expired' | 'code invalid' | 'payment failed' | 'incorrect seller' | 'cancelled by seller';
}
