/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views main wallet screen with balance
 */
export interface ViewWallet {
  /**
   * Identifier of main wallet screen
   */
  screenId: 235;
  /**
   * Balance amount in the wallet
   */
  balanceAmount?: number;
  /**
   * Status of the KYC verification
   */
  kycStatus: "verified" | "pending" | "inProgress";
}
