/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views item detail screen with or without shipping info item dropdowns
 */
export interface ViewShippingInfoItem {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the category that the item belongs to
   */
  categoryId: number;
  /**
   * The unique identifier of the search that the click is under
   */
  searchId?: string;
  /**
   * If the item clicked is from a professional user
   */
  isPro?: boolean;
  /**
   * Item price without fees
   */
  itemPrice: number;
  /**
   * Item title
   */
  title: string;
  /**
   * If the user is in the experiment shipping info item, the value is shipping_info_experiment or baseline. If it's not, the value is empty string
   */
  experiment: string;
  /**
   * Identifier of the item detail screen
   */
  screenId: 115;
}
