/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the popup that requires updating the app version
 */
export interface ViewRequiredUpdateAppVersionPopup {
  /**
   * Identifier of the required update app version popup screen
   */
  screenId: 266;
}
