/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Buyer views P2P payment success screen
 */
export interface ViewP2PPaymentSuccessBuyer {
  /**
   * Identifier of QR code screen
   */
  screenId: 278;
  /**
   * Amount the user paid
   */
  paymentAmount: number;
}
