/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views of item edit screen
 */
export interface ViewEditItem {
  /**
   * Identifier of the category selected
   */
  categoryId: number;
  /**
   * Identifier of the edit screen
   */
  screenId: 41;
  /**
   * Name of the experiment or A/B testing applied to the user who is editing the item. The default value would be 'baseline'
   */
  experiment?: string;
  /**
   * If the item has to add extra info
   */
  mandatoryAdditionalFields?: boolean;
}
