/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views wallet movements history
 */
export interface ViewWalletMovementsHistory {
  /**
   * Identifier of the different wallet movement history tabs
   */
  screenId: 254 | 255 | 256;
  /**
   * Whether the view shows an empty state
   */
  emptyState: boolean;
}
