/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the notification settings screen
 */
export interface ViewNotificationSettings {
  /**
   * Identifier of the screen where the user can activate or deactivate different types of notifications
   */
  screenId: 320;
}
