/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the Login Verification Error screen if the link has expired or any other error happens
 */
export interface ViewLoginVerificationError {
  /**
   * Identifier of the Login Verification Error screen
   */
  screenId: 286;
  /**
   * The error caused when clicking the link to accept or reject the suspicious login
   */
  errorType: 'expired_link' | 'other';
  /**
   * If the clicked clicked link in the email comes from accepting or rejecting the suspicious login
   */
  linkSource?: 'accept' | 'reject';
}
