/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views Edit Profile
 */
export interface ViewEditProfile {
  /**
   * Identifier of the Edit Profile screen
   */
  screenId: 148;
  /**
   * If the item is from a professional user
   */
  isPro: boolean;
  /**
   * Name of the experiment or A/B testing applied to the user who has performed the view. The default value would be 'baseline'
   */
  experiment?: string;
}
