/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views Cars Subscription screen
 */
export interface ViewCarsSubscription {
  /**
   * Identifier of the Cars subscription screen
   */
  screenId: 207;
}
