/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views TTS
 */
export interface ViewTransactionalTimeline {
  /**
   * Identifier of the transaction request
   */
  requestId: string;
  /**
   * Identifier of the transaction timeline screen
   */
  screenId: 205;
  /**
   * From where the user accesses the TRACER screen
   */
  source?: 'tracer-push' | 'mail' | 'N/A';
}
