/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views of pro subscription popup when limit reached
 */
export interface ViewProSubscriptionPopup {
  /**
   * Identifier of the pro subscription limit popup screen
   */
  screenId: 230;
  /**
   * If the view offers free trial or not
   */
  freeTrial?: boolean;
  /**
   * Subscription category type that reached the limit
   */
  subscription: 0 | 100 | 14000 | 12800;
  /**
   * If the user is a cardealer
   */
  isCarDealer: boolean;
}
