/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User PRO views purchase option between subscription bump or a new bump
 */
export interface ViewProBumpPurchaseOption {
  /**
   * The unique identifier for an item
   */
  itemId: string;
  /**
   * Identifier of the screen that the item was clicked from
   */
  screenId: 319;
}
