/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views transactional buyer tutorial
 */
export interface ViewTransactionalTutorialBuyer {
  /**
   * Identifier of the screen in which the user has clicked to see the transactional buyer tutorial
   */
  screenId: 115 | 209;
}
