/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views TRACER survey
 */
export interface ViewTracer {
  /**
   * Identifier of the transaction
   */
  transactionId: string;
  /**
   * Identifier of the transaction timeline screen
   */
  screenId: 268;
  /**
   * Indicates if the user comes from an external source
   */
  source?: 'tracer-push' | 'N/A';
}
