/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the MGM info after clicking More Info in the MGM Host Section
 */
export interface ViewMGMHostInfo {
  /**
   * Identifier of the screen that the link was shared from
   */
  screenId: 294;
}
