/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the section of own items for sale
 */
export interface ViewOwnSaleItems {
  /**
   * Identifier of my catalog section screen
   */
  screenId: 219;
  /**
   * Number of items for sale
   */
  numberOfItems?: number;
  /**
   * Flag true or false is the view shows an empty state
   */
  emptyState?: boolean;
  /**
   * Name of the experiment or A/B testing applied to the user who has viewed the items for sale section.
   */
  experiment?: string;
  /**
   * Whether a promotional banner for subscriptions is displayed
   */
  proSubscriptionBanner?: boolean;
}
