/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users view the Featured Items screen after having clicked on See All in the Bump Slider
 */
export interface ViewSeeAllBumpSlider {
  /**
   * Identifier of the screen where the bumped items are being seen
   */
  screenId: 187;
  /**
   * The unique identifier of the search
   */
  searchId: string;
}
