/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views KYC verifying identity screen
 */
export interface ViewKYCVerifyingIdentityScreen {
  /**
   * Identifier of the user viewing KYC verifying identity screen
   */
  userId?: string;
  /**
   * Identifier of the KYC verifying identity screen
   */
  screenId: 202;
}
