/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views Subscription tier screen (to choose the tier within the subscription)
 */
export interface ViewSubscriptionTier {
  /**
   * Identifier of the Subscription tier screen
   */
  screenId: 241;
  /**
   * Whether the subscription clicked offers free trial
   */
  freeTrial: boolean;
}
