/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users views the reactivation popup of shipping allowed
 */
export interface ViewReactivationShippingPopUp {
  /**
   * Identifier of the item selected
   */
  itemId: number;
  /**
   * Identifier of the popup screen
   */
  screenId: 41;
}
