/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User views the popup that suggests updating the app version
 */
export interface ViewSuggestedUpdateAppVersionPopup {
  /**
   * Identifier of the suggested update app version popup screen
   */
  screenId: 265;
}
