export enum CAR_ICON {
  SEATS = '/assets/icons/cars/car_seats.svg',
  COUPE = '/assets/icons/cars/coupe_car.svg',
  FAMILY = '/assets/icons/cars/family_car.svg',
  MINI_VAN = '/assets/icons/cars/minivan_car.svg',
  SEDAN = '/assets/icons/cars/sedan_car.svg',
  SMALL = '/assets/icons/cars/little_car.svg',
  VAN = '/assets/icons/cars/van_car.svg',
  FXF = '/assets/icons/cars/offroad_car.svg',
  OTHERS = '/assets/icons/cars/others.svg',
  TWO_DOORS = '/assets/icons/cars/doors2_car.svg',
  THREE_DOORS = '/assets/icons/cars/doors3_car.svg',
  FOUR_DOORS = '/assets/icons/cars/doors4_car.svg',
  FIVE_DOORS = '/assets/icons/cars/doors5_car.svg',
  HORSEPOWER = '/assets/icons/cars/horsepower.svg',
  ELECTRIC = '/assets/icons/cars/socket.svg',
  GASOIL = '/assets/icons/cars/diesel.svg',
  GASOLINE = '/assets/icons/cars/gasoline.svg',
  AUTOMATIC = '/assets/icons/cars/automatic_gearbox.svg',
  MANUAL = '/assets/icons/cars/car_gears.svg',
  BRAND_NEW = '/assets/icons/cars/new_car_ribbon.svg',
  MINT = '/assets/icons/cars/impeccable_car.svg',
  SOME_BLOW = '/assets/icons/cars/blow_car.svg',
  CRAPPY = '/assets/icons/cars/crappy_car.svg',
}
