export enum CAR_ICON {
  SEATS = '/assets/icons/seats.svg',
  COUPE = '/assets/icons/coupe_cabrio.svg',
  FAMILY = '/assets/icons/family_car.svg',
  MINI_VAN = '/assets/icons/mini_van.svg',
  SEDAN = '/assets/icons/sedan.svg',
  SMALL = '/assets/icons/small_car.svg',
  VAN = '/assets/icons/van.svg',
  FXF = '/assets/icons/4X4.svg',
  OTHERS = '/assets/icons/other.svg',
  TWO_DOORS = '/assets/icons/car_two_doors.svg',
  THREE_DOORS = '/assets/icons/car_three_doors.svg',
  FOUR_DOORS = '/assets/icons/car_four_doors.svg',
  FIVE_DOORS = '/assets/icons/car_five_doors.svg',
  HORSEPOWER = '/assets/icons/horsepower.svg',
  ELECTRIC = '/assets/icons/electric-hybrid.svg',
  GASOIL = '/assets/icons/gasoil.svg',
  GASOLINE = '/assets/icons/gasoline.svg',
  AUTOMATIC = '/assets/icons/automatic.svg',
  MANUAL = '/assets/icons/manual.svg',
  CONDITION_0 = '/assets/icons/brand_new.svg',
  CONDITION_1 = '/assets/icons/mint.svg',
  CONDITION_2 = '/assets/icons/some_blow.svg',
  CONDITION_3 = '/assets/icons/crappy.svg',
}
